// <auto-generated>
//     Code generated by opensdk. DO NOT EDIT.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Example.UnionDepot.Tests;

public class LogsTests
{
    [Fact]
    public async Task MethodList()
    {
        string baseUrl = TestServer.BaseUrl();
        if (!TestServer.Check(baseUrl))
        {
            return;
        }
        var client = new UnionDepotClient(apiKey: "My API Key", baseUrl: baseUrl);
        var result = await client.Logs.List();
        Assert.NotNull(result);
    }

    [Fact]
    public async Task MethodListWithAllParams()
    {
        string baseUrl = TestServer.BaseUrl();
        if (!TestServer.Check(baseUrl))
        {
            return;
        }
        var client = new UnionDepotClient(apiKey: "My API Key", baseUrl: baseUrl);
        var result = await client.Logs.List(0, 0);
        Assert.NotNull(result);
    }
}
