// Code generated by opensdk. DO NOT EDIT.

package openai

import (
	"context"
	"fmt"
	"net/http"

	"github.com/example/openai/internal/requestconfig"
	"github.com/example/openai/option"
	"github.com/example/openai/packages/pagination"
	"github.com/example/openai/packages/param"
)

// FileService ...
type FileService struct {
	Options []option.RequestOption
}

// NewFileService constructs a service that shares the client's request options.
func NewFileService(opts ...option.RequestOption) (r FileService) {
	r = FileService{}
	r.Options = opts
	return
}

// Returns a list of files.
func (r *FileService) List(ctx context.Context, query FileListParams, opts ...option.RequestOption) (res *pagination.CursorPage[OpenAiFile], err error) {
	opts = append(r.Options[:], opts...)
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, "files", nil, opts...)
	if err != nil {
		return
	}
	if query.Purpose.IsPresent() {
		cfg.Query.Set("purpose", fmt.Sprintf("%v", query.Purpose.Value()))
	}
	if query.Limit.IsPresent() {
		cfg.Query.Set("limit", fmt.Sprintf("%v", query.Limit.Value()))
	}
	if query.Order.IsPresent() {
		cfg.Query.Set("order", fmt.Sprintf("%v", query.Order.Value()))
	}
	if query.After.IsPresent() {
		cfg.Query.Set("after", fmt.Sprintf("%v", query.After.Value()))
	}
	res = &pagination.CursorPage[OpenAiFile]{}
	err = cfg.Execute(res)
	if err != nil {
		return
	}
	res.SetPageConfig(cfg, "after")
	return
}

type FileListParams struct {
	Purpose param.Opt[string] `json:"-" query:"purpose"`
	Limit param.Opt[int64] `json:"-" query:"limit"`
	Order param.Opt[FilesListOrder] `json:"-" query:"order"`
	After param.Opt[string] `json:"-" query:"after"`
}
