// Code generated by opencli2rust. DO NOT EDIT.

use std::process::ExitCode;

use clap::{Arg, ArgMatches, Command};

use crate::gen::runtime::{self, CliOverrides, Context};

pub fn command() -> Command {
    Command::new("fine-tuning")
        .subcommand_required(true)
        .arg_required_else_help(true)
        .subcommand(
            Command::new("checkpoints")
                .subcommand_required(true)
                .arg_required_else_help(true)
                .subcommand(
                    Command::new("permissions")
                        .subcommand_required(true)
                        .arg_required_else_help(true)
                        .subcommand(
                            Command::new("list")
                                .about("**NOTE:** This endpoint requires an [admin API key](../admin-api-keys).\n\nOrganization owners can use this endpoint to view all permissions for a fine-tuned model checkpoint.\n")
                                .arg(
                                    Arg::new("fine-tuned-model-checkpoint")
                                        .help("The ID of the fine-tuned model checkpoint to get permissions for.\n")
                                        .required(true),
                                )
                                .arg(
                                    Arg::new("project-id")
                                        .long("project-id")
                                        .help("The ID of the project to get permissions for."),
                                )
                                .arg(
                                    Arg::new("after")
                                        .long("after")
                                        .help("Identifier for the last permission ID from the previous pagination request."),
                                )
                                .arg(
                                    Arg::new("limit")
                                        .long("limit")
                                        .value_parser(clap::value_parser!(i64))
                                        .help("Number of permissions to retrieve."),
                                )
                                .arg(
                                    Arg::new("order")
                                        .long("order")
                                        .help("The order in which to retrieve permissions."),
                                ),
                        ),
                ),
        )
}

pub async fn run<O: CliOverrides>(ctx: &Context, o: &O, cmd_path: &[String], m: &ArgMatches) -> ExitCode {
    let parts: Vec<&str> = cmd_path.iter().map(String::as_str).collect();
    match parts.as_slice() {
        ["fine-tuning", "checkpoints", "permissions", "list"] => handle_fine_tuning_checkpoints_permissions_list(ctx, o, cmd_path, m).await,
        _ => {
            eprintln!("error: unknown command: {}", cmd_path.join(" "));
            ExitCode::FAILURE
        }
    }
}

async fn handle_fine_tuning_checkpoints_permissions_list<O: CliOverrides>(
    ctx: &Context,
    o: &O,
    cmd_path: &[String],
    m: &ArgMatches,
) -> ExitCode {
    let fine_tuned_model_checkpoint = m.get_one::<String>("fine-tuned-model-checkpoint").map(String::as_str).unwrap_or("");
    let path = format!("/fine_tuning/checkpoints/{}/permissions", runtime::path_escape(fine_tuned_model_checkpoint));
    let mut query: Vec<(&'static str, String)> = Vec::new();
    if let Some(v) = m.get_one::<String>("project-id") {
        query.push(("project_id", v.clone()));
    }
    if let Some(v) = m.get_one::<String>("after") {
        query.push(("after", v.clone()));
    }
    if let Some(v) = m.get_one::<i64>("limit") {
        query.push(("limit", v.to_string()));
    }
    if let Some(v) = m.get_one::<String>("order") {
        query.push(("order", v.clone()));
    }
    let req = runtime::Request {
        method: "GET",
        path,
        query,
        headers: Vec::new(),
        body: None,
    };
    runtime::run_request(ctx, o, cmd_path, req).await
}
