# Code generated by opensdk. DO NOT EDIT.

module Openai
  module Resources
    class Beta
      attr_reader :threads

      # @api private
      def initialize(transport)
        @transport = transport
        @threads = BetaThreads.new(transport)
      end
    end

    class BetaThreads
      # @api private
      def initialize(transport)
        @transport = transport
      end

      # Retrieves a thread.
      #
      # @param thread_id [String]
      # @return [Models::ThreadObject]
      def retrieve(thread_id)
        raise ArgumentError, "Expected a non-empty value for `thread_id`" if thread_id.nil? || thread_id.to_s.empty?

        @transport.request(
          method: :get,
          path: "/threads/#{thread_id}"
        )
      end
    end
  end
end
