// Code generated by opensdk. DO NOT EDIT.

package openai

import (
	"context"
	"errors"
	"fmt"
	"net/http"

	"github.com/example/openai/internal/requestconfig"
	"github.com/example/openai/option"
	"github.com/example/openai/packages/apijson"
	"github.com/example/openai/packages/pagination"
	"github.com/example/openai/packages/param"
)

// FineTuningService ...
type FineTuningService struct {
	Options []option.RequestOption
	Alpha FineTuningAlphaService
	Checkpoints FineTuningCheckpointService
	Jobs FineTuningJobService
}

// NewFineTuningService constructs a service that shares the client's request options.
func NewFineTuningService(opts ...option.RequestOption) (r FineTuningService) {
	r = FineTuningService{}
	r.Options = opts
	r.Alpha = NewFineTuningAlphaService(opts...)
	r.Checkpoints = NewFineTuningCheckpointService(opts...)
	r.Jobs = NewFineTuningJobService(opts...)
	return
}

// FineTuningAlphaService ...
type FineTuningAlphaService struct {
	Options []option.RequestOption
	Graders FineTuningAlphaGraderService
}

// NewFineTuningAlphaService constructs a service that shares the client's request options.
func NewFineTuningAlphaService(opts ...option.RequestOption) (r FineTuningAlphaService) {
	r = FineTuningAlphaService{}
	r.Options = opts
	r.Graders = NewFineTuningAlphaGraderService(opts...)
	return
}

// FineTuningAlphaGraderService ...
type FineTuningAlphaGraderService struct {
	Options []option.RequestOption
	Run FineTuningAlphaGraderRunService
	Validate FineTuningAlphaGraderValidateService
}

// NewFineTuningAlphaGraderService constructs a service that shares the client's request options.
func NewFineTuningAlphaGraderService(opts ...option.RequestOption) (r FineTuningAlphaGraderService) {
	r = FineTuningAlphaGraderService{}
	r.Options = opts
	r.Run = NewFineTuningAlphaGraderRunService(opts...)
	r.Validate = NewFineTuningAlphaGraderValidateService(opts...)
	return
}

// FineTuningAlphaGraderRunService ...
type FineTuningAlphaGraderRunService struct {
	Options []option.RequestOption
}

// NewFineTuningAlphaGraderRunService constructs a service that shares the client's request options.
func NewFineTuningAlphaGraderRunService(opts ...option.RequestOption) (r FineTuningAlphaGraderRunService) {
	r = FineTuningAlphaGraderRunService{}
	r.Options = opts
	return
}

// Run a grader.
func (r *FineTuningAlphaGraderRunService) New(ctx context.Context, body FineTuningAlphaGraderRunNewParams, opts ...option.RequestOption) (res *RunGraderResponse, err error) {
	opts = append(r.Options[:], opts...)
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodPost, "fine_tuning/alpha/graders/run", body, opts...)
	if err != nil {
		return
	}
	res = &RunGraderResponse{}
	err = cfg.Execute(res)
	return
}

type FineTuningAlphaGraderRunNewParams struct {
	Grader RunGraderRequestGrader `json:"grader,required"`
	Item map[string]any `json:"item,omitempty"`
	ModelSample string `json:"model_sample,required"`
}

func (r FineTuningAlphaGraderRunNewParams) MarshalJSON() ([]byte, error) {
	return apijson.MarshalRoot(r)
}

// FineTuningAlphaGraderValidateService ...
type FineTuningAlphaGraderValidateService struct {
	Options []option.RequestOption
}

// NewFineTuningAlphaGraderValidateService constructs a service that shares the client's request options.
func NewFineTuningAlphaGraderValidateService(opts ...option.RequestOption) (r FineTuningAlphaGraderValidateService) {
	r = FineTuningAlphaGraderValidateService{}
	r.Options = opts
	return
}

// Validate a grader.
func (r *FineTuningAlphaGraderValidateService) New(ctx context.Context, body FineTuningAlphaGraderValidateNewParams, opts ...option.RequestOption) (res *ValidateGraderResponse, err error) {
	opts = append(r.Options[:], opts...)
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodPost, "fine_tuning/alpha/graders/validate", body, opts...)
	if err != nil {
		return
	}
	res = &ValidateGraderResponse{}
	err = cfg.Execute(res)
	return
}

type FineTuningAlphaGraderValidateNewParams struct {
	Grader ValidateGraderRequestGrader `json:"grader,required"`
}

func (r FineTuningAlphaGraderValidateNewParams) MarshalJSON() ([]byte, error) {
	return apijson.MarshalRoot(r)
}

// FineTuningCheckpointService ...
type FineTuningCheckpointService struct {
	Options []option.RequestOption
	Permissions FineTuningCheckpointPermissionService
}

// NewFineTuningCheckpointService constructs a service that shares the client's request options.
func NewFineTuningCheckpointService(opts ...option.RequestOption) (r FineTuningCheckpointService) {
	r = FineTuningCheckpointService{}
	r.Options = opts
	r.Permissions = NewFineTuningCheckpointPermissionService(opts...)
	return
}

// FineTuningCheckpointPermissionService ...
type FineTuningCheckpointPermissionService struct {
	Options []option.RequestOption
}

// NewFineTuningCheckpointPermissionService constructs a service that shares the client's request options.
func NewFineTuningCheckpointPermissionService(opts ...option.RequestOption) (r FineTuningCheckpointPermissionService) {
	r = FineTuningCheckpointPermissionService{}
	r.Options = opts
	return
}

// **NOTE:** Calling this endpoint requires an [admin API key](../admin-api-keys).
//
// This enables organization owners to share fine-tuned models with other projects in their organization.
func (r *FineTuningCheckpointPermissionService) New(ctx context.Context, fineTunedModelCheckpoint string, body FineTuningCheckpointPermissionNewParams, opts ...option.RequestOption) (res *pagination.CursorPage[FineTuningCheckpointPermission], err error) {
	opts = append(r.Options[:], opts...)
	if fineTunedModelCheckpoint == "" {
		err = errors.New("missing required fine_tuned_model_checkpoint parameter")
		return
	}
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodPost, fmt.Sprintf("fine_tuning/checkpoints/%v/permissions", fineTunedModelCheckpoint), body, opts...)
	if err != nil {
		return
	}
	res = &pagination.CursorPage[FineTuningCheckpointPermission]{}
	err = cfg.Execute(res)
	return
}

// **NOTE:** This endpoint requires an [admin API key](../admin-api-keys).
//
// Organization owners can use this endpoint to delete a permission for a fine-tuned model checkpoint.
func (r *FineTuningCheckpointPermissionService) Delete(ctx context.Context, fineTunedModelCheckpoint string, permissionID string, opts ...option.RequestOption) (res *DeleteFineTuningCheckpointPermissionResponse, err error) {
	opts = append(r.Options[:], opts...)
	if fineTunedModelCheckpoint == "" {
		err = errors.New("missing required fine_tuned_model_checkpoint parameter")
		return
	}
	if permissionID == "" {
		err = errors.New("missing required permission_id parameter")
		return
	}
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodDelete, fmt.Sprintf("fine_tuning/checkpoints/%v/permissions/%v", fineTunedModelCheckpoint, permissionID), nil, opts...)
	if err != nil {
		return
	}
	res = &DeleteFineTuningCheckpointPermissionResponse{}
	err = cfg.Execute(res)
	return
}

// **NOTE:** This endpoint requires an [admin API key](../admin-api-keys).
//
// Organization owners can use this endpoint to view all permissions for a fine-tuned model checkpoint.
func (r *FineTuningCheckpointPermissionService) List(ctx context.Context, fineTunedModelCheckpoint string, query FineTuningCheckpointPermissionListParams, opts ...option.RequestOption) (res *pagination.CursorPage[FineTuningCheckpointPermission], err error) {
	opts = append(r.Options[:], opts...)
	if fineTunedModelCheckpoint == "" {
		err = errors.New("missing required fine_tuned_model_checkpoint parameter")
		return
	}
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, fmt.Sprintf("fine_tuning/checkpoints/%v/permissions", fineTunedModelCheckpoint), nil, opts...)
	if err != nil {
		return
	}
	if query.ProjectID.IsPresent() {
		cfg.Query.Set("project_id", fmt.Sprintf("%v", query.ProjectID.Value()))
	}
	if query.After.IsPresent() {
		cfg.Query.Set("after", fmt.Sprintf("%v", query.After.Value()))
	}
	if query.Limit.IsPresent() {
		cfg.Query.Set("limit", fmt.Sprintf("%v", query.Limit.Value()))
	}
	if query.Order.IsPresent() {
		cfg.Query.Set("order", fmt.Sprintf("%v", query.Order.Value()))
	}
	res = &pagination.CursorPage[FineTuningCheckpointPermission]{}
	err = cfg.Execute(res)
	if err != nil {
		return
	}
	res.SetPageConfig(cfg, "after")
	return
}

type FineTuningCheckpointPermissionNewParams struct {
	ProjectIds []string `json:"project_ids,required"`
}

func (r FineTuningCheckpointPermissionNewParams) MarshalJSON() ([]byte, error) {
	return apijson.MarshalRoot(r)
}

type FineTuningCheckpointPermissionListParams struct {
	ProjectID param.Opt[string] `json:"-" query:"project_id"`
	After param.Opt[string] `json:"-" query:"after"`
	Limit param.Opt[int64] `json:"-" query:"limit"`
	Order param.Opt[FineTuningCheckpointsPermissionsListOrder] `json:"-" query:"order"`
}

// FineTuningJobService ...
type FineTuningJobService struct {
	Options []option.RequestOption
	Checkpoints FineTuningJobCheckpointService
}

// NewFineTuningJobService constructs a service that shares the client's request options.
func NewFineTuningJobService(opts ...option.RequestOption) (r FineTuningJobService) {
	r = FineTuningJobService{}
	r.Options = opts
	r.Checkpoints = NewFineTuningJobCheckpointService(opts...)
	return
}

// Immediately cancel a fine-tune job.
func (r *FineTuningJobService) Cancel(ctx context.Context, fineTuningJobID string, opts ...option.RequestOption) (res *FineTuningJob, err error) {
	opts = append(r.Options[:], opts...)
	if fineTuningJobID == "" {
		err = errors.New("missing required fine_tuning_job_id parameter")
		return
	}
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodPost, fmt.Sprintf("fine_tuning/jobs/%v/cancel", fineTuningJobID), nil, opts...)
	if err != nil {
		return
	}
	res = &FineTuningJob{}
	err = cfg.Execute(res)
	return
}

// Creates a fine-tuning job which begins the process of creating a new model from a given dataset.
//
// Response includes details of the enqueued job including job status and the name of the fine-tuned models once complete.
//
// [Learn more about fine-tuning](/docs/guides/model-optimization)
func (r *FineTuningJobService) New(ctx context.Context, body FineTuningJobNewParams, opts ...option.RequestOption) (res *FineTuningJob, err error) {
	opts = append(r.Options[:], opts...)
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodPost, "fine_tuning/jobs", body, opts...)
	if err != nil {
		return
	}
	res = &FineTuningJob{}
	err = cfg.Execute(res)
	return
}

// List your organization's fine-tuning jobs
func (r *FineTuningJobService) List(ctx context.Context, query FineTuningJobListParams, opts ...option.RequestOption) (res *pagination.CursorPage[FineTuningJob], err error) {
	opts = append(r.Options[:], opts...)
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, "fine_tuning/jobs", nil, opts...)
	if err != nil {
		return
	}
	if query.After.IsPresent() {
		cfg.Query.Set("after", fmt.Sprintf("%v", query.After.Value()))
	}
	if query.Limit.IsPresent() {
		cfg.Query.Set("limit", fmt.Sprintf("%v", query.Limit.Value()))
	}
	for mapKey, mapValue := range query.Metadata {
		cfg.Query.Set(fmt.Sprintf("metadata[%v]", mapKey), fmt.Sprintf("%v", mapValue))
	}
	res = &pagination.CursorPage[FineTuningJob]{}
	err = cfg.Execute(res)
	if err != nil {
		return
	}
	res.SetPageConfig(cfg, "after")
	return
}

// Get status updates for a fine-tuning job.
func (r *FineTuningJobService) ListEvents(ctx context.Context, fineTuningJobID string, query FineTuningJobListEventsParams, opts ...option.RequestOption) (res *pagination.CursorPage[FineTuningJobEvent], err error) {
	opts = append(r.Options[:], opts...)
	if fineTuningJobID == "" {
		err = errors.New("missing required fine_tuning_job_id parameter")
		return
	}
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, fmt.Sprintf("fine_tuning/jobs/%v/events", fineTuningJobID), nil, opts...)
	if err != nil {
		return
	}
	if query.After.IsPresent() {
		cfg.Query.Set("after", fmt.Sprintf("%v", query.After.Value()))
	}
	if query.Limit.IsPresent() {
		cfg.Query.Set("limit", fmt.Sprintf("%v", query.Limit.Value()))
	}
	res = &pagination.CursorPage[FineTuningJobEvent]{}
	err = cfg.Execute(res)
	if err != nil {
		return
	}
	res.SetPageConfig(cfg, "after")
	return
}

// Pause a fine-tune job.
func (r *FineTuningJobService) Pause(ctx context.Context, fineTuningJobID string, opts ...option.RequestOption) (res *FineTuningJob, err error) {
	opts = append(r.Options[:], opts...)
	if fineTuningJobID == "" {
		err = errors.New("missing required fine_tuning_job_id parameter")
		return
	}
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodPost, fmt.Sprintf("fine_tuning/jobs/%v/pause", fineTuningJobID), nil, opts...)
	if err != nil {
		return
	}
	res = &FineTuningJob{}
	err = cfg.Execute(res)
	return
}

// Resume a fine-tune job.
func (r *FineTuningJobService) Resume(ctx context.Context, fineTuningJobID string, opts ...option.RequestOption) (res *FineTuningJob, err error) {
	opts = append(r.Options[:], opts...)
	if fineTuningJobID == "" {
		err = errors.New("missing required fine_tuning_job_id parameter")
		return
	}
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodPost, fmt.Sprintf("fine_tuning/jobs/%v/resume", fineTuningJobID), nil, opts...)
	if err != nil {
		return
	}
	res = &FineTuningJob{}
	err = cfg.Execute(res)
	return
}

// Get info about a fine-tuning job.
//
// [Learn more about fine-tuning](/docs/guides/model-optimization)
func (r *FineTuningJobService) Get(ctx context.Context, fineTuningJobID string, opts ...option.RequestOption) (res *FineTuningJob, err error) {
	opts = append(r.Options[:], opts...)
	if fineTuningJobID == "" {
		err = errors.New("missing required fine_tuning_job_id parameter")
		return
	}
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, fmt.Sprintf("fine_tuning/jobs/%v", fineTuningJobID), nil, opts...)
	if err != nil {
		return
	}
	res = &FineTuningJob{}
	err = cfg.Execute(res)
	return
}

type FineTuningJobNewParams struct {
	Model CreateFineTuningJobRequestModel `json:"model,required"`
	TrainingFile string `json:"training_file,required"`
	Hyperparameters CreateFineTuningJobRequestHyperparameters `json:"hyperparameters,omitempty"`
	Suffix param.Opt[string] `json:"suffix,omitempty"`
	ValidationFile param.Opt[string] `json:"validation_file,omitempty"`
	Integrations []CreateFineTuningJobRequestIntegrationsItem `json:"integrations,omitempty"`
	Seed param.Opt[int64] `json:"seed,omitempty"`
	Method FineTuneMethod `json:"method,omitempty"`
	Metadata Metadata `json:"metadata,omitempty"`
}

func (r FineTuningJobNewParams) MarshalJSON() ([]byte, error) {
	return apijson.MarshalRoot(r)
}

type FineTuningJobListParams struct {
	After param.Opt[string] `json:"-" query:"after"`
	Limit param.Opt[int64] `json:"-" query:"limit"`
	Metadata map[string]string `json:"-" query:"metadata"`
}

type FineTuningJobListEventsParams struct {
	After param.Opt[string] `json:"-" query:"after"`
	Limit param.Opt[int64] `json:"-" query:"limit"`
}

// FineTuningJobCheckpointService ...
type FineTuningJobCheckpointService struct {
	Options []option.RequestOption
}

// NewFineTuningJobCheckpointService constructs a service that shares the client's request options.
func NewFineTuningJobCheckpointService(opts ...option.RequestOption) (r FineTuningJobCheckpointService) {
	r = FineTuningJobCheckpointService{}
	r.Options = opts
	return
}

// List checkpoints for a fine-tuning job.
func (r *FineTuningJobCheckpointService) List(ctx context.Context, fineTuningJobID string, query FineTuningJobCheckpointListParams, opts ...option.RequestOption) (res *pagination.CursorPage[FineTuningJobCheckpoint], err error) {
	opts = append(r.Options[:], opts...)
	if fineTuningJobID == "" {
		err = errors.New("missing required fine_tuning_job_id parameter")
		return
	}
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, fmt.Sprintf("fine_tuning/jobs/%v/checkpoints", fineTuningJobID), nil, opts...)
	if err != nil {
		return
	}
	if query.After.IsPresent() {
		cfg.Query.Set("after", fmt.Sprintf("%v", query.After.Value()))
	}
	if query.Limit.IsPresent() {
		cfg.Query.Set("limit", fmt.Sprintf("%v", query.Limit.Value()))
	}
	res = &pagination.CursorPage[FineTuningJobCheckpoint]{}
	err = cfg.Execute(res)
	if err != nil {
		return
	}
	res.SetPageConfig(cfg, "after")
	return
}

type FineTuningJobCheckpointListParams struct {
	After param.Opt[string] `json:"-" query:"after"`
	Limit param.Opt[int64] `json:"-" query:"limit"`
}
