// <auto-generated>
//     Code generated by opensdk. DO NOT EDIT.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace Example.Openai;

public sealed class SkillsService
{
    private readonly Transport _transport;
    public SkillsVersionsService Versions { get; }

    internal SkillsService(Transport transport)
    {
        _transport = transport;
        Versions = new SkillsVersionsService(transport);
    }
}

public sealed class SkillsVersionsService
{
    private readonly Transport _transport;

    internal SkillsVersionsService(Transport transport)
    {
        _transport = transport;
    }

    /// <summary>Create a new immutable skill version.</summary>
    public async Task<SkillVersionResource> Create(string skillId, CreateSkillVersionBody? body = null, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrEmpty(skillId))
        {
            throw new ArgumentException("Expected a non-empty value for skillId.", nameof(skillId));
        }
        var bodyMap = new Dictionary<string, object?>
        {
            ["files"] = body.Files,
            ["default"] = body.Default,
        };
        return await _transport.RequestAsync<SkillVersionResource>(HttpMethod.Post, $"/skills/{skillId}/versions", body: bodyMap, encoding: "multipart", cancellationToken: cancellationToken).ConfigureAwait(false);
    }
}
