// Code generated by opencli2rust. DO NOT EDIT.

use std::process::ExitCode;

use clap::{Arg, ArgMatches, Command};

use crate::opencli::runtime::{CliOverrides, Context};

pub fn command() -> Command {
    Command::new("components")
        .about("Manage xyd components")
        .subcommand_required(true)
        .arg_required_else_help(true)
        .subcommand(
            Command::new("install")
                .about("Install a xyd component into your project")
                .arg(
                    Arg::new("component")
                        .help("Name of the component to install")
                        .value_parser(["diagrams", "opensdk"])
                        .required(true),
                ),
        )
        .subcommand(
            Command::new("uninstall")
                .about("Remove an installed xyd component")
                .arg(
                    Arg::new("component")
                        .help("Name of the component to remove")
                        .value_parser(["opensdk"])
                        .required(true),
                ),
        )
}

pub async fn run<O: CliOverrides>(
    _ctx: &Context,
    _o: &O,
    cmd_path: &[String],
    _m: &ArgMatches,
) -> ExitCode {
    let parts: Vec<&str> = cmd_path.iter().map(String::as_str).collect();
    match parts.as_slice() {
        _ => {
            eprintln!("error: unknown command: {}", cmd_path.join(" "));
            ExitCode::FAILURE
        }
    }
}
