// Code generated by opencli2rust. DO NOT EDIT.

use std::process::ExitCode;

use clap::{Arg, ArgMatches, Command};

use crate::gen::runtime::{self, CliOverrides, Context};

pub fn command() -> Command {
    Command::new("threads")
        .subcommand_required(true)
        .arg_required_else_help(true)
        .subcommand(
            Command::new("create")
                .about("Create a thread.")
                .arg(
                    Arg::new("messages")
                        .long("messages")
                        .action(clap::ArgAction::Append)
                        .value_delimiter(',')
                        .help("A list of [messages](/docs/api-reference/messages) to start the thread with."),
                )
                .arg(
                    Arg::new("tool-resources")
                        .long("tool-resources"),
                )
                .arg(
                    Arg::new("metadata")
                        .long("metadata"),
                ),
        )
}

pub async fn run<O: CliOverrides>(ctx: &Context, o: &O, cmd_path: &[String], m: &ArgMatches) -> ExitCode {
    let parts: Vec<&str> = cmd_path.iter().map(String::as_str).collect();
    match parts.as_slice() {
        ["threads", "create"] => handle_threads_create(ctx, o, cmd_path, m).await,
        _ => {
            eprintln!("error: unknown command: {}", cmd_path.join(" "));
            ExitCode::FAILURE
        }
    }
}

async fn handle_threads_create<O: CliOverrides>(
    ctx: &Context,
    o: &O,
    cmd_path: &[String],
    m: &ArgMatches,
) -> ExitCode {
    let path = "/threads".to_string();
    let mut body = serde_json::Map::new();
    if let Some(vs) = m.get_many::<String>("messages") {
        body.insert("messages".to_string(), serde_json::Value::Array(vs.cloned().map(serde_json::Value::String).collect()));
    }
    if let Some(v) = m.get_one::<String>("tool-resources") {
        let value = serde_json::from_str::<serde_json::Value>(v)
            .unwrap_or_else(|_| serde_json::Value::String(v.clone()));
        body.insert("tool_resources".to_string(), value);
    }
    if let Some(v) = m.get_one::<String>("metadata") {
        let value = serde_json::from_str::<serde_json::Value>(v)
            .unwrap_or_else(|_| serde_json::Value::String(v.clone()));
        body.insert("metadata".to_string(), value);
    }
    let body_bytes = match serde_json::to_vec(&serde_json::Value::Object(body)) {
        Ok(bytes) => bytes,
        Err(err) => return o.print_error(cmd_path, &runtime::Error::Invalid(err.to_string())),
    };
    let req = runtime::Request {
        method: "POST",
        path,
        query: Vec::new(),
        headers: Vec::new(),
        body: Some(body_bytes),
    };
    runtime::run_request(ctx, o, cmd_path, req).await
}
