// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

public final class AdminOrganizationCertificateService {
  private final Transport transport;

  AdminOrganizationCertificateService(Transport transport) {
    this.transport = transport;
  }

  /** Modify a certificate. Note that only the name can be modified. */
  public Certificate update(String certificateId, AdminOrganizationCertificateUpdateParams params) {
    if (certificateId == null || certificateId.isEmpty()) {
      throw new IllegalArgumentException("missing required certificate_id parameter");
    }
    Transport.Request request = new Transport.Request("POST", "/organization/certificates/" + Transport.encodePath(certificateId));
    Map<String, Object> body = new LinkedHashMap<>();
    params.name().ifPresent(value -> body.put("name", value));
    request.body(body);
    return Certificate.fromJson(transport.execute(request));
  }
}
