# Code generated by opensdk. DO NOT EDIT.

from __future__ import annotations

from typing import Optional

from ._pagination import CursorPage
from ._transport import Transport
from .models import *  # noqa: F401,F403


class ConversationsResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport
        self.items = ItemsResource(transport)


class ItemsResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def list(self, conversation_id: str, *, limit: Optional[int] = None, order: Optional[ConversationsItemsListOrder] = None, after: Optional[str] = None, include: Optional[list[IncludeEnum]] = None) -> CursorPage[ConversationItem]:
        return CursorPage.from_response(ConversationItem, self._transport.request("GET", f"/conversations/{conversation_id}/items", query={"limit": limit, "order": order, "after": after, "include": include}))
