# Code generated by opensdk. DO NOT EDIT.

from __future__ import annotations

from typing import BinaryIO, Union

from ._transport import Transport, decode
from .models import *  # noqa: F401,F403


class AudioResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport
        self.voices = AudioVoicesResource(transport)


class AudioVoicesResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def create(self, *, name: str, audio_sample: Union[bytes, BinaryIO], consent: str) -> VoiceResource:
        return decode(VoiceResource, self._transport.request("POST", "/audio/voices", body={"name": name, "audio_sample": audio_sample, "consent": consent}, encoding="multipart"))
