// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

public final class AdminOrganizationRoleService {
  private final Transport transport;

  AdminOrganizationRoleService(Transport transport) {
    this.transport = transport;
  }

  /** Creates a custom role for the organization. */
  public Role create(AdminOrganizationRoleCreateParams params) {
    Transport.Request request = new Transport.Request("POST", "/organization/roles");
    Map<String, Object> body = new LinkedHashMap<>();
    body.put("role_name", params.roleName());
    body.put("permissions", params.permissions());
    params.description().ifPresent(value -> body.put("description", value));
    request.body(body);
    return Role.fromJson(transport.execute(request));
  }
}
