# Code generated by opensdk. DO NOT EDIT.

from __future__ import annotations

from ._transport import Transport, decode
from .models import *  # noqa: F401,F403


class ChatResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport
        self.completions = ChatCompletionsResource(transport)


class ChatCompletionsResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def update(self, completion_id: str, *, metadata: Metadata) -> CreateChatCompletionResponse:
        if not completion_id:
            raise ValueError(f"Expected a non-empty value for `completion_id` but received {completion_id!r}")
        return decode(CreateChatCompletionResponse, self._transport.request("POST", f"/chat/completions/{completion_id}", body={"metadata": metadata}))
