// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

public final class ContainerService {
  private final Transport transport;

  ContainerService(Transport transport) {
    this.transport = transport;
  }

  /** Delete a container. */
  public void delete(String containerId) {
    if (containerId == null || containerId.isEmpty()) {
      throw new IllegalArgumentException("missing required container_id parameter");
    }
    Transport.Request request = new Transport.Request("DELETE", "/containers/" + Transport.encodePath(containerId));
    transport.execute(request);
  }
}
