// === index.js ===
import { jsx, jsxs } from "react/jsx-runtime";
function StatusBadge({ label, variant, size = "medium", animated }) {
  return jsx("span", { className: `badge badge-${variant} badge-${size} ${animated ? "pulse" : ""}`, children: label });
}
StatusBadge.__xydUniform = JSON.parse('{"title":"StatusBadge","canonical":"","description":"","definitions":[{"title":"Props","properties":[{"name":"label","type":"string","description":"Current status label","meta":[{"name":"required","value":"true"}]},{"name":"variant","type":"$xor","description":"Visual variant","meta":[{"name":"required","value":"true"}],"properties":[{"name":"","type":"object","description":"","meta":[{"name":"required","value":"true"}]},{"name":"","type":"object","description":"","meta":[{"name":"required","value":"true"}]},{"name":"","type":"object","description":"","meta":[{"name":"required","value":"true"}]},{"name":"","type":"object","description":"","meta":[{"name":"required","value":"true"}]}]},{"name":"size","type":"$xor","description":"Size of the badge","meta":[],"properties":[{"name":"","type":"object","description":"","meta":[{"name":"required","value":"true"}]},{"name":"","type":"object","description":"","meta":[{"name":"required","value":"true"}]},{"name":"","type":"object","description":"","meta":[{"name":"required","value":"true"}]}]},{"name":"animated","type":"boolean","description":"Whether the badge should pulse","meta":[]}],"meta":[{"name":"type","value":"parameters"}]}],"examples":{"groups":[]}}');
function CardWrapper({ title, children, icon, footer, bordered }) {
  return jsxs("div", { className: `card ${bordered ? "bordered" : ""}`, children: [jsxs("div", { className: "card-header", children: [icon && jsx("span", { className: "card-icon", children: icon }), jsx("h3", { children: title })] }), jsx("div", { className: "card-body", children }), footer && jsx("div", { className: "card-footer", children: footer })] });
}
CardWrapper.__xydUniform = JSON.parse('{"title":"CardWrapper","canonical":"","description":"","definitions":[{"title":"Props","properties":[{"name":"title","type":"string","description":"Card title","meta":[{"name":"required","value":"true"}]},{"name":"children","type":"object","description":"Card content — React types that typia cannot resolve","meta":[],"properties":[{"name":"type","type":"string","description":"","meta":[{"name":"required","value":"true"}]},{"name":"props","type":"any","description":"","meta":[{"name":"required","value":"true"}]},{"name":"key","type":"string","description":"","meta":[{"name":"required","value":"true"}]}]},{"name":"icon","type":"object","description":"Optional icon element","meta":[],"properties":[{"name":"type","type":"string","description":"","meta":[{"name":"required","value":"true"}]},{"name":"props","type":"any","description":"","meta":[{"name":"required","value":"true"}]},{"name":"key","type":"string","description":"","meta":[{"name":"required","value":"true"}]}]},{"name":"footer","type":"object","description":"Optional footer element","meta":[],"properties":[{"name":"type","type":"string","description":"","meta":[{"name":"required","value":"true"}]},{"name":"props","type":"any","description":"","meta":[{"name":"required","value":"true"}]},{"name":"key","type":"string","description":"","meta":[{"name":"required","value":"true"}]}]},{"name":"bordered","type":"boolean","description":"Whether the card has a border","meta":[]}],"meta":[{"name":"type","value":"parameters"}]}],"examples":{"groups":[]}}');
export {
  CardWrapper,
  StatusBadge
};

