// Code generated by opensdk. DO NOT EDIT.

package openai

import (
	"context"
	"net/http"

	"github.com/example/openai/internal/requestconfig"
	"github.com/example/openai/option"
	"github.com/example/openai/packages/apijson"
)

// AdminService ...
type AdminService struct {
	Options []option.RequestOption
	Organization AdminOrganizationService
}

// NewAdminService constructs a service that shares the client's request options.
func NewAdminService(opts ...option.RequestOption) (r AdminService) {
	r = AdminService{}
	r.Options = opts
	r.Organization = NewAdminOrganizationService(opts...)
	return
}

// AdminOrganizationService ...
type AdminOrganizationService struct {
	Options []option.RequestOption
	Certificates AdminOrganizationCertificateService
}

// NewAdminOrganizationService constructs a service that shares the client's request options.
func NewAdminOrganizationService(opts ...option.RequestOption) (r AdminOrganizationService) {
	r = AdminOrganizationService{}
	r.Options = opts
	r.Certificates = NewAdminOrganizationCertificateService(opts...)
	return
}

// AdminOrganizationCertificateService ...
type AdminOrganizationCertificateService struct {
	Options []option.RequestOption
	Activate AdminOrganizationCertificateActivateService
}

// NewAdminOrganizationCertificateService constructs a service that shares the client's request options.
func NewAdminOrganizationCertificateService(opts ...option.RequestOption) (r AdminOrganizationCertificateService) {
	r = AdminOrganizationCertificateService{}
	r.Options = opts
	r.Activate = NewAdminOrganizationCertificateActivateService(opts...)
	return
}

// AdminOrganizationCertificateActivateService ...
type AdminOrganizationCertificateActivateService struct {
	Options []option.RequestOption
}

// NewAdminOrganizationCertificateActivateService constructs a service that shares the client's request options.
func NewAdminOrganizationCertificateActivateService(opts ...option.RequestOption) (r AdminOrganizationCertificateActivateService) {
	r = AdminOrganizationCertificateActivateService{}
	r.Options = opts
	return
}

// Activate certificates at the organization level.
//
// You can atomically and idempotently activate up to 10 certificates at a time.
func (r *AdminOrganizationCertificateActivateService) New(ctx context.Context, body AdminOrganizationCertificateActivateNewParams, opts ...option.RequestOption) (res *OrganizationCertificateActivationResponse, err error) {
	opts = append(r.Options[:], opts...)
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodPost, "organization/certificates/activate", body, opts...)
	if err != nil {
		return
	}
	res = &OrganizationCertificateActivationResponse{}
	err = cfg.Execute(res)
	return
}

type AdminOrganizationCertificateActivateNewParams struct {
	CertificateIds []string `json:"certificate_ids,required"`
}

func (r AdminOrganizationCertificateActivateNewParams) MarshalJSON() ([]byte, error) {
	return apijson.MarshalRoot(r)
}
