// Code generated by opensdk. DO NOT EDIT.

use std::sync::Arc;

use crate::error::Error;
use crate::models::*;
use crate::transport::{Page, Transport};

pub struct Responses {
    transport: Arc<Transport>,
}

impl Responses {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        Responses { transport }
    }

    /// Cancels a model response with the given ID. Only responses created with
    /// the `background` parameter set to `true` can be cancelled.
    /// [Learn more](/docs/guides/background).
    pub async fn cancel(&self, response_id: &str) -> Result<Response, Error> {
        if response_id.is_empty() {
            return Err(Error::InvalidArgument("response_id".to_string()));
        }

        let req = self.transport.request(reqwest::Method::POST, format!("/responses/{}/cancel", response_id));
        req.send().await
    }
}
