// Code generated by opensdk. DO NOT EDIT.

#![allow(dead_code, unused_imports)]
mod common;

use common::build_client;
use extensions_demo::*;

#[tokio::test]
async fn test_method_browse() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.catalog().browse().await?;
    Ok(())
}
