// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

public final class BatchService {
  private final Transport transport;

  BatchService(Transport transport) {
    this.transport = transport;
  }

  /** Creates and executes a batch from an uploaded file of requests */
  public Batch create(BatchCreateParams params) {
    Transport.Request request = new Transport.Request("POST", "/batches");
    Map<String, Object> body = new LinkedHashMap<>();
    body.put("input_file_id", params.inputFileId());
    body.put("endpoint", params.endpoint());
    body.put("completion_window", "24h");
    params.metadata().ifPresent(value -> body.put("metadata", value));
    params.outputExpiresAfter().ifPresent(value -> body.put("output_expires_after", value));
    request.body(body);
    return Batch.fromJson(transport.execute(request));
  }
}
