# Code generated by opensdk. DO NOT EDIT.

module Openai
  module Resources
    class Beta
      attr_reader :chat_kit

      # @api private
      def initialize(transport)
        @transport = transport
        @chat_kit = BetaChatKit.new(transport)
      end
    end

    class BetaChatKit
      attr_reader :threads

      # @api private
      def initialize(transport)
        @transport = transport
        @threads = BetaChatKitThreads.new(transport)
      end
    end

    class BetaChatKitThreads
      # @api private
      def initialize(transport)
        @transport = transport
      end

      # Retrieve a ChatKit thread by its identifier.
      #
      # @param thread_id [String]
      # @return [Models::ThreadResource]
      def retrieve(thread_id)
        raise ArgumentError, "Expected a non-empty value for `thread_id`" if thread_id.nil? || thread_id.to_s.empty?

        @transport.request(
          method: :get,
          path: "/chatkit/threads/#{thread_id}"
        )
      end
    end
  end
end
