// Code generated by opensdk. DO NOT EDIT.

import { APIResource } from '../core/resource';
import type { APIClient, RequestOptions } from '../core/request';
import { CursorPage } from '../core/pagination';
import type { AudioResponseFormat, AudioTranscriptionsCreateResponse, AudioTranslationsCreateResponse, CreateSpeechRequestModel, CreateSpeechRequestResponseFormat, CreateSpeechRequestStreamFormat, CreateTranscriptionRequestChunkingStrategy, CreateTranscriptionRequestModel, CreateTranscriptionRequestTimestampGranularitiesItem, CreateTranslationRequestModel, CreateTranslationRequestResponseFormat, TranscriptionInclude, VoiceConsentDeletedResource, VoiceConsentResource, VoiceIdsOrCustomVoice, VoiceResource } from '../models';

export class Audio extends APIResource {
  readonly speech: AudioSpeech;

  readonly transcriptions: AudioTranscriptions;

  readonly translations: AudioTranslations;

  readonly voiceConsents: AudioVoiceConsents;

  readonly voices: AudioVoices;

  constructor(client: APIClient) {
    super(client);
    this.speech = new AudioSpeech(client);
    this.transcriptions = new AudioTranscriptions(client);
    this.translations = new AudioTranslations(client);
    this.voiceConsents = new AudioVoiceConsents(client);
    this.voices = new AudioVoices(client);
  }
}

export class AudioSpeech extends APIResource {
  /**
   * Generates audio from the input text.
   *
   * Returns the audio file content, or a stream of audio events.
   */
  create(body: AudioSpeechCreateParams, options?: RequestOptions): Promise<Response> {
    return this._client.request<Response>({ method: "POST", path: "/audio/speech", body, headers: { Accept: "application/octet-stream" }, raw: true }, options);
  }
}

export class AudioTranscriptions extends APIResource {
  /**
   * Transcribes audio into the input language.
   *
   * Returns a transcription object in `json`, `diarized_json`, or `verbose_json`
   * format, or a stream of transcript events.
   */
  create(body: AudioTranscriptionCreateParams, options?: RequestOptions): Promise<AudioTranscriptionsCreateResponse> {
    return this._client.request<AudioTranscriptionsCreateResponse>({ method: "POST", path: "/audio/transcriptions", body, encoding: "multipart" }, options);
  }
}

export class AudioTranslations extends APIResource {
  /** Translates audio into English. */
  create(body: AudioTranslationCreateParams, options?: RequestOptions): Promise<AudioTranslationsCreateResponse> {
    return this._client.request<AudioTranslationsCreateResponse>({ method: "POST", path: "/audio/translations", body, encoding: "multipart" }, options);
  }
}

export class AudioVoiceConsents extends APIResource {
  /**
   * Upload a consent recording that authorizes creation of a custom voice.
   *
   * See the [custom voices guide](/docs/guides/text-to-speech#custom-voices) for requirements and best practices. Custom voices are limited to eligible customers.
   */
  create(body: AudioVoiceConsentCreateParams, options?: RequestOptions): Promise<VoiceConsentResource> {
    return this._client.request<VoiceConsentResource>({ method: "POST", path: "/audio/voice_consents", body, encoding: "multipart" }, options);
  }

  /**
   * Delete a consent recording that was uploaded for creating custom voices.
   *
   * See the [custom voices guide](/docs/guides/text-to-speech#custom-voices). Custom voices are limited to eligible customers.
   */
  delete(consentId: string, options?: RequestOptions): Promise<VoiceConsentDeletedResource> {
    if (!consentId) {
      throw new Error("missing required consent_id parameter");
    }
    return this._client.request<VoiceConsentDeletedResource>({ method: "DELETE", path: `/audio/voice_consents/${consentId}` }, options);
  }

  /**
   * List consent recordings available to your organization for creating custom voices.
   *
   * See the [custom voices guide](/docs/guides/text-to-speech#custom-voices). Custom voices are limited to eligible customers.
   */
  list(query?: AudioVoiceConsentListParams, options?: RequestOptions): Promise<CursorPage<VoiceConsentResource>> {
    return this._client
      .request<unknown>({ method: "GET", path: "/audio/voice_consents", query }, options)
      .then((raw) => CursorPage.fromResponse<VoiceConsentResource>(raw));
  }

  /**
   * Retrieve consent recording metadata used for creating custom voices.
   *
   * See the [custom voices guide](/docs/guides/text-to-speech#custom-voices). Custom voices are limited to eligible customers.
   */
  retrieve(consentId: string, options?: RequestOptions): Promise<VoiceConsentResource> {
    if (!consentId) {
      throw new Error("missing required consent_id parameter");
    }
    return this._client.request<VoiceConsentResource>({ method: "GET", path: `/audio/voice_consents/${consentId}` }, options);
  }

  /**
   * Update consent recording metadata used for creating custom voices. This endpoint updates metadata only and does not replace the underlying audio.
   *
   * See the [custom voices guide](/docs/guides/text-to-speech#custom-voices). Custom voices are limited to eligible customers.
   */
  update(consentId: string, body: AudioVoiceConsentUpdateParams, options?: RequestOptions): Promise<VoiceConsentResource> {
    if (!consentId) {
      throw new Error("missing required consent_id parameter");
    }
    return this._client.request<VoiceConsentResource>({ method: "POST", path: `/audio/voice_consents/${consentId}`, body }, options);
  }
}

export class AudioVoices extends APIResource {
  /**
   * Create a custom voice you can use for audio output (for example, in Text-to-Speech and the Realtime API). This requires an audio sample and a previously uploaded consent recording.
   *
   * See the [custom voices guide](/docs/guides/text-to-speech#custom-voices) for requirements and best practices. Custom voices are limited to eligible customers.
   */
  create(body: AudioVoiceCreateParams, options?: RequestOptions): Promise<VoiceResource> {
    return this._client.request<VoiceResource>({ method: "POST", path: "/audio/voices", body, encoding: "multipart" }, options);
  }
}

export interface AudioSpeechCreateParams {
  model: CreateSpeechRequestModel;
  input: string;
  instructions?: string;
  voice: VoiceIdsOrCustomVoice;
  response_format?: CreateSpeechRequestResponseFormat;
  speed?: number;
  stream_format?: CreateSpeechRequestStreamFormat;
}

export interface AudioTranscriptionCreateParams {
  file: Uint8Array | Blob;
  model: CreateTranscriptionRequestModel;
  language?: string;
  prompt?: string;
  response_format?: AudioResponseFormat;
  temperature?: number;
  include?: TranscriptionInclude[];
  timestamp_granularities?: CreateTranscriptionRequestTimestampGranularitiesItem[];
  stream?: boolean | null;
  chunking_strategy?: CreateTranscriptionRequestChunkingStrategy | null;
  known_speaker_names?: string[];
  known_speaker_references?: string[];
}

export interface AudioTranslationCreateParams {
  file: Uint8Array | Blob;
  model: CreateTranslationRequestModel;
  prompt?: string;
  response_format?: CreateTranslationRequestResponseFormat;
  temperature?: number;
}

export interface AudioVoiceConsentCreateParams {
  name: string;
  recording: Uint8Array | Blob;
  language: string;
}

export interface AudioVoiceConsentListParams {
  after?: string;
  limit?: number;
}

export interface AudioVoiceConsentUpdateParams {
  name: string;
}

export interface AudioVoiceCreateParams {
  name: string;
  audio_sample: Uint8Array | Blob;
  consent: string;
}
