// Code generated by opensdk. DO NOT EDIT.

import { APIResource } from '../core/resource';
import type { APIClient, RequestOptions } from '../core/request';
import { CursorPage } from '../core/pagination';
import type { DeletedVideoResource, ImageRefParam2, OrderEnum, VideoCharacterResource, VideoContentVariant, VideoModel, VideoReferenceInputParam, VideoResource, VideoSeconds, VideoSize } from '../models';

export class Videos extends APIResource {
  readonly characters: VideosCharacters;

  readonly edits: VideosEdits;

  readonly extensions: VideosExtensions;

  constructor(client: APIClient) {
    super(client);
    this.characters = new VideosCharacters(client);
    this.edits = new VideosEdits(client);
    this.extensions = new VideosExtensions(client);
  }

  /** Create a new video generation job from a prompt and optional reference assets. */
  create(body?: VideoCreateParams, options?: RequestOptions): Promise<VideoResource> {
    return this._client.request<VideoResource>({ method: "POST", path: "/videos", body }, options);
  }

  /** Permanently delete a completed or failed video and its stored assets. */
  delete(videoId: string, options?: RequestOptions): Promise<DeletedVideoResource> {
    if (!videoId) {
      throw new Error("missing required video_id parameter");
    }
    return this._client.request<DeletedVideoResource>({ method: "DELETE", path: `/videos/${videoId}` }, options);
  }

  /**
   * Download the generated video bytes or a derived preview asset.
   *
   * Streams the rendered video content for the specified video job.
   */
  downloadContent(videoId: string, query?: VideoDownloadContentParams, options?: RequestOptions): Promise<string> {
    if (!videoId) {
      throw new Error("missing required video_id parameter");
    }
    return this._client.request<string>({ method: "GET", path: `/videos/${videoId}/content`, query }, options);
  }

  /** List recently generated videos for the current project. */
  list(query?: VideoListParams, options?: RequestOptions): Promise<CursorPage<VideoResource>> {
    return this._client
      .request<unknown>({ method: "GET", path: "/videos", query }, options)
      .then((raw) => CursorPage.fromResponse<VideoResource>(raw));
  }

  /** Create a remix of a completed video using a refreshed prompt. */
  remix(videoId: string, body?: VideoRemixParams, options?: RequestOptions): Promise<VideoResource> {
    if (!videoId) {
      throw new Error("missing required video_id parameter");
    }
    return this._client.request<VideoResource>({ method: "POST", path: `/videos/${videoId}/remix`, body }, options);
  }

  /** Fetch the latest metadata for a generated video. */
  retrieve(videoId: string, options?: RequestOptions): Promise<VideoResource> {
    if (!videoId) {
      throw new Error("missing required video_id parameter");
    }
    return this._client.request<VideoResource>({ method: "GET", path: `/videos/${videoId}` }, options);
  }
}

export class VideosCharacters extends APIResource {
  /** Create a character from an uploaded video. */
  create(body?: VideoCharacterCreateParams, options?: RequestOptions): Promise<VideoCharacterResource> {
    return this._client.request<VideoCharacterResource>({ method: "POST", path: "/videos/characters", body, encoding: "multipart" }, options);
  }

  /** Fetch a character. */
  retrieve(characterId: string, options?: RequestOptions): Promise<VideoCharacterResource> {
    if (!characterId) {
      throw new Error("missing required character_id parameter");
    }
    return this._client.request<VideoCharacterResource>({ method: "GET", path: `/videos/characters/${characterId}` }, options);
  }
}

export class VideosEdits extends APIResource {
  /** Create a new video generation job by editing a source video or existing generated video. */
  create(body?: VideoEditCreateParams, options?: RequestOptions): Promise<VideoResource> {
    return this._client.request<VideoResource>({ method: "POST", path: "/videos/edits", body }, options);
  }
}

export class VideosExtensions extends APIResource {
  /** Create an extension of a completed video. */
  create(body?: VideoExtensionCreateParams, options?: RequestOptions): Promise<VideoResource> {
    return this._client.request<VideoResource>({ method: "POST", path: "/videos/extensions", body }, options);
  }
}

export interface VideoCreateParams {
  model?: VideoModel;
  prompt: string;
  input_reference?: ImageRefParam2;
  seconds?: VideoSeconds;
  size?: VideoSize;
}

export interface VideoDownloadContentParams {
  variant?: VideoContentVariant;
}

export interface VideoListParams {
  limit?: number;
  order?: OrderEnum;
  after?: string;
}

export interface VideoRemixParams {
  prompt: string;
}

export interface VideoCharacterCreateParams {
  video: Uint8Array | Blob;
  name: string;
}

export interface VideoEditCreateParams {
  video: VideoReferenceInputParam;
  prompt: string;
}

export interface VideoExtensionCreateParams {
  video: VideoReferenceInputParam;
  prompt: string;
  seconds: VideoSeconds;
}
