# Code generated by opensdk. DO NOT EDIT.

from __future__ import annotations

from ._transport import Transport, decode
from .models import *  # noqa: F401,F403


class ProjectsResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport
        self.groups = GroupsResource(transport)


class GroupsResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport
        self.roles = RolesResource(transport)


class RolesResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def delete(self, project_id: str, group_id: str, role_id: str) -> DeletedRoleAssignmentResource:
        return decode(DeletedRoleAssignmentResource, self._transport.request("DELETE", f"/projects/{project_id}/groups/{group_id}/roles/{role_id}"))
