# Code generated by opensdk. DO NOT EDIT.

module Openai
  module Resources
    class Batches
      # @api private
      def initialize(transport)
        @transport = transport
      end

      # List your organization's batches.
      #
      # @param after [String]
      # @param limit [Integer]
      # @return [Page<Models::Batch>]
      def list(after: nil, limit: nil)
        response = @transport.request(
          method: :get,
          path: "/batches",
          query: { "after" => after, "limit" => limit }
        )
        Openai::Page.new(data: (response || {})[:data], has_more: (response || {})[:has_more])
      end
    end
  end
end
