//! The vendored Rust runtime + user scaffolds — port of runtime.ts. The static
//! blobs live in `blobs.rs` (byte-exact); config.rs + Cargo.toml are spec-
//! interpolated here.

use serde_json::Value;

use crate::blobs;
use crate::naming::screaming_snake_case;
use crate::rslit::json_str;

const HEADER: &str = "// Code generated by opencli2rust. DO NOT EDIT.";

pub fn http_rs() -> String {
    blobs::HTTP_RS.to_string()
}
/// `src/gen/runtime/mod.rs` — additionally declares/re-exports `actions` when the
/// doc has non-API runnable leaves. Kept byte-identical to the base blob otherwise.
pub fn runtime_mod_rs(has_actions: bool) -> String {
    if !has_actions {
        return blobs::RUNTIME_MOD_RS.to_string();
    }
    blobs::RUNTIME_MOD_RS
        .replace("pub mod config;\n", "mod actions;\npub mod config;\n")
        .replace(
            "pub use custom::CustomCommands;\n",
            "pub use actions::Actions;\npub use custom::CustomCommands;\n",
        )
}
pub fn overrides_rs() -> String {
    blobs::OVERRIDES_RS.to_string()
}
pub fn custom_registry_rs() -> String {
    blobs::CUSTOM_REGISTRY_RS.to_string()
}
pub fn actions_rs() -> String {
    blobs::ACTIONS_RS.to_string()
}
/// `src/custom/mod.rs` scaffold — adds the `actions()` seam (fn + doc + import)
/// when the doc has non-API runnable leaves. Byte-identical to the base otherwise.
pub fn custom_scaffold_rs(has_actions: bool) -> String {
    if !has_actions {
        return blobs::CUSTOM_SCAFFOLD_RS.to_string();
    }
    blobs::CUSTOM_SCAFFOLD_RS
        .replace(
            "//!    registered on an existing path takes over that command's behavior.\n",
            "//!    registered on an existing path takes over that command's behavior.\n//!  * [`actions`] — bind behavior to the generated non-API leaves (dev/build/…).\n",
        )
        .replace(
            "use crate::gen::runtime::{CliOverrides, CustomCommands};",
            "use crate::gen::runtime::{Actions, CliOverrides, CustomCommands};",
        )
        .replace(
            "\n\npub fn overrides() -> Custom {",
            "\n\n/// Bind behavior to the generated non-API leaves. Called by the generated `main`.\npub fn actions(actions: &mut Actions) {\n    let _ = actions;\n    // Example — implement the `dev` leaf:\n    //\n    // actions.on(&[\"dev\"], |_ctx, _m| async move {\n    //     println!(\"dev\");\n    //     Ok(())\n    // });\n}\n\npub fn overrides() -> Custom {",
        )
}
pub fn gen_mod_rs() -> String {
    blobs::GEN_MOD_RS.to_string()
}
pub fn main_rs(has_actions: bool) -> String {
    if has_actions {
        blobs::MAIN_LOCAL_RS.to_string()
    } else {
        blobs::MAIN_RS.to_string()
    }
}

/// One environment-based auth attach block, or None for an unrecognized kind.
fn auth_block(scheme: &Value) -> Option<String> {
    let env = scheme
        .get("envVar")
        .and_then(|v| v.as_str())
        .unwrap_or("API_KEY");
    let name = scheme.get("name").and_then(|v| v.as_str()).unwrap_or("");
    match scheme.get("kind").and_then(|k| k.as_str()) {
        Some("bearer") => Some(format!(
            "    if let Ok(v) = std::env::var({}) {{\n        if !v.is_empty() {{\n            rb = rb.bearer_auth(v);\n        }}\n    }}",
            json_str(env)
        )),
        Some("apiKey-header") => Some(format!(
            "    if let Ok(v) = std::env::var({}) {{\n        if !v.is_empty() {{\n            rb = rb.header({}, v);\n        }}\n    }}",
            json_str(env),
            json_str(name)
        )),
        Some("apiKey-query") => Some(format!(
            "    if let Ok(v) = std::env::var({}) {{\n        if !v.is_empty() {{\n            rb = rb.query(&[({}, v.as_str())]);\n        }}\n    }}",
            json_str(env),
            json_str(name)
        )),
        Some("apiKey-cookie") => Some(format!(
            "    if let Ok(v) = std::env::var({}) {{\n        if !v.is_empty() {{\n            rb = rb.header(\"Cookie\", format!(\"{{}}={{}}\", {}, v));\n        }}\n    }}",
            json_str(env),
            json_str(name)
        )),
        Some("basic") => Some(format!(
            "    let user = std::env::var({}).unwrap_or_default();\n    let pass = std::env::var({}).unwrap_or_default();\n    if !user.is_empty() || !pass.is_empty() {{\n        rb = rb.basic_auth(user, Some(pass));\n    }}",
            json_str(&format!("{env}_USERNAME")),
            json_str(&format!("{env}_PASSWORD"))
        )),
        _ => None,
    }
}

/// `src/gen/runtime/config.rs` — base URL + auth derived from the root x-openapi.
pub fn config_rs(spec: &Value, bin_name: &str, base_url: &str) -> String {
    let prefix = screaming_snake_case(bin_name);
    let empty: Vec<Value> = Vec::new();
    let security = spec
        .get("x-openapi")
        .and_then(|x| x.get("security"))
        .and_then(|s| s.as_array())
        .unwrap_or(&empty);
    let blocks: Vec<String> = security.iter().filter_map(auth_block).collect();

    let apply_auth = if !blocks.is_empty() {
        format!(
            "/// Attach credentials read from the environment to the request.\npub fn apply_auth(mut rb: reqwest::RequestBuilder) -> reqwest::RequestBuilder {{\n{}\n    rb\n}}",
            blocks.join("\n")
        )
    } else {
        "/// Attach credentials read from the environment to the request.\npub fn apply_auth(rb: reqwest::RequestBuilder) -> reqwest::RequestBuilder {\n    rb\n}".to_string()
    };

    format!(
        "{HEADER}\n\n//! Spec-derived configuration: the API base URL and environment-based auth.\n\nconst DEFAULT_BASE_URL: &str = {};\n\n/// The API base URL, overridable via `{prefix}_BASE_URL`.\npub fn base_url() -> String {{\n    match std::env::var({}) {{\n        Ok(v) if !v.is_empty() => v,\n        _ => DEFAULT_BASE_URL.to_string(),\n    }}\n}}\n\n{apply_auth}\n",
        json_str(base_url),
        json_str(&format!("{prefix}_BASE_URL"))
    )
}

/// `Cargo.toml` (skipIfExists) — the crate manifest.
pub fn cargo_toml(spec: &Value, crate_name: &str, bin_name: &str, edition: &str) -> String {
    let version = spec
        .get("info")
        .and_then(|i| i.get("version"))
        .and_then(|v| v.as_str())
        .unwrap_or("0.1.0");
    format!(
        "# Generated once by opencli2rust — yours to edit; regeneration never overwrites it.\n\n[package]\nname = {}\nversion = {}\nedition = {}\n\n[dependencies]\nclap = {{ version = \"4\", features = [\"string\"] }}\npercent-encoding = \"2\"\nreqwest = {{ version = \"0.12\", default-features = false, features = [\"json\", \"rustls-tls\"] }}\nserde_json = \"1\"\ntokio = {{ version = \"1\", features = [\"macros\", \"rt-multi-thread\"] }}\n\n[[bin]]\nname = {}\npath = \"src/main.rs\"\n",
        json_str(crate_name),
        json_str(version),
        json_str(edition),
        json_str(bin_name)
    )
}
