// Code generated by opensdk. DO NOT EDIT.

import { APIResource } from '../core/resource';
import type { APIClient, RequestOptions } from '../core/request';
import type { SystemHealthCheckResponse } from '../models';

export class System extends APIResource {
  readonly health: SystemHealth;

  constructor(client: APIClient) {
    super(client);
    this.health = new SystemHealth(client);
  }
}

export class SystemHealth extends APIResource {
  /** Health check */
  check(options?: RequestOptions): Promise<SystemHealthCheckResponse> {
    return this._client.request<SystemHealthCheckResponse>({ method: "GET", path: "/misc/ping" }, options);
  }
}
