// Code generated by opensdk. DO NOT EDIT.

import { APIResource } from '../core/resource';
import type { RequestOptions } from '../core/request';
import type { Thing } from '../models';

export class Things extends APIResource {
  /** Retrieve a thing */
  fetch(thingId: string, options?: RequestOptions): Promise<Thing> {
    if (!thingId) {
      throw new Error("missing required thing_id parameter");
    }
    return this._client.request<Thing>({ method: "GET", path: `/things/${thingId}` }, options);
  }
}
