// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

public final class UploadService {
  private final Transport transport;

  UploadService(Transport transport) {
    this.transport = transport;
  }

  /**
   * Cancels the Upload. No Parts may be added after an Upload is cancelled.
   * 
   * Returns the Upload object with status `cancelled`.
   */
  public Upload cancel(String uploadId) {
    if (uploadId == null || uploadId.isEmpty()) {
      throw new IllegalArgumentException("missing required upload_id parameter");
    }
    Transport.Request request = new Transport.Request("POST", "/uploads/" + Transport.encodePath(uploadId) + "/cancel");
    return Upload.fromJson(transport.execute(request));
  }
}
