// Code generated by opensdk. DO NOT EDIT.

#![allow(dead_code, unused_imports)]
mod common;

use common::build_client;
use openai::*;

#[tokio::test]
async fn test_method_content() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.files().content("file_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_content() {
    let client = build_client();
    let error = client.files().content("").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_create() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.files().create(FilesCreateParams { file: Some(b"Example data".to_vec()), purpose: Some(CreateFileRequestPurpose::Assistants), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_create_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.files().create(FilesCreateParams { file: Some(b"Example data".to_vec()), purpose: Some(CreateFileRequestPurpose::Assistants), expires_after: Some(FileExpirationAfter { anchor: Some("created_at".to_string()), seconds: Some(0), ..Default::default() }), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_delete() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.files().delete("file_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_delete() {
    let client = build_client();
    let error = client.files().delete("").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.files().list(FilesListParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.files().list(FilesListParams { purpose: Some("purpose".to_string()), limit: Some(0), order: Some(FilesListOrder::Asc), after: Some("after".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_retrieve() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.files().retrieve("file_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_retrieve() {
    let client = build_client();
    let error = client.files().retrieve("").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}
