// Code generated by opensdk. DO NOT EDIT.

package openai_test

import (
	"context"
	"errors"
	"os"
	"strings"
	"testing"

	"github.com/example/openai"
	"github.com/example/openai/internal/requestconfig"
	"github.com/example/openai/internal/testutil"
	"github.com/example/openai/option"
	"github.com/example/openai/packages/param"
)

func TestVectorStoreNewWithOptionalParams(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.New(
		context.TODO(),
		openai.VectorStoreNewParams{
			FileIds: []string{"x"},
			Name: param.NewOpt[string]("x"),
			Description: param.NewOpt[string]("x"),
			ExpiresAfter: openai.VectorStoreExpirationAfter{Anchor: "last_active_at", Days: 0},
			ChunkingStrategy: openai.AutoChunkingStrategyRequestParam{Type: "auto"},
			Metadata: map[string]string{"key": "x"},
		},
	)
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestVectorStoreDelete(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.Delete(context.TODO(), "vector_store_id")
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestVectorStoreDeletePathParams(t *testing.T) {
	client := openai.NewClient(
		option.WithBaseURL("http://localhost:4010"),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.Delete(context.TODO(), "")
	if err == nil || !strings.Contains(err.Error(), "missing required") {
		t.Fatal("expected a missing required path param error")
	}
}

func TestVectorStoreListWithOptionalParams(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.List(
		context.TODO(),
		openai.VectorStoreListParams{
			Limit: param.NewOpt[int64](0),
			Order: param.NewOpt[openai.VectorStoresListOrder](openai.VectorStoresListOrderAsc),
			After: param.NewOpt[string]("after"),
			Before: param.NewOpt[string]("before"),
		},
	)
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestVectorStoreGet(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.Get(context.TODO(), "vector_store_id")
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestVectorStoreGetPathParams(t *testing.T) {
	client := openai.NewClient(
		option.WithBaseURL("http://localhost:4010"),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.Get(context.TODO(), "")
	if err == nil || !strings.Contains(err.Error(), "missing required") {
		t.Fatal("expected a missing required path param error")
	}
}

func TestVectorStoreSearchWithOptionalParams(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.Search(
		context.TODO(),
		"vector_store_id",
		openai.VectorStoreSearchParams{
			Query: "x",
			RewriteQuery: param.NewOpt[bool](true),
			MaxNumResults: param.NewOpt[int64](0),
			Filters: openai.ComparisonFilter{Type: openai.ComparisonFilterTypeEq, Key: "x", Value: "x"},
			RankingOptions: openai.VectorStoreSearchRequestRankingOptions{Ranker: openai.VectorStoreSearchRequestRankingOptionsRankerNone, ScoreThreshold: 0},
		},
	)
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestVectorStoreSearchPathParams(t *testing.T) {
	client := openai.NewClient(
		option.WithBaseURL("http://localhost:4010"),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.Search(
		context.TODO(),
		"",
		openai.VectorStoreSearchParams{
			Query: "x",
		},
	)
	if err == nil || !strings.Contains(err.Error(), "missing required") {
		t.Fatal("expected a missing required path param error")
	}
}

func TestVectorStoreUpdateWithOptionalParams(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.Update(
		context.TODO(),
		"vector_store_id",
		openai.VectorStoreUpdateParams{
			Name: param.NewOpt[string]("x"),
			ExpiresAfter: openai.VectorStoreExpirationAfter{Anchor: "last_active_at", Days: 0},
			Metadata: map[string]string{"key": "x"},
		},
	)
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestVectorStoreUpdatePathParams(t *testing.T) {
	client := openai.NewClient(
		option.WithBaseURL("http://localhost:4010"),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.Update(context.TODO(), "", openai.VectorStoreUpdateParams{})
	if err == nil || !strings.Contains(err.Error(), "missing required") {
		t.Fatal("expected a missing required path param error")
	}
}

func TestVectorStoreFileBatchCancel(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.FileBatches.Cancel(context.TODO(), "vector_store_id", "batch_id")
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestVectorStoreFileBatchCancelPathParams(t *testing.T) {
	client := openai.NewClient(
		option.WithBaseURL("http://localhost:4010"),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.FileBatches.Cancel(context.TODO(), "", "batch_id")
	if err == nil || !strings.Contains(err.Error(), "missing required") {
		t.Fatal("expected a missing required path param error")
	}
}

func TestVectorStoreFileBatchNew(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.FileBatches.New(context.TODO(), "vector_store_id", openai.VectorStoreFileBatchNewParams{})
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestVectorStoreFileBatchNewPathParams(t *testing.T) {
	client := openai.NewClient(
		option.WithBaseURL("http://localhost:4010"),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.FileBatches.New(context.TODO(), "", openai.VectorStoreFileBatchNewParams{})
	if err == nil || !strings.Contains(err.Error(), "missing required") {
		t.Fatal("expected a missing required path param error")
	}
}

func TestVectorStoreFileBatchListFilesWithOptionalParams(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.FileBatches.ListFiles(
		context.TODO(),
		"vector_store_id",
		"batch_id",
		openai.VectorStoreFileBatchListFilesParams{
			Limit: param.NewOpt[int64](0),
			Order: param.NewOpt[openai.VectorStoresFileBatchesListFilesOrder](openai.VectorStoresFileBatchesListFilesOrderAsc),
			After: param.NewOpt[string]("after"),
			Before: param.NewOpt[string]("before"),
			Filter: param.NewOpt[openai.VectorStoresFileBatchesListFilesFilter](openai.VectorStoresFileBatchesListFilesFilterInProgress),
		},
	)
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestVectorStoreFileBatchListFilesPathParams(t *testing.T) {
	client := openai.NewClient(
		option.WithBaseURL("http://localhost:4010"),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.FileBatches.ListFiles(context.TODO(), "", "batch_id", openai.VectorStoreFileBatchListFilesParams{})
	if err == nil || !strings.Contains(err.Error(), "missing required") {
		t.Fatal("expected a missing required path param error")
	}
}

func TestVectorStoreFileBatchGet(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.FileBatches.Get(context.TODO(), "vector_store_id", "batch_id")
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestVectorStoreFileBatchGetPathParams(t *testing.T) {
	client := openai.NewClient(
		option.WithBaseURL("http://localhost:4010"),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.FileBatches.Get(context.TODO(), "", "batch_id")
	if err == nil || !strings.Contains(err.Error(), "missing required") {
		t.Fatal("expected a missing required path param error")
	}
}

func TestVectorStoreFileContent(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.Files.Content(context.TODO(), "vector_store_id", "file_id")
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestVectorStoreFileContentPathParams(t *testing.T) {
	client := openai.NewClient(
		option.WithBaseURL("http://localhost:4010"),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.Files.Content(context.TODO(), "", "file_id")
	if err == nil || !strings.Contains(err.Error(), "missing required") {
		t.Fatal("expected a missing required path param error")
	}
}

func TestVectorStoreFileNewWithOptionalParams(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.Files.New(
		context.TODO(),
		"vector_store_id",
		openai.VectorStoreFileNewParams{
			FileID: "x",
			ChunkingStrategy: openai.AutoChunkingStrategyRequestParam{Type: "auto"},
			Attributes: map[string]openai.VectorStoreFileAttributesValue{"key": "x"},
		},
	)
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestVectorStoreFileNewPathParams(t *testing.T) {
	client := openai.NewClient(
		option.WithBaseURL("http://localhost:4010"),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.Files.New(
		context.TODO(),
		"",
		openai.VectorStoreFileNewParams{
			FileID: "x",
		},
	)
	if err == nil || !strings.Contains(err.Error(), "missing required") {
		t.Fatal("expected a missing required path param error")
	}
}

func TestVectorStoreFileDelete(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.Files.Delete(context.TODO(), "vector_store_id", "file_id")
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestVectorStoreFileDeletePathParams(t *testing.T) {
	client := openai.NewClient(
		option.WithBaseURL("http://localhost:4010"),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.Files.Delete(context.TODO(), "", "file_id")
	if err == nil || !strings.Contains(err.Error(), "missing required") {
		t.Fatal("expected a missing required path param error")
	}
}

func TestVectorStoreFileListWithOptionalParams(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.Files.List(
		context.TODO(),
		"vector_store_id",
		openai.VectorStoreFileListParams{
			Limit: param.NewOpt[int64](0),
			Order: param.NewOpt[openai.VectorStoresFilesListOrder](openai.VectorStoresFilesListOrderAsc),
			After: param.NewOpt[string]("after"),
			Before: param.NewOpt[string]("before"),
			Filter: param.NewOpt[openai.VectorStoresFilesListFilter](openai.VectorStoresFilesListFilterInProgress),
		},
	)
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestVectorStoreFileListPathParams(t *testing.T) {
	client := openai.NewClient(
		option.WithBaseURL("http://localhost:4010"),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.Files.List(context.TODO(), "", openai.VectorStoreFileListParams{})
	if err == nil || !strings.Contains(err.Error(), "missing required") {
		t.Fatal("expected a missing required path param error")
	}
}

func TestVectorStoreFileGet(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.Files.Get(context.TODO(), "vector_store_id", "file_id")
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestVectorStoreFileGetPathParams(t *testing.T) {
	client := openai.NewClient(
		option.WithBaseURL("http://localhost:4010"),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.Files.Get(context.TODO(), "", "file_id")
	if err == nil || !strings.Contains(err.Error(), "missing required") {
		t.Fatal("expected a missing required path param error")
	}
}

func TestVectorStoreFileUpdate(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.Files.Update(
		context.TODO(),
		"vector_store_id",
		"file_id",
		openai.VectorStoreFileUpdateParams{
			Attributes: map[string]openai.VectorStoreFileAttributesValue{"key": "x"},
		},
	)
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestVectorStoreFileUpdatePathParams(t *testing.T) {
	client := openai.NewClient(
		option.WithBaseURL("http://localhost:4010"),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.VectorStores.Files.Update(
		context.TODO(),
		"",
		"file_id",
		openai.VectorStoreFileUpdateParams{
			Attributes: map[string]openai.VectorStoreFileAttributesValue{"key": "x"},
		},
	)
	if err == nil || !strings.Contains(err.Error(), "missing required") {
		t.Fatal("expected a missing required path param error")
	}
}
