# Code generated by opensdk. DO NOT EDIT.

from __future__ import annotations

from typing import Optional

from ._pagination import CursorPage
from ._transport import Transport
from .models import *  # noqa: F401,F403


class BetaResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport
        self.threads = BetaThreadsResource(transport)


class BetaThreadsResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport
        self.messages = BetaThreadsMessagesResource(transport)


class BetaThreadsMessagesResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def list(self, thread_id: str, *, limit: Optional[int] = None, order: Optional[BetaThreadsMessagesListOrder] = None, after: Optional[str] = None, before: Optional[str] = None, run_id: Optional[str] = None) -> CursorPage[MessageObject]:
        if not thread_id:
            raise ValueError(f"Expected a non-empty value for `thread_id` but received {thread_id!r}")
        return CursorPage.from_response(MessageObject, self._transport.request("GET", f"/threads/{thread_id}/messages", query={"limit": limit, "order": order, "after": after, "before": before, "run_id": run_id}))
