// Code generated by opensdk. DO NOT EDIT.

import { APIResource } from '../core/resource';
import type { APIClient, RequestOptions } from '../core/request';
import type { MessageObject, Metadata } from '../models';

export class Beta extends APIResource {
  readonly threads: BetaThreads;

  constructor(client: APIClient) {
    super(client);
    this.threads = new BetaThreads(client);
  }
}

export class BetaThreads extends APIResource {
  readonly messages: BetaThreadsMessages;

  constructor(client: APIClient) {
    super(client);
    this.messages = new BetaThreadsMessages(client);
  }
}

export class BetaThreadsMessages extends APIResource {
  /** Modifies a message. */
  update(threadId: string, messageId: string, body: BetaThreadMessageUpdateParams, options?: RequestOptions): Promise<MessageObject> {
    if (!threadId) {
      throw new Error("missing required thread_id parameter");
    }
    if (!messageId) {
      throw new Error("missing required message_id parameter");
    }
    return this._client.request<MessageObject>({ method: "POST", path: `/threads/${threadId}/messages/${messageId}`, body }, options);
  }
}

export interface BetaThreadMessageUpdateParams {
  metadata?: Metadata;
}
