// Code generated by opensdk. DO NOT EDIT.

#![allow(dead_code, unused_imports)]
mod common;

use common::build_client;
use openai::*;

#[tokio::test]
async fn test_method_organization_admin_api_keys_create() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().admin_api_keys().create(AdminOrganizationAdminApiKeysCreateParams { name: Some("x".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_admin_api_keys_delete() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().admin_api_keys().delete("key_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_admin_api_keys_delete() {
    let client = build_client();
    let error = client.admin().organization().admin_api_keys().delete("").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_admin_api_keys_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().admin_api_keys().list(AdminOrganizationAdminApiKeysListParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_admin_api_keys_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().admin_api_keys().list(AdminOrganizationAdminApiKeysListParams { after: Some("after".to_string()), order: Some(AdminOrganizationAdminApiKeysListOrder::Asc), limit: Some(0), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_admin_api_keys_retrieve() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().admin_api_keys().retrieve("key_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_admin_api_keys_retrieve() {
    let client = build_client();
    let error = client.admin().organization().admin_api_keys().retrieve("").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_audit_logs_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().audit_logs().list(AdminOrganizationAuditLogsListParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_audit_logs_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().audit_logs().list(AdminOrganizationAuditLogsListParams { effective_at: Some(AdminOrganizationAuditLogsListEffectiveAt { gt: Some(0), gte: Some(0), lt: Some(0), lte: Some(0), ..Default::default() }), project_ids: Some(vec!["x".to_string()]), event_types: Some(vec![AuditLogEventType::ApiKeyCreated]), actor_ids: Some(vec!["x".to_string()]), actor_emails: Some(vec!["x".to_string()]), resource_ids: Some(vec!["x".to_string()]), limit: Some(0), after: Some("after".to_string()), before: Some("before".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_certificates_create() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().certificates().create(AdminOrganizationCertificatesCreateParams { certificate: Some("x".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_certificates_create_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().certificates().create(AdminOrganizationCertificatesCreateParams { certificate: Some("x".to_string()), name: Some("x".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_certificates_delete() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().certificates().delete("certificate_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_certificates_delete() {
    let client = build_client();
    let error = client.admin().organization().certificates().delete("").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_certificates_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().certificates().list(AdminOrganizationCertificatesListParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_certificates_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().certificates().list(AdminOrganizationCertificatesListParams { limit: Some(0), after: Some("after".to_string()), order: Some(AdminOrganizationCertificatesListOrder::Asc), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_certificates_retrieve() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().certificates().retrieve("certificate_id", AdminOrganizationCertificatesRetrieveParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_certificates_retrieve_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().certificates().retrieve("certificate_id", AdminOrganizationCertificatesRetrieveParams { include: Some(vec!["content".to_string()]), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_certificates_retrieve() {
    let client = build_client();
    let error = client.admin().organization().certificates().retrieve("", AdminOrganizationCertificatesRetrieveParams::default()).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_certificates_update() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().certificates().update("certificate_id", AdminOrganizationCertificatesUpdateParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_certificates_update_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().certificates().update("certificate_id", AdminOrganizationCertificatesUpdateParams { name: Some("x".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_certificates_update() {
    let client = build_client();
    let error = client.admin().organization().certificates().update("", AdminOrganizationCertificatesUpdateParams::default()).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_certificates_activate_create() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().certificates().activate().create(AdminOrganizationCertificatesActivateCreateParams { certificate_ids: Some(vec!["x".to_string()]), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_certificates_deactivate_create() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().certificates().deactivate().create(AdminOrganizationCertificatesDeactivateCreateParams { certificate_ids: Some(vec!["x".to_string()]), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_costs_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().costs().list(AdminOrganizationCostsListParams { start_time: Some(0), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_costs_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().costs().list(AdminOrganizationCostsListParams { start_time: Some(0), end_time: Some(0), bucket_width: Some("1d".to_string()), project_ids: Some(vec!["x".to_string()]), api_key_ids: Some(vec!["x".to_string()]), group_by: Some(vec![AdminOrganizationCostsListGroupByItem::ProjectId]), limit: Some(0), page: Some("page".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_groups_create() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().groups().create(AdminOrganizationGroupsCreateParams { name: Some("x".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_groups_delete() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().groups().delete("group_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_groups_delete() {
    let client = build_client();
    let error = client.admin().organization().groups().delete("").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_groups_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().groups().list(AdminOrganizationGroupsListParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_groups_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().groups().list(AdminOrganizationGroupsListParams { limit: Some(0), after: Some("after".to_string()), order: Some(AdminOrganizationGroupsListOrder::Asc), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_groups_update() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().groups().update("group_id", AdminOrganizationGroupsUpdateParams { name: Some("x".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_groups_update() {
    let client = build_client();
    let error = client.admin().organization().groups().update("", AdminOrganizationGroupsUpdateParams { name: Some("x".to_string()), ..Default::default() }).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_groups_roles_create() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().groups().roles().create("group_id", AdminOrganizationGroupsRolesCreateParams { role_id: Some("x".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_groups_roles_create() {
    let client = build_client();
    let error = client.admin().organization().groups().roles().create("", AdminOrganizationGroupsRolesCreateParams { role_id: Some("x".to_string()), ..Default::default() }).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_groups_roles_delete() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().groups().roles().delete("group_id", "role_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_groups_roles_delete() {
    let client = build_client();
    let error = client.admin().organization().groups().roles().delete("", "role_id").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_groups_roles_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().groups().roles().list("group_id", AdminOrganizationGroupsRolesListParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_groups_roles_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().groups().roles().list("group_id", AdminOrganizationGroupsRolesListParams { limit: Some(0), after: Some("after".to_string()), order: Some(AdminOrganizationGroupsRolesListOrder::Asc), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_groups_roles_list() {
    let client = build_client();
    let error = client.admin().organization().groups().roles().list("", AdminOrganizationGroupsRolesListParams::default()).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_groups_users_create() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().groups().users().create("group_id", AdminOrganizationGroupsUsersCreateParams { user_id: Some("x".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_groups_users_create() {
    let client = build_client();
    let error = client.admin().organization().groups().users().create("", AdminOrganizationGroupsUsersCreateParams { user_id: Some("x".to_string()), ..Default::default() }).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_groups_users_delete() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().groups().users().delete("group_id", "user_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_groups_users_delete() {
    let client = build_client();
    let error = client.admin().organization().groups().users().delete("", "user_id").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_groups_users_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().groups().users().list("group_id", AdminOrganizationGroupsUsersListParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_groups_users_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().groups().users().list("group_id", AdminOrganizationGroupsUsersListParams { limit: Some(0), after: Some("after".to_string()), order: Some(AdminOrganizationGroupsUsersListOrder::Asc), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_groups_users_list() {
    let client = build_client();
    let error = client.admin().organization().groups().users().list("", AdminOrganizationGroupsUsersListParams::default()).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_invites_create() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().invites().create(AdminOrganizationInvitesCreateParams { email: Some("x".to_string()), role: Some(InviteRequestRole::Reader), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_invites_create_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().invites().create(AdminOrganizationInvitesCreateParams { email: Some("x".to_string()), role: Some(InviteRequestRole::Reader), projects: Some(vec![InviteRequestProjectsItem { id: Some("x".to_string()), role: Some(InviteRequestProjectsItemRole::Member), ..Default::default() }]), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_invites_delete() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().invites().delete("invite_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_invites_delete() {
    let client = build_client();
    let error = client.admin().organization().invites().delete("").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_invites_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().invites().list(AdminOrganizationInvitesListParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_invites_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().invites().list(AdminOrganizationInvitesListParams { limit: Some(0), after: Some("after".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_invites_retrieve() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().invites().retrieve("invite_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_invites_retrieve() {
    let client = build_client();
    let error = client.admin().organization().invites().retrieve("").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_archive() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().archive("project_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_archive() {
    let client = build_client();
    let error = client.admin().organization().projects().archive("").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_create() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().create(AdminOrganizationProjectsCreateParams { name: Some("x".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_projects_create_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().create(AdminOrganizationProjectsCreateParams { name: Some("x".to_string()), geography: Some("x".to_string()), external_key_id: Some("x".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_projects_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().list(AdminOrganizationProjectsListParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_projects_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().list(AdminOrganizationProjectsListParams { limit: Some(0), after: Some("after".to_string()), include_archived: Some(true), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_projects_retrieve() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().retrieve("project_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_retrieve() {
    let client = build_client();
    let error = client.admin().organization().projects().retrieve("").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_update() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().update("project_id", AdminOrganizationProjectsUpdateParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_projects_update_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().update("project_id", AdminOrganizationProjectsUpdateParams { name: Some("x".to_string()), external_key_id: Some("x".to_string()), geography: Some("x".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_update() {
    let client = build_client();
    let error = client.admin().organization().projects().update("", AdminOrganizationProjectsUpdateParams::default()).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_api_keys_delete() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().api_keys().delete("project_id", "api_key_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_api_keys_delete() {
    let client = build_client();
    let error = client.admin().organization().projects().api_keys().delete("", "api_key_id").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_api_keys_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().api_keys().list("project_id", AdminOrganizationProjectsApiKeysListParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_projects_api_keys_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().api_keys().list("project_id", AdminOrganizationProjectsApiKeysListParams { limit: Some(0), after: Some("after".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_api_keys_list() {
    let client = build_client();
    let error = client.admin().organization().projects().api_keys().list("", AdminOrganizationProjectsApiKeysListParams::default()).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_api_keys_retrieve() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().api_keys().retrieve("project_id", "api_key_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_api_keys_retrieve() {
    let client = build_client();
    let error = client.admin().organization().projects().api_keys().retrieve("", "api_key_id").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_certificates_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().certificates().list("project_id", AdminOrganizationProjectsCertificatesListParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_projects_certificates_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().certificates().list("project_id", AdminOrganizationProjectsCertificatesListParams { limit: Some(0), after: Some("after".to_string()), order: Some(AdminOrganizationProjectsCertificatesListOrder::Asc), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_certificates_list() {
    let client = build_client();
    let error = client.admin().organization().projects().certificates().list("", AdminOrganizationProjectsCertificatesListParams::default()).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_certificates_activate_create() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().certificates().activate().create("project_id", AdminOrganizationProjectsCertificatesActivateCreateParams { certificate_ids: Some(vec!["x".to_string()]), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_certificates_activate_create() {
    let client = build_client();
    let error = client.admin().organization().projects().certificates().activate().create("", AdminOrganizationProjectsCertificatesActivateCreateParams { certificate_ids: Some(vec!["x".to_string()]), ..Default::default() }).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_certificates_deactivate_create() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().certificates().deactivate().create("project_id", AdminOrganizationProjectsCertificatesDeactivateCreateParams { certificate_ids: Some(vec!["x".to_string()]), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_certificates_deactivate_create() {
    let client = build_client();
    let error = client.admin().organization().projects().certificates().deactivate().create("", AdminOrganizationProjectsCertificatesDeactivateCreateParams { certificate_ids: Some(vec!["x".to_string()]), ..Default::default() }).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_groups_create() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().groups().create("project_id", AdminOrganizationProjectsGroupsCreateParams { group_id: Some("x".to_string()), role: Some("x".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_groups_create() {
    let client = build_client();
    let error = client.admin().organization().projects().groups().create("", AdminOrganizationProjectsGroupsCreateParams { group_id: Some("x".to_string()), role: Some("x".to_string()), ..Default::default() }).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_groups_delete() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().groups().delete("project_id", "group_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_groups_delete() {
    let client = build_client();
    let error = client.admin().organization().projects().groups().delete("", "group_id").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_groups_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().groups().list("project_id", AdminOrganizationProjectsGroupsListParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_projects_groups_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().groups().list("project_id", AdminOrganizationProjectsGroupsListParams { limit: Some(0), after: Some("after".to_string()), order: Some(AdminOrganizationProjectsGroupsListOrder::Asc), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_groups_list() {
    let client = build_client();
    let error = client.admin().organization().projects().groups().list("", AdminOrganizationProjectsGroupsListParams::default()).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_rate_limits_list_rate_limits() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().rate_limits().list_rate_limits("project_id", AdminOrganizationProjectsRateLimitsListRateLimitsParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_projects_rate_limits_list_rate_limits_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().rate_limits().list_rate_limits("project_id", AdminOrganizationProjectsRateLimitsListRateLimitsParams { limit: Some(0), after: Some("after".to_string()), before: Some("before".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_rate_limits_list_rate_limits() {
    let client = build_client();
    let error = client.admin().organization().projects().rate_limits().list_rate_limits("", AdminOrganizationProjectsRateLimitsListRateLimitsParams::default()).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_rate_limits_update_rate_limit() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().rate_limits().update_rate_limit("project_id", "rate_limit_id", AdminOrganizationProjectsRateLimitsUpdateRateLimitParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_projects_rate_limits_update_rate_limit_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().rate_limits().update_rate_limit("project_id", "rate_limit_id", AdminOrganizationProjectsRateLimitsUpdateRateLimitParams { max_requests_per_1_minute: Some(0), max_tokens_per_1_minute: Some(0), max_images_per_1_minute: Some(0), max_audio_megabytes_per_1_minute: Some(0), max_requests_per_1_day: Some(0), batch_1_day_max_input_tokens: Some(0), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_rate_limits_update_rate_limit() {
    let client = build_client();
    let error = client.admin().organization().projects().rate_limits().update_rate_limit("", "rate_limit_id", AdminOrganizationProjectsRateLimitsUpdateRateLimitParams::default()).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_service_accounts_create() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().service_accounts().create("project_id", AdminOrganizationProjectsServiceAccountsCreateParams { name: Some("x".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_service_accounts_create() {
    let client = build_client();
    let error = client.admin().organization().projects().service_accounts().create("", AdminOrganizationProjectsServiceAccountsCreateParams { name: Some("x".to_string()), ..Default::default() }).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_service_accounts_delete() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().service_accounts().delete("project_id", "service_account_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_service_accounts_delete() {
    let client = build_client();
    let error = client.admin().organization().projects().service_accounts().delete("", "service_account_id").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_service_accounts_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().service_accounts().list("project_id", AdminOrganizationProjectsServiceAccountsListParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_projects_service_accounts_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().service_accounts().list("project_id", AdminOrganizationProjectsServiceAccountsListParams { limit: Some(0), after: Some("after".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_service_accounts_list() {
    let client = build_client();
    let error = client.admin().organization().projects().service_accounts().list("", AdminOrganizationProjectsServiceAccountsListParams::default()).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_service_accounts_retrieve() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().service_accounts().retrieve("project_id", "service_account_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_service_accounts_retrieve() {
    let client = build_client();
    let error = client.admin().organization().projects().service_accounts().retrieve("", "service_account_id").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_users_create() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().users().create("project_id", AdminOrganizationProjectsUsersCreateParams { role: Some("x".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_projects_users_create_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().users().create("project_id", AdminOrganizationProjectsUsersCreateParams { role: Some("x".to_string()), user_id: Some("x".to_string()), email: Some("x".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_users_create() {
    let client = build_client();
    let error = client.admin().organization().projects().users().create("", AdminOrganizationProjectsUsersCreateParams { role: Some("x".to_string()), ..Default::default() }).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_users_delete() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().users().delete("project_id", "user_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_users_delete() {
    let client = build_client();
    let error = client.admin().organization().projects().users().delete("", "user_id").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_users_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().users().list("project_id", AdminOrganizationProjectsUsersListParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_projects_users_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().users().list("project_id", AdminOrganizationProjectsUsersListParams { limit: Some(0), after: Some("after".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_users_list() {
    let client = build_client();
    let error = client.admin().organization().projects().users().list("", AdminOrganizationProjectsUsersListParams::default()).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_users_retrieve() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().users().retrieve("project_id", "user_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_users_retrieve() {
    let client = build_client();
    let error = client.admin().organization().projects().users().retrieve("", "user_id").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_projects_users_update() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().users().update("project_id", "user_id", AdminOrganizationProjectsUsersUpdateParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_projects_users_update_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().projects().users().update("project_id", "user_id", AdminOrganizationProjectsUsersUpdateParams { role: Some("x".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_projects_users_update() {
    let client = build_client();
    let error = client.admin().organization().projects().users().update("", "user_id", AdminOrganizationProjectsUsersUpdateParams::default()).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_roles_create() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().roles().create(AdminOrganizationRolesCreateParams { role_name: Some("x".to_string()), permissions: Some(vec!["x".to_string()]), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_roles_create_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().roles().create(AdminOrganizationRolesCreateParams { role_name: Some("x".to_string()), permissions: Some(vec!["x".to_string()]), description: Some("x".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_roles_delete() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().roles().delete("role_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_roles_delete() {
    let client = build_client();
    let error = client.admin().organization().roles().delete("").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_roles_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().roles().list(AdminOrganizationRolesListParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_roles_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().roles().list(AdminOrganizationRolesListParams { limit: Some(0), after: Some("after".to_string()), order: Some(AdminOrganizationRolesListOrder::Asc), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_roles_update() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().roles().update("role_id", AdminOrganizationRolesUpdateParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_roles_update_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().roles().update("role_id", AdminOrganizationRolesUpdateParams { permissions: Some(vec!["x".to_string()]), description: Some("x".to_string()), role_name: Some("x".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_roles_update() {
    let client = build_client();
    let error = client.admin().organization().roles().update("", AdminOrganizationRolesUpdateParams::default()).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_usage_audio_speeches_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().usage().audio_speeches().list(AdminOrganizationUsageAudioSpeechesListParams { start_time: Some(0), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_usage_audio_speeches_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().usage().audio_speeches().list(AdminOrganizationUsageAudioSpeechesListParams { start_time: Some(0), end_time: Some(0), bucket_width: Some(AdminOrganizationUsageAudioSpeechesListBucketWidth::_1m), project_ids: Some(vec!["x".to_string()]), user_ids: Some(vec!["x".to_string()]), api_key_ids: Some(vec!["x".to_string()]), models: Some(vec!["x".to_string()]), group_by: Some(vec![AdminOrganizationUsageAudioSpeechesListGroupByItem::ProjectId]), limit: Some(0), page: Some("page".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_usage_audio_transcriptions_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().usage().audio_transcriptions().list(AdminOrganizationUsageAudioTranscriptionsListParams { start_time: Some(0), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_usage_audio_transcriptions_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().usage().audio_transcriptions().list(AdminOrganizationUsageAudioTranscriptionsListParams { start_time: Some(0), end_time: Some(0), bucket_width: Some(AdminOrganizationUsageAudioTranscriptionsListBucketWidth::_1m), project_ids: Some(vec!["x".to_string()]), user_ids: Some(vec!["x".to_string()]), api_key_ids: Some(vec!["x".to_string()]), models: Some(vec!["x".to_string()]), group_by: Some(vec![AdminOrganizationUsageAudioTranscriptionsListGroupByItem::ProjectId]), limit: Some(0), page: Some("page".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_usage_code_interpreter_sessions_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().usage().code_interpreter_sessions().list(AdminOrganizationUsageCodeInterpreterSessionsListParams { start_time: Some(0), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_usage_code_interpreter_sessions_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().usage().code_interpreter_sessions().list(AdminOrganizationUsageCodeInterpreterSessionsListParams { start_time: Some(0), end_time: Some(0), bucket_width: Some(AdminOrganizationUsageCodeInterpreterSessionsListBucketWidth::_1m), project_ids: Some(vec!["x".to_string()]), group_by: Some(vec!["project_id".to_string()]), limit: Some(0), page: Some("page".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_usage_completions_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().usage().completions().list(AdminOrganizationUsageCompletionsListParams { start_time: Some(0), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_usage_completions_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().usage().completions().list(AdminOrganizationUsageCompletionsListParams { start_time: Some(0), end_time: Some(0), bucket_width: Some(AdminOrganizationUsageCompletionsListBucketWidth::_1m), project_ids: Some(vec!["x".to_string()]), user_ids: Some(vec!["x".to_string()]), api_key_ids: Some(vec!["x".to_string()]), models: Some(vec!["x".to_string()]), batch: Some(true), group_by: Some(vec![AdminOrganizationUsageCompletionsListGroupByItem::ProjectId]), limit: Some(0), page: Some("page".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_usage_embeddings_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().usage().embeddings().list(AdminOrganizationUsageEmbeddingsListParams { start_time: Some(0), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_usage_embeddings_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().usage().embeddings().list(AdminOrganizationUsageEmbeddingsListParams { start_time: Some(0), end_time: Some(0), bucket_width: Some(AdminOrganizationUsageEmbeddingsListBucketWidth::_1m), project_ids: Some(vec!["x".to_string()]), user_ids: Some(vec!["x".to_string()]), api_key_ids: Some(vec!["x".to_string()]), models: Some(vec!["x".to_string()]), group_by: Some(vec![AdminOrganizationUsageEmbeddingsListGroupByItem::ProjectId]), limit: Some(0), page: Some("page".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_usage_images_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().usage().images().list(AdminOrganizationUsageImagesListParams { start_time: Some(0), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_usage_images_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().usage().images().list(AdminOrganizationUsageImagesListParams { start_time: Some(0), end_time: Some(0), bucket_width: Some(AdminOrganizationUsageImagesListBucketWidth::_1m), sources: Some(vec![AdminOrganizationUsageImagesListSourcesItem::ImageGeneration]), sizes: Some(vec![AdminOrganizationUsageImagesListSizesItem::_256x256]), project_ids: Some(vec!["x".to_string()]), user_ids: Some(vec!["x".to_string()]), api_key_ids: Some(vec!["x".to_string()]), models: Some(vec!["x".to_string()]), group_by: Some(vec![AdminOrganizationUsageImagesListGroupByItem::ProjectId]), limit: Some(0), page: Some("page".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_usage_moderations_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().usage().moderations().list(AdminOrganizationUsageModerationsListParams { start_time: Some(0), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_usage_moderations_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().usage().moderations().list(AdminOrganizationUsageModerationsListParams { start_time: Some(0), end_time: Some(0), bucket_width: Some(AdminOrganizationUsageModerationsListBucketWidth::_1m), project_ids: Some(vec!["x".to_string()]), user_ids: Some(vec!["x".to_string()]), api_key_ids: Some(vec!["x".to_string()]), models: Some(vec!["x".to_string()]), group_by: Some(vec![AdminOrganizationUsageModerationsListGroupByItem::ProjectId]), limit: Some(0), page: Some("page".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_usage_vector_stores_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().usage().vector_stores().list(AdminOrganizationUsageVectorStoresListParams { start_time: Some(0), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_usage_vector_stores_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().usage().vector_stores().list(AdminOrganizationUsageVectorStoresListParams { start_time: Some(0), end_time: Some(0), bucket_width: Some(AdminOrganizationUsageVectorStoresListBucketWidth::_1m), project_ids: Some(vec!["x".to_string()]), group_by: Some(vec!["project_id".to_string()]), limit: Some(0), page: Some("page".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_users_delete() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().users().delete("user_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_users_delete() {
    let client = build_client();
    let error = client.admin().organization().users().delete("").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_users_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().users().list(AdminOrganizationUsersListParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_users_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().users().list(AdminOrganizationUsersListParams { limit: Some(0), after: Some("after".to_string()), emails: Some(vec!["x".to_string()]), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_users_retrieve() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().users().retrieve("user_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_users_retrieve() {
    let client = build_client();
    let error = client.admin().organization().users().retrieve("").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_users_update() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().users().update("user_id", AdminOrganizationUsersUpdateParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_users_update_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().users().update("user_id", AdminOrganizationUsersUpdateParams { role: Some("x".to_string()), role_id: Some("x".to_string()), technical_level: Some("x".to_string()), developer_persona: Some("x".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_users_update() {
    let client = build_client();
    let error = client.admin().organization().users().update("", AdminOrganizationUsersUpdateParams::default()).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_users_roles_create() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().users().roles().create("user_id", AdminOrganizationUsersRolesCreateParams { role_id: Some("x".to_string()), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_users_roles_create() {
    let client = build_client();
    let error = client.admin().organization().users().roles().create("", AdminOrganizationUsersRolesCreateParams { role_id: Some("x".to_string()), ..Default::default() }).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_users_roles_delete() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().users().roles().delete("user_id", "role_id").await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_users_roles_delete() {
    let client = build_client();
    let error = client.admin().organization().users().roles().delete("", "role_id").await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}

#[tokio::test]
async fn test_method_organization_users_roles_list() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().users().roles().list("user_id", AdminOrganizationUsersRolesListParams::default()).await?;
    Ok(())
}

#[tokio::test]
async fn test_method_organization_users_roles_list_with_all_params() -> Result<(), Box<dyn std::error::Error>> {
    let client = build_client();
    let _ = client.admin().organization().users().roles().list("user_id", AdminOrganizationUsersRolesListParams { limit: Some(0), after: Some("after".to_string()), order: Some(AdminOrganizationUsersRolesListOrder::Asc), ..Default::default() }).await?;
    Ok(())
}

#[tokio::test]
async fn test_path_params_organization_users_roles_list() {
    let client = build_client();
    let error = client.admin().organization().users().roles().list("", AdminOrganizationUsersRolesListParams::default()).await.unwrap_err();
    assert!(matches!(error, Error::InvalidArgument(_)));
}
