// Code generated by opensdk. DO NOT EDIT.

package openai

import (
	"context"
	"net/http"

	"github.com/example/openai/internal/requestconfig"
	"github.com/example/openai/option"
	"github.com/example/openai/packages/apijson"
)

// ConversationService ...
type ConversationService struct {
	Options []option.RequestOption
}

// NewConversationService constructs a service that shares the client's request options.
func NewConversationService(opts ...option.RequestOption) (r ConversationService) {
	r = ConversationService{}
	r.Options = opts
	return
}

// Create a conversation.
func (r *ConversationService) New(ctx context.Context, body ConversationNewParams, opts ...option.RequestOption) (res *ConversationResource, err error) {
	opts = append(r.Options[:], opts...)
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodPost, "conversations", body, opts...)
	if err != nil {
		return
	}
	res = &ConversationResource{}
	err = cfg.Execute(res)
	return
}

type ConversationNewParams struct {
	Metadata Metadata `json:"metadata,omitempty"`
	Items []InputItem `json:"items,omitempty"`
}

func (r ConversationNewParams) MarshalJSON() ([]byte, error) {
	return apijson.MarshalRoot(r)
}
