// <auto-generated>
//     Code generated by opensdk. DO NOT EDIT.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace Example.Openai;

public sealed class AdminService
{
    private readonly Transport _transport;
    public AdminOrganizationService Organization { get; }

    internal AdminService(Transport transport)
    {
        _transport = transport;
        Organization = new AdminOrganizationService(transport);
    }
}

public sealed class AdminOrganizationService
{
    private readonly Transport _transport;
    public AdminOrganizationAdminApiKeysService AdminApiKeys { get; }

    internal AdminOrganizationService(Transport transport)
    {
        _transport = transport;
        AdminApiKeys = new AdminOrganizationAdminApiKeysService(transport);
    }
}

public sealed class AdminOrganizationAdminApiKeysService
{
    private readonly Transport _transport;

    internal AdminOrganizationAdminApiKeysService(Transport transport)
    {
        _transport = transport;
    }

    /// <summary>Retrieve a paginated list of organization admin API keys.</summary>
    public async Task<CursorPage<AdminApiKey>> List(string? after = null, AdminOrganizationAdminApiKeysListOrder? order = null, long? limit = null, CancellationToken cancellationToken = default)
    {
        var query = new Dictionary<string, object?>
        {
            ["after"] = after,
            ["order"] = order,
            ["limit"] = limit,
        };
        return await _transport.RequestAsync<CursorPage<AdminApiKey>>(HttpMethod.Get, "/organization/admin_api_keys", query: query, cancellationToken: cancellationToken).ConfigureAwait(false);
    }
}
