# Code generated by opensdk. DO NOT EDIT.

module Openai
  module Resources
    class FineTuning
      attr_reader :jobs

      # @api private
      def initialize(transport)
        @transport = transport
        @jobs = FineTuningJobs.new(transport)
      end
    end

    class FineTuningJobs
      # @api private
      def initialize(transport)
        @transport = transport
      end

      # List your organization's fine-tuning jobs
      #
      # @param after [String]
      # @param limit [Integer]
      # @param metadata [Hash{String => String}]
      # @return [Page<Models::FineTuningJob>]
      def list(after: nil, limit: nil, metadata: nil)
        response = @transport.request(
          method: :get,
          path: "/fine_tuning/jobs",
          query: { "after" => after, "limit" => limit, "metadata" => metadata }
        )
        Openai::Page.new(data: (response || {})[:data], has_more: (response || {})[:has_more])
      end
    end
  end
end
