// Code generated by opensdk. DO NOT EDIT.

package petstore

import (
	"context"
	"errors"
	"fmt"
	"net/http"

	"github.com/example/petstore/internal/requestconfig"
	"github.com/example/petstore/option"
	"github.com/example/petstore/packages/apijson"
	"github.com/example/petstore/packages/pagination"
	"github.com/example/petstore/packages/param"
)

// PetService ...
type PetService struct {
	Options []option.RequestOption
}

// NewPetService constructs a service that shares the client's request options.
func NewPetService(opts ...option.RequestOption) (r PetService) {
	r = PetService{}
	r.Options = opts
	return
}

// List pets
func (r *PetService) List(ctx context.Context, query PetListParams, opts ...option.RequestOption) (res *pagination.CursorPage[Pet], err error) {
	opts = append(r.Options[:], opts...)
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, "pets", nil, opts...)
	if err != nil {
		return
	}
	if query.After.IsPresent() {
		cfg.Query.Set("after", fmt.Sprintf("%v", query.After.Value()))
	}
	if query.Limit.IsPresent() {
		cfg.Query.Set("limit", fmt.Sprintf("%v", query.Limit.Value()))
	}
	res = &pagination.CursorPage[Pet]{}
	err = cfg.Execute(res)
	if err != nil {
		return
	}
	res.SetPageConfig(cfg, "after")
	return
}

// Create a pet
func (r *PetService) New(ctx context.Context, body PetNewParams, opts ...option.RequestOption) (res *Pet, err error) {
	opts = append(r.Options[:], opts...)
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodPost, "pets", body, opts...)
	if err != nil {
		return
	}
	res = &Pet{}
	err = cfg.Execute(res)
	return
}

// Retrieve a pet
func (r *PetService) Get(ctx context.Context, petID string, opts ...option.RequestOption) (res *Pet, err error) {
	opts = append(r.Options[:], opts...)
	if petID == "" {
		err = errors.New("missing required pet_id parameter")
		return
	}
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, fmt.Sprintf("pets/%v", petID), nil, opts...)
	if err != nil {
		return
	}
	res = &Pet{}
	err = cfg.Execute(res)
	return
}

// Download a pet's photo
func (r *PetService) DownloadPhoto(ctx context.Context, petID string, opts ...option.RequestOption) (res *http.Response, err error) {
	opts = append(r.Options[:], opts...)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "application/binary")}, opts...)
	if petID == "" {
		err = errors.New("missing required pet_id parameter")
		return
	}
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, fmt.Sprintf("pets/%v/photo", petID), nil, opts...)
	if err != nil {
		return
	}
	res, err = cfg.ExecuteRaw()
	return
}

type PetListParams struct {
	After param.Opt[string] `json:"-" query:"after"`
	Limit param.Opt[int64] `json:"-" query:"limit"`
}

type PetNewParams struct {
	Name string `json:"name,required"`
	Status PetStatus `json:"status,omitempty"`
}

func (r PetNewParams) MarshalJSON() ([]byte, error) {
	return apijson.MarshalRoot(r)
}
