# Code generated by opensdk. DO NOT EDIT.

from __future__ import annotations

from ._transport import Transport, decode
from .models import *  # noqa: F401,F403


class BetaResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport
        self.threads = BetaThreadsResource(transport)


class BetaThreadsResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport
        self.messages = BetaThreadsMessagesResource(transport)


class BetaThreadsMessagesResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def delete(self, thread_id: str, message_id: str) -> DeleteMessageResponse:
        if not thread_id:
            raise ValueError(f"Expected a non-empty value for `thread_id` but received {thread_id!r}")
        if not message_id:
            raise ValueError(f"Expected a non-empty value for `message_id` but received {message_id!r}")
        return decode(DeleteMessageResponse, self._transport.request("DELETE", f"/threads/{thread_id}/messages/{message_id}"))
