// Code generated by opensdk. DO NOT EDIT.

export interface BranchesRequest {
  kind: ProviderKind;
  baseUrl: string;
  token: string;
  login?: string;
  repo: string;
}

export type ProviderKind = "github" | "gitlab" | "bitbucket" | "gitea";

export interface ErrorResponse {
  error: string;
}

export interface CreateReleaseBody {
  kind: ProviderKind;
  baseUrl: string;
  token: string;
  login?: string;
  repo: string;
  tag: string;
  name: string;
  body: string;
  commitish: string;
  prerelease: boolean;
}

export interface CreateReleaseResult {
  url: string;
  tag: string;
}

export interface CreateRepoBody {
  kind: ProviderKind;
  baseUrl: string;
  token: string;
  login?: string;
  name: string;
  private: boolean;
  defaultBranch?: string;
}

export interface Repo {
  fullName: string;
  namespace: string;
  name: string;
  defaultBranch: string;
  cloneUrl: string;
  htmlUrl: string;
  private: boolean;
}

export interface CreateTagBody {
  kind: ProviderKind;
  baseUrl: string;
  token: string;
  login?: string;
  repo: string;
  tag: string;
  ref: string;
  author: Signature;
}

export interface Signature {
  name: string;
  email: string;
}

export interface CreateTagResult {
  tag: string;
  sha: string;
}

/** Verify + parse a raw webhook delivery. No token — the secret authenticates it. */
export interface ParseWebhookBody {
  kind: ProviderKind;
  secret: string;
  headers: Record<string, string>;
  bodyBase64: string;
}

export interface ParseWebhookResult {
  event: string;
  action: string;
  number: number;
  merged: boolean;
  baseBranch: string;
  mergeSha: string;
  verified: boolean;
}

export interface PrStatusBody {
  kind: ProviderKind;
  baseUrl: string;
  token: string;
  login?: string;
  repo: string;
  number: number;
}

export interface PrStatusResult {
  number: number;
  merged: boolean;
  closed: boolean;
  mergeSha: string;
  baseBranch: string;
}

export interface RegisterWebhookBody {
  kind: ProviderKind;
  baseUrl: string;
  token: string;
  login?: string;
  repo: string;
  target: string;
  secret: string;
}

export interface RegisterWebhookResult {
  id: string;
}

/** Per-request provider credentials, inlined into every body. */
export interface Creds {
  kind: ProviderKind;
  baseUrl: string;
  token: string;
  login?: string;
}

export interface SyncBody {
  kind: ProviderKind;
  baseUrl: string;
  token: string;
  login?: string;
  repo: string;
  branch: string;
  prefix: string;
  message: string;
  author: Signature;
  files: FileEntry[];
}

/** A file to push; content is base64-encoded on the wire. */
export interface FileEntry {
  path: string;
  contentBase64: string;
}

export interface SyncResult {
  commit: string;
  branch: string;
  htmlUrl: string;
  noChanges: boolean;
}

/** Open or force-update a rolling release PR (push files to head, PR head→base). */
export interface UpsertPrBody {
  kind: ProviderKind;
  baseUrl: string;
  token: string;
  login?: string;
  repo: string;
  headBranch: string;
  baseBranch: string;
  prefix: string;
  title: string;
  body: string;
  author: Signature;
  files: FileEntry[];
  replaceSubtree: boolean;
}

export interface UpsertPrResult {
  number: number;
  url: string;
  branch: string;
  commit: string;
  created: boolean;
  noChanges: boolean;
}

export interface User {
  login: string;
  name: string;
  email: string;
}
