// Code generated by opensdk. DO NOT EDIT.

import { APIResource } from '../core/resource';
import type { APIClient, RequestOptions } from '../core/request';
import { CursorPage } from '../core/pagination';
import type { AdminOrganizationUsageCompletionsListBucketWidth, AdminOrganizationUsageCompletionsListGroupByItem, UsageTimeBucket } from '../models';

export class Admin extends APIResource {
  readonly organization: AdminOrganization;

  constructor(client: APIClient) {
    super(client);
    this.organization = new AdminOrganization(client);
  }
}

export class AdminOrganization extends APIResource {
  readonly usage: AdminOrganizationUsage;

  constructor(client: APIClient) {
    super(client);
    this.usage = new AdminOrganizationUsage(client);
  }
}

export class AdminOrganizationUsage extends APIResource {
  readonly completions: AdminOrganizationUsageCompletions;

  constructor(client: APIClient) {
    super(client);
    this.completions = new AdminOrganizationUsageCompletions(client);
  }
}

export class AdminOrganizationUsageCompletions extends APIResource {
  /** Get completions usage details for the organization. */
  list(query: AdminOrganizationUsageCompletionListParams, options?: RequestOptions): Promise<CursorPage<UsageTimeBucket>> {
    return this._client
      .request<unknown>({ method: "GET", path: "/organization/usage/completions", query }, options)
      .then((raw) => CursorPage.fromResponse<UsageTimeBucket>(raw));
  }
}

export interface AdminOrganizationUsageCompletionListParams {
  start_time: number;
  end_time?: number;
  bucket_width?: AdminOrganizationUsageCompletionsListBucketWidth;
  project_ids?: string[];
  user_ids?: string[];
  api_key_ids?: string[];
  models?: string[];
  batch?: boolean;
  group_by?: AdminOrganizationUsageCompletionsListGroupByItem[];
  limit?: number;
  page?: string;
}
