# Code generated by opensdk. DO NOT EDIT.

module Packer
  # Client drives the packer CLI (the `packer` binary).
  class Client
    # Creates a client that runs `packer` (override with the PACKER_BIN env var or bin_path:).
    def initialize(bin_path: nil, env: nil, cwd: nil, timeout_ms: nil)
      @runner = Packer::Runner.new(bin_path: bin_path, env: env, cwd: cwd, timeout_ms: timeout_ms)
    end

    # Pack files
    #
    # @param dest [String]
    # @param files [Array<String>]
    # @param tag [Array<String>]
    # @param meta [Object]
    # @return [CommandResult]
    def pack(dest, files, tag: nil, meta: nil)
      raise ArgumentError, "Expected a non-empty value for `dest`" if dest.nil? || dest.to_s.empty?

      argv = ["pack"]
      argv << dest
      (files || []).each do |value|
        argv << value
      end
      (tag || []).each do |value|
        argv.push("--tag", value)
      end
      argv.push("--meta", JSON.generate(meta)) unless meta.nil?
      @runner.run(argv)
    end
  end
end
