// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

public final class FineTuningJobService {
  private final Transport transport;

  FineTuningJobService(Transport transport) {
    this.transport = transport;
  }

  /** List your organization's fine-tuning jobs */
  public CursorPage<FineTuningJob> list(FineTuningJobListParams params) {
    Transport.Request request = new Transport.Request("GET", "/fine_tuning/jobs");
    params.after().ifPresent(value -> request.query("after", String.valueOf(value)));
    params.limit().ifPresent(value -> request.query("limit", String.valueOf(value)));
    params.metadata().ifPresent(entries -> entries.forEach((mapKey, mapValue) -> request.query("metadata[" + mapKey + "]", String.valueOf(mapValue))));
    return CursorPage.fromJson(transport.execute(request), __e -> FineTuningJob.fromJson(__e));
  }
}
