// <auto-generated>
//     Code generated by opensdk. DO NOT EDIT.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace Example.Openai;

public sealed class FineTuningService
{
    private readonly Transport _transport;
    public FineTuningCheckpointsService Checkpoints { get; }

    internal FineTuningService(Transport transport)
    {
        _transport = transport;
        Checkpoints = new FineTuningCheckpointsService(transport);
    }
}

public sealed class FineTuningCheckpointsService
{
    private readonly Transport _transport;
    public FineTuningCheckpointsPermissionsService Permissions { get; }

    internal FineTuningCheckpointsService(Transport transport)
    {
        _transport = transport;
        Permissions = new FineTuningCheckpointsPermissionsService(transport);
    }
}

public sealed class FineTuningCheckpointsPermissionsService
{
    private readonly Transport _transport;

    internal FineTuningCheckpointsPermissionsService(Transport transport)
    {
        _transport = transport;
    }

    /// <summary>
    /// **NOTE:** This endpoint requires an [admin API key](../admin-api-keys).
    /// Organization owners can use this endpoint to view all permissions for a fine-tuned model checkpoint.
    /// </summary>
    public async Task<CursorPage<FineTuningCheckpointPermission>> List(string fineTunedModelCheckpoint, string? projectId = null, string? after = null, long? limit = null, FineTuningCheckpointsPermissionsListOrder? order = null, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrEmpty(fineTunedModelCheckpoint))
        {
            throw new ArgumentException("Expected a non-empty value for fineTunedModelCheckpoint.", nameof(fineTunedModelCheckpoint));
        }
        var query = new Dictionary<string, object?>
        {
            ["project_id"] = projectId,
            ["after"] = after,
            ["limit"] = limit,
            ["order"] = order,
        };
        return await _transport.RequestAsync<CursorPage<FineTuningCheckpointPermission>>(HttpMethod.Get, $"/fine_tuning/checkpoints/{fineTunedModelCheckpoint}/permissions", query: query, cancellationToken: cancellationToken).ConfigureAwait(false);
    }
}
