// Code generated by opensdk. DO NOT EDIT.

import { CLIResource } from '../core/command';
import type { CLIClient, CommandResult } from '../core/command';

export class Chat extends CLIResource {
  readonly completions: ChatCompletions;

  constructor(client: CLIClient) {
    super(client);
    this.completions = new ChatCompletions(client);
  }
}

export class ChatCompletions extends CLIResource {
  /**
   * List completions
   *
   * Runs `acme chat completions list`.
   */
  list(): Promise<CommandResult> {
    const argv: string[] = ["chat", "completions", "list"];
    return this._client._run(argv);
  }

  /**
   * Create a completion
   *
   * Runs `acme chat completions create`.
   */
  create(prompt: string, params: ChatCompletionCreateParams): Promise<CommandResult> {
    if (!prompt) {
      throw new Error("missing required prompt parameter");
    }
    const argv: string[] = ["chat", "completions", "create"];
    argv.push(prompt);
    argv.push("--model", params.model);
    if (params.temperature !== undefined) {
      argv.push("--temperature", String(params.temperature));
    }
    return this._client._run(argv);
  }
}

export interface ChatCompletionCreateParams {
  model: string;
  temperature?: number;
}
