// Code generated by opensdk. DO NOT EDIT.

use std::sync::Arc;

use crate::error::Error;
use crate::models::*;
use crate::transport::{Page, Transport};

pub struct Audio {
    transport: Arc<Transport>,
}

impl Audio {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        Audio { transport }
    }

    pub fn voices(&self) -> AudioVoices {
        AudioVoices::new(self.transport.clone())
    }
}

pub struct AudioVoices {
    transport: Arc<Transport>,
}

impl AudioVoices {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        AudioVoices { transport }
    }

    /// Create a custom voice you can use for audio output (for example, in Text-to-Speech and the Realtime API). This requires an audio sample and a previously uploaded consent recording.
    ///
    /// See the [custom voices guide](/docs/guides/text-to-speech#custom-voices) for requirements and best practices. Custom voices are limited to eligible customers.
    pub async fn create(&self, params: AudioVoicesCreateParams) -> Result<VoiceResource, Error> {
        let mut req = self.transport.request(reqwest::Method::POST, "/audio/voices");
        if let Some(value) = &params.name {
            req = req.multipart_json("name", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.audio_sample {
            req = req.multipart_file("audio_sample", value.clone());
        }
        if let Some(value) = &params.consent {
            req = req.multipart_json("consent", serde_json::to_value(value)?);
        }
        req.send().await
    }
}

#[derive(Debug, Clone, Default)]
pub struct AudioVoicesCreateParams {
    /// The name of the new voice.
    pub name: Option<String>,
    /// The sample audio recording file. Maximum size is 10 MiB.
    ///
    /// Supported MIME types:
    /// `audio/mpeg`, `audio/wav`, `audio/x-wav`, `audio/ogg`, `audio/aac`, `audio/flac`, `audio/webm`, `audio/mp4`.
    pub audio_sample: Option<Vec<u8>>,
    /// The consent recording ID (for example, `cons_1234`).
    pub consent: Option<String>,
}
