// TODO: in the future move to separate package
export const syntaxThemeCosmo = {
    name: "cosmo",
    "type": "from-css",
    colors: {
        "list.focusForeground": "var(--ch-1)",
        "scrollbar.shadow": "var(--ch-2)",
        "tab.activeBorder": "var(--ch-1)",
        "widget.shadow": "var(--ch-2)",
        "activityBar.border": "var(--ch-3)",
        "editorGroup.border": "var(--ch-3)",
        "editorGroupHeader.tabsBorder": "var(--ch-3)",
        "editorWidget.border": "var(--ch-3)",
        "editorWidget.resizeBorder": "var(--ch-3)",
        "input.border": "var(--ch-3)",
        "notificationCenter.border": "var(--ch-3)",
        "notifications.border": "var(--ch-3)",
        "panel.border": "var(--ch-3)",
        "sideBar.border": "var(--ch-3)",
        "statusBar.border": "var(--ch-3)",
        "tab.border": "var(--ch-3)",
        "activityBar.background": "var(--ch-4)",
        "statusBar.background": "var(--ch-4)",
        "statusBar.noFolderBackground": "var(--ch-4)",
        "statusBar.debuggingBackground": "var(--ch-4)",
        "editorGroupHeader.tabsBackground": "var(--ch-5)",
        "editorWidget.background": "var(--ch-5)",
        "sideBar.background": "var(--ch-5)",
        "sideBarSectionHeader.background": "var(--ch-5)",
        "tab.inactiveBackground": "var(--ch-5)",
        "activityBarBadge.background": "var(--ch-6)",
        "activityBar.foreground": "var(--ch-6)",
        "statusBar.foreground": "var(--ch-7)",
        "input.placeholderForeground": "var(--ch-8)",
        "editorLineNumber.foreground": "var(--ch-9)",
        "editorLineNumber.activeForeground": "var(--ch-6)",
        foreground: "var(--ch-6)",
        "panelTitle.activeForeground": "var(--ch-6)",
        "sideBarTitle.foreground": "var(--ch-6)",
        "sideBarSectionHeader.foreground": "var(--ch-6)",
        "panelTitle.inactiveForeground": "var(--ch-10)",
        "tab.inactiveForeground": "var(--ch-10)",
        "list.highlightForeground": "var(--ch-10)",
        "editor.lineHighlightBackground": "var(--ch-11)",
        focusBorder: "var(--ch-12)",
        "button.background": "var(--ch-13)",
        "list.activeSelectionBackground": "var(--ch-13)",
        "list.focusBackground": "var(--ch-13)",
        "selection.background": "#B3D7FF",
        "list.inactiveSelectionBackground": "var(--ch-14)",
        "terminal.ansiBlack": "var(--ch-15)",
        "terminal.ansiBrightBlack": "var(--ch-15)",
        "terminal.ansiRed": "var(--ch-16)",
        "terminal.ansiBrightRed": "var(--ch-16)",
        "terminal.ansiGreen": "var(--ch-17)",
        "terminal.ansiBrightGreen": "var(--ch-17)",
        "terminal.ansiYellow": "var(--ch-18)",
        "terminal.ansiBrightYellow": "var(--ch-18)",
        "terminal.ansiBlue": "var(--ch-19)",
        "terminal.ansiBrightBlue": "var(--ch-19)",
        "terminal.ansiMagenta": "var(--ch-20)",
        "terminal.ansiBrightMagenta": "var(--ch-20)",
        "terminal.ansiCyan": "var(--ch-21)",
        "terminal.ansiBrightCyan": "var(--ch-21)",
    },
    tokenColors: [
        {
            scope: "new.expr entity.name",
            settings: {
                foreground: "var(--ch-22)",
            },
        },
        {
            name: "Comments",
            scope: ["comment", "comment storage.type"],
            settings: {
                foreground: "var(--ch-23)",
                fontStyle: "italic",
            },
        },
        {
            name: "CSS",
            scope: [
                "entity.other.attribute-name.pseudo-class.css",
                "entity.other.attribute-name.pseudo-class.scss",
                "entity.other.attribute-name.pseudo-element.css",
                "entity.other.attribute-name.pseudo-element.scss",
                "support.function.calc.css",
                "support.function.calc.scss",
                "support.type.property-name.css",
                "support.type.property-name.scss",
                "support.type.vendored.property-name.css",
                "support.type.vendored.property-name.scss",
                "meta.property-value.css support.constant",
                "meta.property-value.scss support.constant",
                "meta.property-value.css support.constant.property-value",
                "meta.property-value.scss support.constant.property-value",
                "support.function.transform.css",
                "support.function.transform.scss",
            ],
            settings: {
                foreground: "var(--ch-20)",
            },
        },
        {
            name: "Decorator",
            scope: [
                "meta.decorator",
                "meta.decorator punctuation.decorator",
                "meta.decorator variable.other.readwrite",
                "meta.decorator meta.function-call entity.name.function",
            ],
            settings: {
                foreground: "var(--ch-18)",
            },
        },
        {
            name: "Doctype",
            scope: ["meta.tag.sgml.html"],
            settings: {
                foreground: "var(--ch-9)",
            },
        },
        {
            name: "Functions",
            scope: ["entity.name.function", "support.function"],
            settings: {
                foreground: "var(--ch-24)",
            },
        },
        {
            name: "Keys",
            scope: [
                "meta.property-list meta.property-name",
                "support.type.property-name",
                "support.type.map.key",
                "entity.name.tag.yaml",
            ],
            settings: {
                foreground: "var(--ch-24)",
            },
        },
        {
            name: "Keywords",
            scope: [
                "keyword.control",
                "keyword.declaration",
                "keyword.expressions-and-types",
                "keyword.operator.new",
                "keyword.reserved",
                "keyword.statement",
                "storage.type",
                "storage.modifier",
                "constant.language",
                "variable.language.super",
                "variable.language.this",
                "text.html entity.name.tag",
                "meta.tag entity.name.tag",
                "meta.tag support.class",
                "string.regexp keyword.other",
            ],
            settings: {
                foreground: "var(--ch-25)",
                fontStyle: "bold",
            },
        },
        {
            name: "Operators",
            scope: [
                "storage.type.function.arrow",
                "meta.template.expression punctuation",
                "punctuation.separator.key-value",
                "meta.object-literal.key meta.brace.square",
                "meta.template.expression keyword.operator",
                "keyword.operator.or.regexp",
                "keyword.operator.quantifier",
                "punctuation.definition.group.regexp",
                "punctuation.definition.character-class",
            ],
            settings: {
                foreground: "var(--ch-15)",
            },
        },
        {
            scope: [
                "meta.tag entity.other.attribute-name",
                "constant.character.escape.backslash",
            ],
            settings: {
                foreground: "var(--ch-26)",
            },
        },
        {
            name: "Numbers",
            scope: ["constant.numeric", "keyword.other.unit", "constant.other.color"],
            settings: {
                foreground: "var(--ch-19)",
            },
        },
        {
            name: "Strings",
            scope: [
                "string",
                "variable.parameter.url.scss",
                "markup.heading.markdown",
                "beginning.punctuation.definition.list.markdown",
                "meta.template.expression meta.embedded punctuation.definition.string.begin",
                "meta.template.expression meta.embedded punctuation.definition.string.end",
            ],
            settings: {
                foreground: "var(--ch-27)",
            },
        },
        {
            name: "Types",
            scope: [
                "meta.type",
                "meta.return.type",
                "entity.name.type",
                "support.type.primitive",
            ],
            settings: {
                foreground: "var(--ch-22)",
            },
        },
        {
            scope: [
                "meta.objectliteral variable.other.object",
                "entity.name.type.module",
                "entity.other.inherited-class",
                "variable.scss",
                "variable.other.bracket.shell",
                "entity.name.function.scss",
            ],
            settings: {
                foreground: "var(--ch-21)",
            },
        },
        {
            scope: [
                "keyword.control.at-rule",
                "meta.import variable.other.readwrite",
                "meta.definition.variable variable.other.readwrite",
                "meta.definition.variable variable.other.constant",
                "meta.template.expression variable.other.readwrite",
                "meta.template.expression variable.other.constant",
                "support.constant.property-value",
            ],
            settings: {
                foreground: "var(--ch-15)",
            },
        },
        {
            scope: [
                "variable.other.property",
                "variable.other.object.property",
                "support.variable.property",
            ],
            settings: {
                foreground: "var(--ch-22)",
            },
        },
    ],
}
