# Code generated by opensdk. DO NOT EDIT.

require_relative "test_helper"

class TestBeta < Minitest::Test
  include TestHelper

  def test_method_assistants_create
    client = build_client
    result = client.beta.assistants.create(model: "x")
    refute_nil(result)
  end

  def test_method_assistants_create_with_all_params
    client = build_client
    result = client.beta.assistants.create(model: "x", name: "x", description: "x", instructions: "x", reasoning_effort: "none", tools: [{ "type" => "code_interpreter" }], tool_resources: { "code_interpreter" => { "file_ids" => ["x"] }, "file_search" => nil }, metadata: { "key" => "x" }, temperature: 0, top_p: 0, response_format: "auto")
    refute_nil(result)
  end

  def test_method_assistants_delete
    client = build_client
    result = client.beta.assistants.delete("assistant_id")
    refute_nil(result)
  end

  def test_path_params_assistants_delete
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.assistants.delete("")
    end
  end

  def test_method_assistants_list
    client = build_client
    result = client.beta.assistants.list
    assert_instance_of(Openai::Page, result)
  end

  def test_method_assistants_list_with_all_params
    client = build_client
    result = client.beta.assistants.list(limit: 0, order: "asc", after: "after", before: "before")
    assert_instance_of(Openai::Page, result)
  end

  def test_method_assistants_retrieve
    client = build_client
    result = client.beta.assistants.retrieve("assistant_id")
    refute_nil(result)
  end

  def test_path_params_assistants_retrieve
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.assistants.retrieve("")
    end
  end

  def test_method_assistants_update
    client = build_client
    result = client.beta.assistants.update("assistant_id")
    refute_nil(result)
  end

  def test_method_assistants_update_with_all_params
    client = build_client
    result = client.beta.assistants.update("assistant_id", model: "x", reasoning_effort: "none", name: "x", description: "x", instructions: "x", tools: [{ "type" => "code_interpreter" }], tool_resources: { "code_interpreter" => { "file_ids" => ["x"] }, "file_search" => { "vector_store_ids" => ["x"] } }, metadata: { "key" => "x" }, temperature: 0, top_p: 0, response_format: "auto")
    refute_nil(result)
  end

  def test_path_params_assistants_update
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.assistants.update("")
    end
  end

  def test_method_chat_kit_sessions_cancel
    client = build_client
    result = client.beta.chat_kit.sessions.cancel("session_id")
    refute_nil(result)
  end

  def test_path_params_chat_kit_sessions_cancel
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.chat_kit.sessions.cancel("")
    end
  end

  def test_method_chat_kit_sessions_create
    client = build_client
    result = client.beta.chat_kit.sessions.create(workflow: { "id" => "x" }, user: "x")
    refute_nil(result)
  end

  def test_method_chat_kit_sessions_create_with_all_params
    client = build_client
    result = client.beta.chat_kit.sessions.create(workflow: { "id" => "x", "version" => "x", "state_variables" => { "key" => "x" }, "tracing" => { "enabled" => true } }, user: "x", expires_after: { "anchor" => "created_at", "seconds" => 0 }, rate_limits: { "max_requests_per_1_minute" => 0 }, chatkit_configuration: { "automatic_thread_titling" => { "enabled" => true }, "file_upload" => { "enabled" => true, "max_file_size" => 0, "max_files" => 0 }, "history" => { "enabled" => true, "recent_threads" => 0 } })
    refute_nil(result)
  end

  def test_method_chat_kit_threads_delete
    client = build_client
    result = client.beta.chat_kit.threads.delete("thread_id")
    refute_nil(result)
  end

  def test_path_params_chat_kit_threads_delete
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.chat_kit.threads.delete("")
    end
  end

  def test_method_chat_kit_threads_list
    client = build_client
    result = client.beta.chat_kit.threads.list
    assert_instance_of(Openai::Page, result)
  end

  def test_method_chat_kit_threads_list_with_all_params
    client = build_client
    result = client.beta.chat_kit.threads.list(limit: 0, order: "asc", after: "after", before: "before", user: "user")
    assert_instance_of(Openai::Page, result)
  end

  def test_method_chat_kit_threads_retrieve
    client = build_client
    result = client.beta.chat_kit.threads.retrieve("thread_id")
    refute_nil(result)
  end

  def test_path_params_chat_kit_threads_retrieve
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.chat_kit.threads.retrieve("")
    end
  end

  def test_method_chat_kit_threads_items_list
    client = build_client
    result = client.beta.chat_kit.threads.items.list("thread_id")
    assert_instance_of(Openai::Page, result)
  end

  def test_method_chat_kit_threads_items_list_with_all_params
    client = build_client
    result = client.beta.chat_kit.threads.items.list("thread_id", limit: 0, order: "asc", after: "after", before: "before")
    assert_instance_of(Openai::Page, result)
  end

  def test_path_params_chat_kit_threads_items_list
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.chat_kit.threads.items.list("")
    end
  end

  def test_method_threads_create
    client = build_client
    result = client.beta.threads.create
    refute_nil(result)
  end

  def test_method_threads_create_with_all_params
    client = build_client
    result = client.beta.threads.create(messages: [{ "role" => "user", "content" => "x", "attachments" => [{ "file_id" => "x", "tools" => [{ "type" => nil }] }], "metadata" => { "key" => "x" } }], tool_resources: { "code_interpreter" => { "file_ids" => ["x"] }, "file_search" => nil }, metadata: { "key" => "x" })
    refute_nil(result)
  end

  def test_method_threads_delete
    client = build_client
    result = client.beta.threads.delete("thread_id")
    refute_nil(result)
  end

  def test_path_params_threads_delete
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.threads.delete("")
    end
  end

  def test_method_threads_new_and_run
    client = build_client
    result = client.beta.threads.new_and_run(assistant_id: "x")
    refute_nil(result)
  end

  def test_method_threads_new_and_run_with_all_params
    client = build_client
    result = client.beta.threads.new_and_run(assistant_id: "x", thread: { "messages" => [{ "role" => "user", "content" => "x", "attachments" => [{ "file_id" => "x", "tools" => [nil] }], "metadata" => { "key" => "x" } }], "tool_resources" => { "code_interpreter" => { "file_ids" => ["x"] }, "file_search" => nil }, "metadata" => { "key" => "x" } }, model: "x", instructions: "x", tools: [{ "type" => "code_interpreter" }], tool_resources: { "code_interpreter" => { "file_ids" => ["x"] }, "file_search" => { "vector_store_ids" => ["x"] } }, metadata: { "key" => "x" }, temperature: 0, top_p: 0, stream: true, max_prompt_tokens: 0, max_completion_tokens: 0, truncation_strategy: { "type" => "auto", "last_messages" => 0 }, tool_choice: "none", parallel_tool_calls: true, response_format: "auto")
    refute_nil(result)
  end

  def test_method_threads_retrieve
    client = build_client
    result = client.beta.threads.retrieve("thread_id")
    refute_nil(result)
  end

  def test_path_params_threads_retrieve
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.threads.retrieve("")
    end
  end

  def test_method_threads_update
    client = build_client
    result = client.beta.threads.update("thread_id")
    refute_nil(result)
  end

  def test_method_threads_update_with_all_params
    client = build_client
    result = client.beta.threads.update("thread_id", tool_resources: { "code_interpreter" => { "file_ids" => ["x"] }, "file_search" => { "vector_store_ids" => ["x"] } }, metadata: { "key" => "x" })
    refute_nil(result)
  end

  def test_path_params_threads_update
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.threads.update("")
    end
  end

  def test_method_threads_messages_create
    client = build_client
    result = client.beta.threads.messages.create("thread_id", role: "user", content: "x")
    refute_nil(result)
  end

  def test_method_threads_messages_create_with_all_params
    client = build_client
    result = client.beta.threads.messages.create("thread_id", role: "user", content: "x", attachments: [{ "file_id" => "x", "tools" => [{ "type" => "code_interpreter" }] }], metadata: { "key" => "x" })
    refute_nil(result)
  end

  def test_path_params_threads_messages_create
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.threads.messages.create("", role: "user", content: "x")
    end
  end

  def test_method_threads_messages_delete
    client = build_client
    result = client.beta.threads.messages.delete("thread_id", "message_id")
    refute_nil(result)
  end

  def test_path_params_threads_messages_delete
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.threads.messages.delete("", "message_id")
    end
  end

  def test_method_threads_messages_list
    client = build_client
    result = client.beta.threads.messages.list("thread_id")
    assert_instance_of(Openai::Page, result)
  end

  def test_method_threads_messages_list_with_all_params
    client = build_client
    result = client.beta.threads.messages.list("thread_id", limit: 0, order: "asc", after: "after", before: "before", run_id: "run_id")
    assert_instance_of(Openai::Page, result)
  end

  def test_path_params_threads_messages_list
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.threads.messages.list("")
    end
  end

  def test_method_threads_messages_retrieve
    client = build_client
    result = client.beta.threads.messages.retrieve("thread_id", "message_id")
    refute_nil(result)
  end

  def test_path_params_threads_messages_retrieve
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.threads.messages.retrieve("", "message_id")
    end
  end

  def test_method_threads_messages_update
    client = build_client
    result = client.beta.threads.messages.update("thread_id", "message_id")
    refute_nil(result)
  end

  def test_method_threads_messages_update_with_all_params
    client = build_client
    result = client.beta.threads.messages.update("thread_id", "message_id", metadata: { "key" => "x" })
    refute_nil(result)
  end

  def test_path_params_threads_messages_update
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.threads.messages.update("", "message_id")
    end
  end

  def test_method_threads_runs_cancel
    client = build_client
    result = client.beta.threads.runs.cancel("thread_id", "run_id")
    refute_nil(result)
  end

  def test_path_params_threads_runs_cancel
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.threads.runs.cancel("", "run_id")
    end
  end

  def test_method_threads_runs_create
    client = build_client
    result = client.beta.threads.runs.create("thread_id", assistant_id: "x")
    refute_nil(result)
  end

  def test_method_threads_runs_create_with_all_params
    client = build_client
    result = client.beta.threads.runs.create("thread_id", assistant_id: "x", include: ["step_details.tool_calls[*].file_search.results[*].content"], model: "x", reasoning_effort: "none", instructions: "x", additional_instructions: "x", additional_messages: [{ "role" => "user", "content" => "x", "attachments" => [{ "file_id" => "x", "tools" => [{ "type" => nil }] }], "metadata" => { "key" => "x" } }], tools: [{ "type" => "code_interpreter" }], metadata: { "key" => "x" }, temperature: 0, top_p: 0, stream: true, max_prompt_tokens: 0, max_completion_tokens: 0, truncation_strategy: { "type" => "auto", "last_messages" => 0 }, tool_choice: "none", parallel_tool_calls: true, response_format: "auto")
    refute_nil(result)
  end

  def test_path_params_threads_runs_create
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.threads.runs.create("", assistant_id: "x")
    end
  end

  def test_method_threads_runs_list
    client = build_client
    result = client.beta.threads.runs.list("thread_id")
    assert_instance_of(Openai::Page, result)
  end

  def test_method_threads_runs_list_with_all_params
    client = build_client
    result = client.beta.threads.runs.list("thread_id", limit: 0, order: "asc", after: "after", before: "before")
    assert_instance_of(Openai::Page, result)
  end

  def test_path_params_threads_runs_list
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.threads.runs.list("")
    end
  end

  def test_method_threads_runs_retrieve
    client = build_client
    result = client.beta.threads.runs.retrieve("thread_id", "run_id")
    refute_nil(result)
  end

  def test_path_params_threads_runs_retrieve
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.threads.runs.retrieve("", "run_id")
    end
  end

  def test_method_threads_runs_update
    client = build_client
    result = client.beta.threads.runs.update("thread_id", "run_id")
    refute_nil(result)
  end

  def test_method_threads_runs_update_with_all_params
    client = build_client
    result = client.beta.threads.runs.update("thread_id", "run_id", metadata: { "key" => "x" })
    refute_nil(result)
  end

  def test_path_params_threads_runs_update
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.threads.runs.update("", "run_id")
    end
  end

  def test_method_threads_runs_steps_list
    client = build_client
    result = client.beta.threads.runs.steps.list("thread_id", "run_id")
    assert_instance_of(Openai::Page, result)
  end

  def test_method_threads_runs_steps_list_with_all_params
    client = build_client
    result = client.beta.threads.runs.steps.list("thread_id", "run_id", limit: 0, order: "asc", after: "after", before: "before", include: ["step_details.tool_calls[*].file_search.results[*].content"])
    assert_instance_of(Openai::Page, result)
  end

  def test_path_params_threads_runs_steps_list
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.threads.runs.steps.list("", "run_id")
    end
  end

  def test_method_threads_runs_steps_retrieve
    client = build_client
    result = client.beta.threads.runs.steps.retrieve("thread_id", "run_id", "step_id")
    refute_nil(result)
  end

  def test_method_threads_runs_steps_retrieve_with_all_params
    client = build_client
    result = client.beta.threads.runs.steps.retrieve("thread_id", "run_id", "step_id", include: ["step_details.tool_calls[*].file_search.results[*].content"])
    refute_nil(result)
  end

  def test_path_params_threads_runs_steps_retrieve
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.threads.runs.steps.retrieve("", "run_id", "step_id")
    end
  end

  def test_method_threads_runs_submit_tool_outputs_create
    client = build_client
    result = client.beta.threads.runs.submit_tool_outputs.create("thread_id", "run_id", tool_outputs: [{}])
    refute_nil(result)
  end

  def test_method_threads_runs_submit_tool_outputs_create_with_all_params
    client = build_client
    result = client.beta.threads.runs.submit_tool_outputs.create("thread_id", "run_id", tool_outputs: [{ "tool_call_id" => "x", "output" => "x" }], stream: true)
    refute_nil(result)
  end

  def test_path_params_threads_runs_submit_tool_outputs_create
    client = build_client
    assert_raises(ArgumentError) do
      client.beta.threads.runs.submit_tool_outputs.create("", "run_id", tool_outputs: [{}])
    end
  end
end
