// Code generated by opensdk. DO NOT EDIT.

use std::sync::Arc;

use crate::error::Error;
use crate::models::*;
use crate::transport::{Page, Transport};

pub struct Containers {
    transport: Arc<Transport>,
}

impl Containers {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        Containers { transport }
    }

    pub fn files(&self) -> ContainersFiles {
        ContainersFiles::new(self.transport.clone())
    }
}

pub struct ContainersFiles {
    transport: Arc<Transport>,
}

impl ContainersFiles {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        ContainersFiles { transport }
    }

    /// Lists container files.
    pub async fn list(&self, container_id: &str, params: ContainersFilesListParams) -> Result<Page<ContainerFileResource>, Error> {
        if container_id.is_empty() {
            return Err(Error::InvalidArgument("container_id".to_string()));
        }

        let mut req = self.transport.request(reqwest::Method::GET, format!("/containers/{}/files", container_id));
        if let Some(value) = &params.limit {
            req = req.query("limit", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.order {
            req = req.query("order", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.after {
            req = req.query("after", serde_json::to_value(value)?);
        }
        let value = req.send_value().await?;
        Page::from_value(value, "data", Some("has_more"))
    }
}

#[derive(Debug, Clone, Default)]
pub struct ContainersFilesListParams {
    /// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 20.
    pub limit: Option<i64>,
    /// Sort order by the `created_at` timestamp of the objects. `asc` for ascending order and `desc` for descending order.
    pub order: Option<ContainersFilesListOrder>,
    /// A cursor for use in pagination. `after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with obj_foo, your subsequent call can include after=obj_foo in order to fetch the next page of the list.
    pub after: Option<String>,
}
