# Code generated by opensdk. DO NOT EDIT.

from __future__ import annotations

from tests.utils import assert_matches_type
from openai import Client
from openai.models import *  # noqa: F401,F403


class TestEmbeddings:
    def test_method_create(self, client: Client) -> None:
        result = client.embeddings.create(input="x", model="x")
        assert_matches_type(CreateEmbeddingResponse, result, path=["response"])

    def test_method_create_with_all_params(self, client: Client) -> None:
        result = client.embeddings.create(input="x", model="x", encoding_format="float", dimensions=0, user="x")
        assert_matches_type(CreateEmbeddingResponse, result, path=["response"])
