// Code generated by opensdk. DO NOT EDIT.

import { APIResource } from '../core/resource';
import type { RequestOptions } from '../core/request';
import type { ContainerResource, CreateContainerBodyExpiresAfter, CreateContainerBodyMemoryLimit, CreateContainerBodyNetworkPolicy, CreateContainerBodySkillsItem } from '../models';

export class Containers extends APIResource {
  /** Creates a container. */
  create(body?: ContainerCreateParams, options?: RequestOptions): Promise<ContainerResource> {
    return this._client.request<ContainerResource>({ method: "POST", path: "/containers", body }, options);
  }
}

export interface ContainerCreateParams {
  name: string;
  file_ids?: string[];
  expires_after?: CreateContainerBodyExpiresAfter;
  skills?: CreateContainerBodySkillsItem[];
  memory_limit?: CreateContainerBodyMemoryLimit;
  network_policy?: CreateContainerBodyNetworkPolicy;
}
