// Code generated by opensdk. DO NOT EDIT.

package openai

import (
	"context"
	"errors"
	"fmt"
	"net/http"

	"github.com/example/openai/internal/requestconfig"
	"github.com/example/openai/option"
	"github.com/example/openai/packages/apijson"
	"github.com/example/openai/packages/pagination"
)

// FineTuningService ...
type FineTuningService struct {
	Options []option.RequestOption
	Checkpoints FineTuningCheckpointService
}

// NewFineTuningService constructs a service that shares the client's request options.
func NewFineTuningService(opts ...option.RequestOption) (r FineTuningService) {
	r = FineTuningService{}
	r.Options = opts
	r.Checkpoints = NewFineTuningCheckpointService(opts...)
	return
}

// FineTuningCheckpointService ...
type FineTuningCheckpointService struct {
	Options []option.RequestOption
	Permissions FineTuningCheckpointPermissionService
}

// NewFineTuningCheckpointService constructs a service that shares the client's request options.
func NewFineTuningCheckpointService(opts ...option.RequestOption) (r FineTuningCheckpointService) {
	r = FineTuningCheckpointService{}
	r.Options = opts
	r.Permissions = NewFineTuningCheckpointPermissionService(opts...)
	return
}

// FineTuningCheckpointPermissionService ...
type FineTuningCheckpointPermissionService struct {
	Options []option.RequestOption
}

// NewFineTuningCheckpointPermissionService constructs a service that shares the client's request options.
func NewFineTuningCheckpointPermissionService(opts ...option.RequestOption) (r FineTuningCheckpointPermissionService) {
	r = FineTuningCheckpointPermissionService{}
	r.Options = opts
	return
}

// **NOTE:** Calling this endpoint requires an [admin API key](../admin-api-keys).
//
// This enables organization owners to share fine-tuned models with other projects in their organization.
func (r *FineTuningCheckpointPermissionService) New(ctx context.Context, fineTunedModelCheckpoint string, body FineTuningCheckpointPermissionNewParams, opts ...option.RequestOption) (res *pagination.CursorPage[FineTuningCheckpointPermission], err error) {
	opts = append(r.Options[:], opts...)
	if fineTunedModelCheckpoint == "" {
		err = errors.New("missing required fine_tuned_model_checkpoint parameter")
		return
	}
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodPost, fmt.Sprintf("fine_tuning/checkpoints/%v/permissions", fineTunedModelCheckpoint), body, opts...)
	if err != nil {
		return
	}
	res = &pagination.CursorPage[FineTuningCheckpointPermission]{}
	err = cfg.Execute(res)
	return
}

type FineTuningCheckpointPermissionNewParams struct {
	ProjectIds []string `json:"project_ids,required"`
}

func (r FineTuningCheckpointPermissionNewParams) MarshalJSON() ([]byte, error) {
	return apijson.MarshalRoot(r)
}
