openapi: 3.0.0

info:
  title: Sample API

servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server

paths:
  /users:
    get:
      summary: Returns a list of users
      description: Optional extended description in CommonMark or HTML.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: array
                  items:
                    $ref: "#/components/schemas/Status"
      responses:
        '200':
          description: A JSON array of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
              examples:
                json:
                  summary: A sample JSON response
                  value: {
                    id: 1,
                    username: 'John Doe',
                  }
components:
  schemas:
    User:
      type: object
      required:
        - id
        - username
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
          format: email
        status:
          type: string
          enum: [ active, inactive ]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Status:
      type: string
      enum:
        - active
        - inactive

