// Code generated by opensdk. DO NOT EDIT.

use std::sync::Arc;

use crate::error::Error;
use crate::runner::{CommandResult, Runner};

pub struct Projects {
    runner: Arc<Runner>,
}

impl Projects {
    pub(crate) fn new(runner: Arc<Runner>) -> Self {
        Projects { runner }
    }

    /// List projects
    ///
    /// Runs `acme projects list`.
    pub async fn list(&self) -> Result<CommandResult, Error> {
        let mut argv: Vec<String> = vec!["projects".to_string(), "list".to_string()];
        self.runner.run(argv).await
    }
}
