// Code generated by opensdk. DO NOT EDIT.

import { APIResource } from '../core/resource';
import type { APIClient, RequestOptions } from '../core/request';
import type { Certificate } from '../models';

export class Admin extends APIResource {
  readonly organization: AdminOrganization;

  constructor(client: APIClient) {
    super(client);
    this.organization = new AdminOrganization(client);
  }
}

export class AdminOrganization extends APIResource {
  readonly certificates: AdminOrganizationCertificates;

  constructor(client: APIClient) {
    super(client);
    this.certificates = new AdminOrganizationCertificates(client);
  }
}

export class AdminOrganizationCertificates extends APIResource {
  /**
   * Upload a certificate to the organization. This does **not** automatically activate the certificate.
   *
   * Organizations can upload up to 50 certificates.
   */
  create(body: AdminOrganizationCertificateCreateParams, options?: RequestOptions): Promise<Certificate> {
    return this._client.request<Certificate>({ method: "POST", path: "/organization/certificates", body }, options);
  }
}

export interface AdminOrganizationCertificateCreateParams {
  name?: string;
  certificate: string;
}
