// <auto-generated>
//     Code generated by opensdk. DO NOT EDIT.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace Example.Openai;

public sealed class ChatService
{
    private readonly Transport _transport;
    public ChatCompletionsService Completions { get; }

    internal ChatService(Transport transport)
    {
        _transport = transport;
        Completions = new ChatCompletionsService(transport);
    }
}

public sealed class ChatCompletionsService
{
    private readonly Transport _transport;
    public ChatCompletionsMessagesService Messages { get; }

    internal ChatCompletionsService(Transport transport)
    {
        _transport = transport;
        Messages = new ChatCompletionsMessagesService(transport);
    }

    /// <summary>
    /// **Starting a new project?** We recommend trying [Responses](/docs/api-reference/responses)
    /// to take advantage of the latest OpenAI platform features. Compare
    /// [Chat Completions with Responses](/docs/guides/responses-vs-chat-completions?api-mode=responses).
    /// ---
    /// Creates a model response for the given chat conversation. Learn more in the
    /// [text generation](/docs/guides/text-generation), [vision](/docs/guides/vision),
    /// and [audio](/docs/guides/audio) guides.
    /// Parameter support can differ depending on the model used to generate the
    /// response, particularly for newer reasoning models. Parameters that are only
    /// supported for reasoning models are noted below. For the current state of
    /// unsupported parameters in reasoning models,
    /// [refer to the reasoning guide](/docs/guides/reasoning).
    /// Returns a chat completion object, or a streamed sequence of chat completion
    /// chunk objects if the request is streamed.
    /// </summary>
    public async Task<CreateChatCompletionResponse> Create(CreateChatCompletionRequest body, CancellationToken cancellationToken = default)
    {
        return await _transport.RequestAsync<CreateChatCompletionResponse>(HttpMethod.Post, "/chat/completions", body: body, cancellationToken: cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Delete a stored chat completion. Only Chat Completions that have been
    /// created with the `store` parameter set to `true` can be deleted.
    /// </summary>
    public async Task<ChatCompletionDeleted> Delete(string completionId, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrEmpty(completionId))
        {
            throw new ArgumentException("Expected a non-empty value for completionId.", nameof(completionId));
        }
        return await _transport.RequestAsync<ChatCompletionDeleted>(HttpMethod.Delete, $"/chat/completions/{completionId}", cancellationToken: cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// List stored Chat Completions. Only Chat Completions that have been stored
    /// with the `store` parameter set to `true` will be returned.
    /// </summary>
    public async Task<CursorPage<CreateChatCompletionResponse>> List(string? model = null, Dictionary<string, string>? metadata = null, string? after = null, long? limit = null, ChatCompletionsListOrder? order = null, CancellationToken cancellationToken = default)
    {
        var query = new Dictionary<string, object?>
        {
            ["model"] = model,
            ["metadata"] = Transport.JsonQuery(metadata),
            ["after"] = after,
            ["limit"] = limit,
            ["order"] = order,
        };
        return await _transport.RequestAsync<CursorPage<CreateChatCompletionResponse>>(HttpMethod.Get, "/chat/completions", query: query, cancellationToken: cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Get a stored chat completion. Only Chat Completions that have been created
    /// with the `store` parameter set to `true` will be returned.
    /// </summary>
    public async Task<CreateChatCompletionResponse> Retrieve(string completionId, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrEmpty(completionId))
        {
            throw new ArgumentException("Expected a non-empty value for completionId.", nameof(completionId));
        }
        return await _transport.RequestAsync<CreateChatCompletionResponse>(HttpMethod.Get, $"/chat/completions/{completionId}", cancellationToken: cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Modify a stored chat completion. Only Chat Completions that have been
    /// created with the `store` parameter set to `true` can be modified. Currently,
    /// the only supported modification is to update the `metadata` field.
    /// </summary>
    public async Task<CreateChatCompletionResponse> Update(string completionId, ChatCompletionsUpdateRequest body, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrEmpty(completionId))
        {
            throw new ArgumentException("Expected a non-empty value for completionId.", nameof(completionId));
        }
        return await _transport.RequestAsync<CreateChatCompletionResponse>(HttpMethod.Post, $"/chat/completions/{completionId}", body: body, cancellationToken: cancellationToken).ConfigureAwait(false);
    }
}

public sealed class ChatCompletionsMessagesService
{
    private readonly Transport _transport;

    internal ChatCompletionsMessagesService(Transport transport)
    {
        _transport = transport;
    }

    /// <summary>
    /// Get the messages in a stored chat completion. Only Chat Completions that
    /// have been created with the `store` parameter set to `true` will be
    /// returned.
    /// </summary>
    public async Task<CursorPage<ChatCompletionMessageListDataItem>> List(string completionId, string? after = null, long? limit = null, ChatCompletionsMessagesListOrder? order = null, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrEmpty(completionId))
        {
            throw new ArgumentException("Expected a non-empty value for completionId.", nameof(completionId));
        }
        var query = new Dictionary<string, object?>
        {
            ["after"] = after,
            ["limit"] = limit,
            ["order"] = order,
        };
        return await _transport.RequestAsync<CursorPage<ChatCompletionMessageListDataItem>>(HttpMethod.Get, $"/chat/completions/{completionId}/messages", query: query, cancellationToken: cancellationToken).ConfigureAwait(false);
    }
}
