// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.Optional;

/** Parameters for list: Returns a list of API keys in the project. */
public final class AdminOrganizationProjectApiKeyListParams {
  private final Long limit;
  private final String after;

  private AdminOrganizationProjectApiKeyListParams(Builder builder) {
    this.limit = builder.limit;
    this.after = builder.after;
  }

  public static Builder builder() {
    return new Builder();
  }

  public Optional<Long> limit() {
    return Optional.ofNullable(limit);
  }

  public Optional<String> after() {
    return Optional.ofNullable(after);
  }

  public static final class Builder {
    private Long limit;
    private String after;

    public Builder limit(Long limit) {
      this.limit = limit;
      return this;
    }

    public Builder after(String after) {
      this.after = after;
      return this;
    }

    public AdminOrganizationProjectApiKeyListParams build() {
      return new AdminOrganizationProjectApiKeyListParams(this);
    }
  }
}
