// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

public enum ApplyPatchCallOutputStatus implements Json.JsonEnum {
  COMPLETED("completed"),
  FAILED("failed");

  private final String value;

  ApplyPatchCallOutputStatus(String value) {
    this.value = value;
  }

  public String value() {
    return value;
  }

  @Override
  public Object jsonValue() {
    return value;
  }

  public static ApplyPatchCallOutputStatus fromValue(String value) {
    for (ApplyPatchCallOutputStatus item : values()) {
      if (item.value.equals(value)) {
        return item;
      }
    }
    throw new IllegalArgumentException("unknown ApplyPatchCallOutputStatus value: " + value);
  }

  public static ApplyPatchCallOutputStatus fromJson(Object json) {
    return json == null ? null : fromValue(Json.asString(json));
  }
}
