// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

/** Instruction describing how to create a file via the apply_patch tool. */
public final class ApplyPatchCreateFileOperation implements Json.JsonSerializable {
  private String type;
  private String path;
  private String diff;

  public String type() {
    return type;
  }

  public String path() {
    return path;
  }

  public String diff() {
    return diff;
  }

  public static ApplyPatchCreateFileOperation fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    ApplyPatchCreateFileOperation out = new ApplyPatchCreateFileOperation();
    out.type = Json.asString(map.get("type"));
    out.path = Json.asString(map.get("path"));
    out.diff = Json.asString(map.get("diff"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("type", type != null ? type : "create_file");
    map.put("path", path);
    map.put("diff", diff);
    return map;
  }
}
