// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

/** The API Key used to perform the audit logged action. */
public final class AuditLogActorApiKey implements Json.JsonSerializable {
  private String id;
  private AuditLogActorApiKeyType type;
  private AuditLogActorUser user;
  private AuditLogActorServiceAccount serviceAccount;

  public String id() {
    return id;
  }

  public AuditLogActorApiKeyType type() {
    return type;
  }

  public AuditLogActorUser user() {
    return user;
  }

  public AuditLogActorServiceAccount serviceAccount() {
    return serviceAccount;
  }

  public static AuditLogActorApiKey fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    AuditLogActorApiKey out = new AuditLogActorApiKey();
    out.id = Json.asString(map.get("id"));
    out.type = AuditLogActorApiKeyType.fromJson(map.get("type"));
    out.user = AuditLogActorUser.fromJson(map.get("user"));
    out.serviceAccount = AuditLogActorServiceAccount.fromJson(map.get("service_account"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    if (id != null) {
      map.put("id", id);
    }
    if (type != null) {
      map.put("type", type);
    }
    if (user != null) {
      map.put("user", user);
    }
    if (serviceAccount != null) {
      map.put("service_account", serviceAccount);
    }
    return map;
  }
}
