// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

public final class BetaThreadRunStepService {
  private final Transport transport;

  BetaThreadRunStepService(Transport transport) {
    this.transport = transport;
  }

  /** Returns a list of run steps belonging to a run. */
  public CursorPage<RunStepObject> list(String threadId, String runId, BetaThreadRunStepListParams params) {
    if (threadId == null || threadId.isEmpty()) {
      throw new IllegalArgumentException("missing required thread_id parameter");
    }
    if (runId == null || runId.isEmpty()) {
      throw new IllegalArgumentException("missing required run_id parameter");
    }
    Transport.Request request = new Transport.Request("GET", "/threads/" + Transport.encodePath(threadId) + "/runs/" + Transport.encodePath(runId) + "/steps");
    params.limit().ifPresent(value -> request.query("limit", String.valueOf(value)));
    params.order().ifPresent(value -> request.query("order", String.valueOf(value)));
    params.after().ifPresent(value -> request.query("after", String.valueOf(value)));
    params.before().ifPresent(value -> request.query("before", String.valueOf(value)));
    params.include().ifPresent(values -> {
      for (Object value : values) {
        request.query("include[]", String.valueOf(value));
      }
    });
    return CursorPage.fromJson(transport.execute(request), __e -> RunStepObject.fromJson(__e));
  }

  /** Retrieves a run step. */
  public RunStepObject retrieve(String threadId, String runId, String stepId, BetaThreadRunStepRetrieveParams params) {
    if (threadId == null || threadId.isEmpty()) {
      throw new IllegalArgumentException("missing required thread_id parameter");
    }
    if (runId == null || runId.isEmpty()) {
      throw new IllegalArgumentException("missing required run_id parameter");
    }
    if (stepId == null || stepId.isEmpty()) {
      throw new IllegalArgumentException("missing required step_id parameter");
    }
    Transport.Request request = new Transport.Request("GET", "/threads/" + Transport.encodePath(threadId) + "/runs/" + Transport.encodePath(runId) + "/steps/" + Transport.encodePath(stepId));
    params.include().ifPresent(values -> {
      for (Object value : values) {
        request.query("include[]", String.valueOf(value));
      }
    });
    return RunStepObject.fromJson(transport.execute(request));
  }
}
