// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

public enum ClickButtonType implements Json.JsonEnum {
  LEFT("left"),
  RIGHT("right"),
  WHEEL("wheel"),
  BACK("back"),
  FORWARD("forward");

  private final String value;

  ClickButtonType(String value) {
    this.value = value;
  }

  public String value() {
    return value;
  }

  @Override
  public Object jsonValue() {
    return value;
  }

  public static ClickButtonType fromValue(String value) {
    for (ClickButtonType item : values()) {
      if (item.value.equals(value)) {
        return item;
      }
    }
    throw new IllegalArgumentException("unknown ClickButtonType value: " + value);
  }

  public static ClickButtonType fromJson(Object json) {
    return json == null ? null : fromValue(Json.asString(json));
  }
}
