// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

/** The logs output from the code interpreter. */
public final class CodeInterpreterOutputLogs implements Json.JsonSerializable {
  private String type;
  private String logs;

  public String type() {
    return type;
  }

  public String logs() {
    return logs;
  }

  public static CodeInterpreterOutputLogs fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    CodeInterpreterOutputLogs out = new CodeInterpreterOutputLogs();
    out.type = Json.asString(map.get("type"));
    out.logs = Json.asString(map.get("logs"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("type", type != null ? type : "logs");
    map.put("logs", logs);
    return map;
  }
}
