// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public final class ConversationsItemsCreateRequest implements Json.JsonSerializable {
  private List<Object> items;

  public List<Object> items() {
    return items;
  }

  public static ConversationsItemsCreateRequest fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    ConversationsItemsCreateRequest out = new ConversationsItemsCreateRequest();
    out.items = Json.mapList(map.get("items"), __e -> InputItem.fromJson(__e));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("items", items);
    return map;
  }
}
