// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** A list of Conversation items. */
public final class ConversationItemList implements Json.JsonSerializable {
  private String object;
  private List<Object> data;
  private Boolean hasMore;
  private String firstId;
  private String lastId;

  public String object() {
    return object;
  }

  public List<Object> data() {
    return data;
  }

  public Boolean hasMore() {
    return hasMore;
  }

  public String firstId() {
    return firstId;
  }

  public String lastId() {
    return lastId;
  }

  public static ConversationItemList fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    ConversationItemList out = new ConversationItemList();
    out.object = Json.asString(map.get("object"));
    out.data = Json.mapList(map.get("data"), __e -> ConversationItem.fromJson(__e));
    out.hasMore = Json.asBoolean(map.get("has_more"));
    out.firstId = Json.asString(map.get("first_id"));
    out.lastId = Json.asString(map.get("last_id"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("object", object != null ? object : "list");
    map.put("data", data);
    map.put("has_more", hasMore);
    map.put("first_id", firstId);
    map.put("last_id", lastId);
    return map;
  }
}
