// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public final class CreateMessageRequest implements Json.JsonSerializable {
  private CreateMessageRequestRole role;
  private Object content;
  private List<CreateMessageRequestAttachmentsItem> attachments;
  private Map<String, String> metadata;

  public CreateMessageRequestRole role() {
    return role;
  }

  public Object content() {
    return content;
  }

  public List<CreateMessageRequestAttachmentsItem> attachments() {
    return attachments;
  }

  public Map<String, String> metadata() {
    return metadata;
  }

  public static CreateMessageRequest fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    CreateMessageRequest out = new CreateMessageRequest();
    out.role = CreateMessageRequestRole.fromJson(map.get("role"));
    out.content = map.get("content");
    out.attachments = Json.mapList(map.get("attachments"), __e -> CreateMessageRequestAttachmentsItem.fromJson(__e));
    out.metadata = Json.mapValues(map.get("metadata"), __e -> Json.asString(__e));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("role", role);
    map.put("content", content);
    if (attachments != null) {
      map.put("attachments", attachments);
    }
    if (metadata != null) {
      map.put("metadata", metadata);
    }
    return map;
  }
}
