// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

public enum CreateFineTuningJobRequestModelString implements Json.JsonEnum {
  BABBAGE_002("babbage-002"),
  DAVINCI_002("davinci-002"),
  GPT_3_5_TURBO("gpt-3.5-turbo"),
  GPT_4O_MINI("gpt-4o-mini");

  private final String value;

  CreateFineTuningJobRequestModelString(String value) {
    this.value = value;
  }

  public String value() {
    return value;
  }

  @Override
  public Object jsonValue() {
    return value;
  }

  public static CreateFineTuningJobRequestModelString fromValue(String value) {
    for (CreateFineTuningJobRequestModelString item : values()) {
      if (item.value.equals(value)) {
        return item;
      }
    }
    throw new IllegalArgumentException("unknown CreateFineTuningJobRequestModelString value: " + value);
  }

  public static CreateFineTuningJobRequestModelString fromJson(Object json) {
    return json == null ? null : fromValue(Json.asString(json));
  }
}
