// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public final class CreateFineTuningCheckpointPermissionRequest implements Json.JsonSerializable {
  private List<String> projectIds;

  public List<String> projectIds() {
    return projectIds;
  }

  public static CreateFineTuningCheckpointPermissionRequest fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    CreateFineTuningCheckpointPermissionRequest out = new CreateFineTuningCheckpointPermissionRequest();
    out.projectIds = Json.mapList(map.get("project_ids"), __e -> Json.asString(__e));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("project_ids", projectIds);
    return map;
  }
}
