// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

/** Your chosen grammar. */
public final class CustomToolChatCompletionsCustomFormatGrammarGrammar implements Json.JsonSerializable {
  private String definition;
  private CustomToolChatCompletionsCustomFormatGrammarGrammarSyntax syntax;

  public String definition() {
    return definition;
  }

  public CustomToolChatCompletionsCustomFormatGrammarGrammarSyntax syntax() {
    return syntax;
  }

  public static CustomToolChatCompletionsCustomFormatGrammarGrammar fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    CustomToolChatCompletionsCustomFormatGrammarGrammar out = new CustomToolChatCompletionsCustomFormatGrammarGrammar();
    out.definition = Json.asString(map.get("definition"));
    out.syntax = CustomToolChatCompletionsCustomFormatGrammarGrammarSyntax.fromJson(map.get("syntax"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("definition", definition);
    map.put("syntax", syntax);
    return map;
  }
}
