// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

/** The type of method. Is either `supervised`, `dpo`, or `reinforcement`. */
public enum FineTuneMethodType implements Json.JsonEnum {
  SUPERVISED("supervised"),
  DPO("dpo"),
  REINFORCEMENT("reinforcement");

  private final String value;

  FineTuneMethodType(String value) {
    this.value = value;
  }

  public String value() {
    return value;
  }

  @Override
  public Object jsonValue() {
    return value;
  }

  public static FineTuneMethodType fromValue(String value) {
    for (FineTuneMethodType item : values()) {
      if (item.value.equals(value)) {
        return item;
      }
    }
    throw new IllegalArgumentException("unknown FineTuneMethodType value: " + value);
  }

  public static FineTuneMethodType fromJson(Object json) {
    return json == null ? null : fromValue(Json.asString(json));
  }
}
