// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

/** Parameters for create: Validate a grader. */
public final class FineTuningAlphaGraderValidateCreateParams {
  private final Object grader;

  private FineTuningAlphaGraderValidateCreateParams(Builder builder) {
    this.grader = builder.grader;
  }

  public static Builder builder() {
    return new Builder();
  }

  public Object grader() {
    return grader;
  }

  public static final class Builder {
    private Object grader;

    public Builder grader(Object grader) {
      this.grader = grader;
      return this;
    }

    public FineTuningAlphaGraderValidateCreateParams build() {
      if (grader == null) {
        throw new IllegalStateException("grader is required");
      }
      return new FineTuningAlphaGraderValidateCreateParams(this);
    }
  }
}
