// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.Map;

/** Decode helper for the FunctionShellToolParamEnvironment union, selecting the concrete variant by its "type" discriminator. */
public final class FunctionShellToolParamEnvironment {
  private FunctionShellToolParamEnvironment() {
  }

  /**
   * Decode JSON into the concrete FunctionShellToolParamEnvironment variant selected by the "type"
   * discriminator. An unknown or absent discriminator keeps the raw parsed value.
   */
  public static Object fromJson(Object json) {
    if (!(json instanceof Map)) {
      return json;
    }
    Object discriminator = ((Map<?, ?>) json).get("type");
    if ("container_auto".equals(discriminator)) {
      return ContainerAutoParam.fromJson(json);
    }
    if ("container_reference".equals(discriminator)) {
      return ContainerReferenceParam.fromJson(json);
    }
    if ("local".equals(discriminator)) {
      return LocalEnvironmentParam.fromJson(json);
    }
    return json;
  }
}
