// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

public enum FunctionCallStatus implements Json.JsonEnum {
  IN_PROGRESS("in_progress"),
  COMPLETED("completed"),
  INCOMPLETE("incomplete");

  private final String value;

  FunctionCallStatus(String value) {
    this.value = value;
  }

  public String value() {
    return value;
  }

  @Override
  public Object jsonValue() {
    return value;
  }

  public static FunctionCallStatus fromValue(String value) {
    for (FunctionCallStatus item : values()) {
      if (item.value.equals(value)) {
        return item;
      }
    }
    throw new IllegalArgumentException("unknown FunctionCallStatus value: " + value);
  }

  public static FunctionCallStatus fromJson(Object json) {
    return json == null ? null : fromValue(Json.asString(json));
  }
}
