// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

/** The string check operation to perform. One of `eq`, `ne`, `like`, or `ilike`. */
public enum GraderStringCheckOperation implements Json.JsonEnum {
  EQ("eq"),
  NE("ne"),
  LIKE("like"),
  ILIKE("ilike");

  private final String value;

  GraderStringCheckOperation(String value) {
    this.value = value;
  }

  public String value() {
    return value;
  }

  @Override
  public Object jsonValue() {
    return value;
  }

  public static GraderStringCheckOperation fromValue(String value) {
    for (GraderStringCheckOperation item : values()) {
      if (item.value.equals(value)) {
        return item;
      }
    }
    throw new IllegalArgumentException("unknown GraderStringCheckOperation value: " + value);
  }

  public static GraderStringCheckOperation fromJson(Object json) {
    return json == null ? null : fromValue(Json.asString(json));
  }
}
