// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

/** The role of the message input. One of `user`, `system`, or `developer`. */
public enum InputMessageResourceRole implements Json.JsonEnum {
  USER("user"),
  SYSTEM("system"),
  DEVELOPER("developer");

  private final String value;

  InputMessageResourceRole(String value) {
    this.value = value;
  }

  public String value() {
    return value;
  }

  @Override
  public Object jsonValue() {
    return value;
  }

  public static InputMessageResourceRole fromValue(String value) {
    for (InputMessageResourceRole item : values()) {
      if (item.value.equals(value)) {
        return item;
      }
    }
    throw new IllegalArgumentException("unknown InputMessageResourceRole value: " + value);
  }

  public static InputMessageResourceRole fromJson(Object json) {
    return json == null ? null : fromValue(Json.asString(json));
  }
}
