// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public final class ModifyThreadRequestToolResourcesCodeInterpreter implements Json.JsonSerializable {
  private List<String> fileIds;

  public List<String> fileIds() {
    return fileIds;
  }

  public static ModifyThreadRequestToolResourcesCodeInterpreter fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    ModifyThreadRequestToolResourcesCodeInterpreter out = new ModifyThreadRequestToolResourcesCodeInterpreter();
    out.fileIds = Json.mapList(map.get("file_ids"), __e -> Json.asString(__e));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    if (fileIds != null) {
      map.put("file_ids", fileIds);
    }
    return map;
  }
}
