// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

public final class RealtimeTranscriptionSessionService {
  private final Transport transport;

  RealtimeTranscriptionSessionService(Transport transport) {
    this.transport = transport;
  }

  /**
   * Create an ephemeral API token for use in client-side applications with the
   * Realtime API specifically for realtime transcriptions.
   * Can be configured with the same session parameters as the `transcription_session.update` client event.
   * 
   * It responds with a session object, plus a `client_secret` key which contains
   * a usable ephemeral API token that can be used to authenticate browser clients
   * for the Realtime API.
   * 
   * Returns the created Realtime transcription session object, plus an ephemeral key.
   */
  public RealtimeTranscriptionSessionCreateResponse create(RealtimeTranscriptionSessionCreateParams params) {
    Transport.Request request = new Transport.Request("POST", "/realtime/transcription_sessions");
    Map<String, Object> body = new LinkedHashMap<>();
    params.turnDetection().ifPresent(value -> body.put("turn_detection", value));
    params.inputAudioNoiseReduction().ifPresent(value -> body.put("input_audio_noise_reduction", value));
    params.inputAudioFormat().ifPresent(value -> body.put("input_audio_format", value));
    params.inputAudioTranscription().ifPresent(value -> body.put("input_audio_transcription", value));
    params.include().ifPresent(value -> body.put("include", value));
    request.body(body);
    return RealtimeTranscriptionSessionCreateResponse.fromJson(transport.execute(request));
  }
}
