// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.List;
import java.util.Optional;

/**
 * Parameters for create: Create an ephemeral API token for use in client-side applications with the
 * Realtime API. Can be configured with the same session parameters as the
 * `session.update` client event.
 * 
 * It responds with a session object, plus a `client_secret` key which contains
 * a usable ephemeral API token that can be used to authenticate browser clients
 * for the Realtime API.
 * 
 * Returns the created Realtime session object, plus an ephemeral key.
 */
public final class RealtimeSessionCreateParams {
  private final RealtimeSessionCreateRequestClientSecret clientSecret;
  private final Object modalities;
  private final String instructions;
  private final Object voice;
  private final String inputAudioFormat;
  private final String outputAudioFormat;
  private final RealtimeSessionCreateRequestInputAudioTranscription inputAudioTranscription;
  private final Double speed;
  private final Object tracing;
  private final RealtimeSessionCreateRequestTurnDetection turnDetection;
  private final List<RealtimeSessionCreateRequestToolsItem> tools;
  private final String toolChoice;
  private final Double temperature;
  private final Object maxResponseOutputTokens;
  private final Object truncation;
  private final Prompt prompt;

  private RealtimeSessionCreateParams(Builder builder) {
    this.clientSecret = builder.clientSecret;
    this.modalities = builder.modalities;
    this.instructions = builder.instructions;
    this.voice = builder.voice;
    this.inputAudioFormat = builder.inputAudioFormat;
    this.outputAudioFormat = builder.outputAudioFormat;
    this.inputAudioTranscription = builder.inputAudioTranscription;
    this.speed = builder.speed;
    this.tracing = builder.tracing;
    this.turnDetection = builder.turnDetection;
    this.tools = builder.tools;
    this.toolChoice = builder.toolChoice;
    this.temperature = builder.temperature;
    this.maxResponseOutputTokens = builder.maxResponseOutputTokens;
    this.truncation = builder.truncation;
    this.prompt = builder.prompt;
  }

  public static Builder builder() {
    return new Builder();
  }

  public RealtimeSessionCreateRequestClientSecret clientSecret() {
    return clientSecret;
  }

  public Optional<Object> modalities() {
    return Optional.ofNullable(modalities);
  }

  public Optional<String> instructions() {
    return Optional.ofNullable(instructions);
  }

  public Optional<Object> voice() {
    return Optional.ofNullable(voice);
  }

  public Optional<String> inputAudioFormat() {
    return Optional.ofNullable(inputAudioFormat);
  }

  public Optional<String> outputAudioFormat() {
    return Optional.ofNullable(outputAudioFormat);
  }

  public Optional<RealtimeSessionCreateRequestInputAudioTranscription> inputAudioTranscription() {
    return Optional.ofNullable(inputAudioTranscription);
  }

  public Optional<Double> speed() {
    return Optional.ofNullable(speed);
  }

  public Optional<Object> tracing() {
    return Optional.ofNullable(tracing);
  }

  public Optional<RealtimeSessionCreateRequestTurnDetection> turnDetection() {
    return Optional.ofNullable(turnDetection);
  }

  public Optional<List<RealtimeSessionCreateRequestToolsItem>> tools() {
    return Optional.ofNullable(tools);
  }

  public Optional<String> toolChoice() {
    return Optional.ofNullable(toolChoice);
  }

  public Optional<Double> temperature() {
    return Optional.ofNullable(temperature);
  }

  public Optional<Object> maxResponseOutputTokens() {
    return Optional.ofNullable(maxResponseOutputTokens);
  }

  public Optional<Object> truncation() {
    return Optional.ofNullable(truncation);
  }

  public Optional<Prompt> prompt() {
    return Optional.ofNullable(prompt);
  }

  public static final class Builder {
    private RealtimeSessionCreateRequestClientSecret clientSecret;
    private Object modalities;
    private String instructions;
    private Object voice;
    private String inputAudioFormat;
    private String outputAudioFormat;
    private RealtimeSessionCreateRequestInputAudioTranscription inputAudioTranscription;
    private Double speed;
    private Object tracing;
    private RealtimeSessionCreateRequestTurnDetection turnDetection;
    private List<RealtimeSessionCreateRequestToolsItem> tools;
    private String toolChoice;
    private Double temperature;
    private Object maxResponseOutputTokens;
    private Object truncation;
    private Prompt prompt;

    public Builder clientSecret(RealtimeSessionCreateRequestClientSecret clientSecret) {
      this.clientSecret = clientSecret;
      return this;
    }

    public Builder modalities(Object modalities) {
      this.modalities = modalities;
      return this;
    }

    public Builder instructions(String instructions) {
      this.instructions = instructions;
      return this;
    }

    public Builder voice(Object voice) {
      this.voice = voice;
      return this;
    }

    public Builder inputAudioFormat(String inputAudioFormat) {
      this.inputAudioFormat = inputAudioFormat;
      return this;
    }

    public Builder outputAudioFormat(String outputAudioFormat) {
      this.outputAudioFormat = outputAudioFormat;
      return this;
    }

    public Builder inputAudioTranscription(RealtimeSessionCreateRequestInputAudioTranscription inputAudioTranscription) {
      this.inputAudioTranscription = inputAudioTranscription;
      return this;
    }

    public Builder speed(Double speed) {
      this.speed = speed;
      return this;
    }

    public Builder tracing(Object tracing) {
      this.tracing = tracing;
      return this;
    }

    public Builder turnDetection(RealtimeSessionCreateRequestTurnDetection turnDetection) {
      this.turnDetection = turnDetection;
      return this;
    }

    public Builder tools(List<RealtimeSessionCreateRequestToolsItem> tools) {
      this.tools = tools;
      return this;
    }

    public Builder toolChoice(String toolChoice) {
      this.toolChoice = toolChoice;
      return this;
    }

    public Builder temperature(Double temperature) {
      this.temperature = temperature;
      return this;
    }

    public Builder maxResponseOutputTokens(Object maxResponseOutputTokens) {
      this.maxResponseOutputTokens = maxResponseOutputTokens;
      return this;
    }

    public Builder truncation(Object truncation) {
      this.truncation = truncation;
      return this;
    }

    public Builder prompt(Prompt prompt) {
      this.prompt = prompt;
      return this;
    }

    public RealtimeSessionCreateParams build() {
      if (clientSecret == null) {
        throw new IllegalStateException("clientSecret is required");
      }
      return new RealtimeSessionCreateParams(this);
    }
  }
}
