// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.Map;

/** The session configuration for either a realtime or transcription session. */
public final class RealtimeCreateClientSecretResponseSession {
  private RealtimeCreateClientSecretResponseSession() {
  }

  /**
   * Decode JSON into the concrete RealtimeCreateClientSecretResponseSession variant selected by the "type"
   * discriminator. An unknown or absent discriminator keeps the raw parsed value.
   */
  public static Object fromJson(Object json) {
    if (!(json instanceof Map)) {
      return json;
    }
    Object discriminator = ((Map<?, ?>) json).get("type");
    if ("realtime".equals(discriminator)) {
      return RealtimeSessionCreateResponseGa.fromJson(json);
    }
    if ("transcription".equals(discriminator)) {
      return RealtimeTranscriptionSessionCreateResponseGa.fromJson(json);
    }
    return json;
  }
}
