// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

/**
 * A summary of the reasoning performed by the model. This can be
 * useful for debugging and understanding the model's reasoning process.
 * One of `auto`, `concise`, or `detailed`.
 * 
 * `concise` is supported for `computer-use-preview` models and all reasoning models after `gpt-5`.
 */
public enum ReasoningSummary implements Json.JsonEnum {
  AUTO("auto"),
  CONCISE("concise"),
  DETAILED("detailed");

  private final String value;

  ReasoningSummary(String value) {
    this.value = value;
  }

  public String value() {
    return value;
  }

  @Override
  public Object jsonValue() {
    return value;
  }

  public static ReasoningSummary fromValue(String value) {
    for (ReasoningSummary item : values()) {
      if (item.value.equals(value)) {
        return item;
      }
    }
    throw new IllegalArgumentException("unknown ReasoningSummary value: " + value);
  }

  public static ReasoningSummary fromJson(Object json) {
    return json == null ? null : fromValue(Json.asString(json));
  }
}
