// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

/** Default response format. Used to generate text responses. */
public final class ResponseFormatText implements Json.JsonSerializable {
  private String type;

  public String type() {
    return type;
  }

  public static ResponseFormatText fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    ResponseFormatText out = new ResponseFormatText();
    out.type = Json.asString(map.get("type"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("type", type != null ? type : "text");
    return map;
  }
}
