// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public final class Response implements Json.JsonSerializable {
  private Map<String, String> metadata;
  private Long topLogprobs;
  private Double temperature;
  private Double topP;
  private String user;
  private String safetyIdentifier;
  private String promptCacheKey;
  private ServiceTier serviceTier;
  private ResponsePromptCacheRetention promptCacheRetention;
  private String previousResponseId;
  private Object model;
  private Reasoning reasoning;
  private Boolean background;
  private Long maxToolCalls;
  private ResponseTextParam text;
  private List<Object> tools;
  private Object toolChoice;
  private Prompt prompt;
  private ResponseTruncation truncation;
  private String id;
  private String object;
  private ResponseStatus status;
  private Double createdAt;
  private Double completedAt;
  private ResponseError error;
  private ResponseIncompleteDetails incompleteDetails;
  private List<Object> output;
  private Object instructions;
  private String outputText;
  private ResponseUsage usage;
  private Boolean parallelToolCalls;
  private Conversation2 conversation;
  private Long maxOutputTokens;

  public Map<String, String> metadata() {
    return metadata;
  }

  public Long topLogprobs() {
    return topLogprobs;
  }

  public Double temperature() {
    return temperature;
  }

  public Double topP() {
    return topP;
  }

  public String user() {
    return user;
  }

  public String safetyIdentifier() {
    return safetyIdentifier;
  }

  public String promptCacheKey() {
    return promptCacheKey;
  }

  public ServiceTier serviceTier() {
    return serviceTier;
  }

  public ResponsePromptCacheRetention promptCacheRetention() {
    return promptCacheRetention;
  }

  public String previousResponseId() {
    return previousResponseId;
  }

  public Object model() {
    return model;
  }

  public Reasoning reasoning() {
    return reasoning;
  }

  public Boolean background() {
    return background;
  }

  public Long maxToolCalls() {
    return maxToolCalls;
  }

  public ResponseTextParam text() {
    return text;
  }

  public List<Object> tools() {
    return tools;
  }

  public Object toolChoice() {
    return toolChoice;
  }

  public Prompt prompt() {
    return prompt;
  }

  public ResponseTruncation truncation() {
    return truncation;
  }

  public String id() {
    return id;
  }

  public String object() {
    return object;
  }

  public ResponseStatus status() {
    return status;
  }

  public Double createdAt() {
    return createdAt;
  }

  public Double completedAt() {
    return completedAt;
  }

  public ResponseError error() {
    return error;
  }

  public ResponseIncompleteDetails incompleteDetails() {
    return incompleteDetails;
  }

  public List<Object> output() {
    return output;
  }

  public Object instructions() {
    return instructions;
  }

  public String outputText() {
    return outputText;
  }

  public ResponseUsage usage() {
    return usage;
  }

  public Boolean parallelToolCalls() {
    return parallelToolCalls;
  }

  public Conversation2 conversation() {
    return conversation;
  }

  public Long maxOutputTokens() {
    return maxOutputTokens;
  }

  public static Response fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    Response out = new Response();
    out.metadata = Json.mapValues(map.get("metadata"), __e -> Json.asString(__e));
    out.topLogprobs = Json.asLong(map.get("top_logprobs"));
    out.temperature = Json.asDouble(map.get("temperature"));
    out.topP = Json.asDouble(map.get("top_p"));
    out.user = Json.asString(map.get("user"));
    out.safetyIdentifier = Json.asString(map.get("safety_identifier"));
    out.promptCacheKey = Json.asString(map.get("prompt_cache_key"));
    out.serviceTier = ServiceTier.fromJson(map.get("service_tier"));
    out.promptCacheRetention = ResponsePromptCacheRetention.fromJson(map.get("prompt_cache_retention"));
    out.previousResponseId = Json.asString(map.get("previous_response_id"));
    out.model = map.get("model");
    out.reasoning = Reasoning.fromJson(map.get("reasoning"));
    out.background = Json.asBoolean(map.get("background"));
    out.maxToolCalls = Json.asLong(map.get("max_tool_calls"));
    out.text = ResponseTextParam.fromJson(map.get("text"));
    out.tools = Json.mapList(map.get("tools"), __e -> Tool.fromJson(__e));
    out.toolChoice = map.get("tool_choice");
    out.prompt = Prompt.fromJson(map.get("prompt"));
    out.truncation = ResponseTruncation.fromJson(map.get("truncation"));
    out.id = Json.asString(map.get("id"));
    out.object = Json.asString(map.get("object"));
    out.status = ResponseStatus.fromJson(map.get("status"));
    out.createdAt = Json.asDouble(map.get("created_at"));
    out.completedAt = Json.asDouble(map.get("completed_at"));
    out.error = ResponseError.fromJson(map.get("error"));
    out.incompleteDetails = ResponseIncompleteDetails.fromJson(map.get("incomplete_details"));
    out.output = Json.mapList(map.get("output"), __e -> OutputItem.fromJson(__e));
    out.instructions = map.get("instructions");
    out.outputText = Json.asString(map.get("output_text"));
    out.usage = ResponseUsage.fromJson(map.get("usage"));
    out.parallelToolCalls = Json.asBoolean(map.get("parallel_tool_calls"));
    out.conversation = Conversation2.fromJson(map.get("conversation"));
    out.maxOutputTokens = Json.asLong(map.get("max_output_tokens"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("metadata", metadata);
    if (topLogprobs != null) {
      map.put("top_logprobs", topLogprobs);
    }
    map.put("temperature", temperature);
    map.put("top_p", topP);
    if (user != null) {
      map.put("user", user);
    }
    if (safetyIdentifier != null) {
      map.put("safety_identifier", safetyIdentifier);
    }
    if (promptCacheKey != null) {
      map.put("prompt_cache_key", promptCacheKey);
    }
    if (serviceTier != null) {
      map.put("service_tier", serviceTier);
    }
    if (promptCacheRetention != null) {
      map.put("prompt_cache_retention", promptCacheRetention);
    }
    if (previousResponseId != null) {
      map.put("previous_response_id", previousResponseId);
    }
    map.put("model", model);
    if (reasoning != null) {
      map.put("reasoning", reasoning);
    }
    if (background != null) {
      map.put("background", background);
    }
    if (maxToolCalls != null) {
      map.put("max_tool_calls", maxToolCalls);
    }
    if (text != null) {
      map.put("text", text);
    }
    map.put("tools", tools);
    map.put("tool_choice", toolChoice);
    if (prompt != null) {
      map.put("prompt", prompt);
    }
    if (truncation != null) {
      map.put("truncation", truncation);
    }
    map.put("id", id);
    map.put("object", object != null ? object : "response");
    if (status != null) {
      map.put("status", status);
    }
    map.put("created_at", createdAt);
    if (completedAt != null) {
      map.put("completed_at", completedAt);
    }
    map.put("error", error);
    map.put("incomplete_details", incompleteDetails);
    map.put("output", output);
    map.put("instructions", instructions);
    if (outputText != null) {
      map.put("output_text", outputText);
    }
    if (usage != null) {
      map.put("usage", usage);
    }
    map.put("parallel_tool_calls", parallelToolCalls);
    if (conversation != null) {
      map.put("conversation", conversation);
    }
    if (maxOutputTokens != null) {
      map.put("max_output_tokens", maxOutputTokens);
    }
    return map;
  }
}
