// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

/** The definition of the function that was called. */
public final class RunStepDetailsToolCallsFunctionObjectFunction implements Json.JsonSerializable {
  private String name;
  private String arguments;
  private String output;

  public String name() {
    return name;
  }

  public String arguments() {
    return arguments;
  }

  public String output() {
    return output;
  }

  public static RunStepDetailsToolCallsFunctionObjectFunction fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    RunStepDetailsToolCallsFunctionObjectFunction out = new RunStepDetailsToolCallsFunctionObjectFunction();
    out.name = Json.asString(map.get("name"));
    out.arguments = Json.asString(map.get("arguments"));
    out.output = Json.asString(map.get("output"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("name", name);
    map.put("arguments", arguments);
    map.put("output", output);
    return map;
  }
}
