// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

public final class RunStepDetailsToolCallsFunctionObject implements Json.JsonSerializable {
  private String id;
  private String type;
  private RunStepDetailsToolCallsFunctionObjectFunction function;

  public String id() {
    return id;
  }

  public String type() {
    return type;
  }

  public RunStepDetailsToolCallsFunctionObjectFunction function() {
    return function;
  }

  public static RunStepDetailsToolCallsFunctionObject fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    RunStepDetailsToolCallsFunctionObject out = new RunStepDetailsToolCallsFunctionObject();
    out.id = Json.asString(map.get("id"));
    out.type = Json.asString(map.get("type"));
    out.function = RunStepDetailsToolCallsFunctionObjectFunction.fromJson(map.get("function"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("id", id);
    map.put("type", type != null ? type : "function");
    map.put("function", function);
    return map;
  }
}
