// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.Map;

/** A tool that can be used to generate a response. */
public final class Tool {
  private Tool() {
  }

  /**
   * Decode JSON into the concrete Tool variant selected by the "type"
   * discriminator. An unknown or absent discriminator keeps the raw parsed value.
   */
  public static Object fromJson(Object json) {
    if (!(json instanceof Map)) {
      return json;
    }
    Object discriminator = ((Map<?, ?>) json).get("type");
    if ("apply_patch".equals(discriminator)) {
      return ApplyPatchToolParam.fromJson(json);
    }
    if ("code_interpreter".equals(discriminator)) {
      return CodeInterpreterTool.fromJson(json);
    }
    if ("computer".equals(discriminator)) {
      return ComputerTool.fromJson(json);
    }
    if ("computer_use_preview".equals(discriminator)) {
      return ComputerUsePreviewTool.fromJson(json);
    }
    if ("custom".equals(discriminator)) {
      return CustomToolParam.fromJson(json);
    }
    if ("file_search".equals(discriminator)) {
      return FileSearchTool.fromJson(json);
    }
    if ("function".equals(discriminator)) {
      return FunctionTool.fromJson(json);
    }
    if ("image_generation".equals(discriminator)) {
      return ImageGenTool.fromJson(json);
    }
    if ("local_shell".equals(discriminator)) {
      return LocalShellToolParam.fromJson(json);
    }
    if ("mcp".equals(discriminator)) {
      return McpTool.fromJson(json);
    }
    if ("namespace".equals(discriminator)) {
      return NamespaceToolParam.fromJson(json);
    }
    if ("shell".equals(discriminator)) {
      return FunctionShellToolParam.fromJson(json);
    }
    if ("tool_search".equals(discriminator)) {
      return ToolSearchToolParam.fromJson(json);
    }
    return json;
  }
}
