// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

/** The aggregated vector stores usage details of the specific time bucket. */
public final class UsageVectorStoresResult implements Json.JsonSerializable {
  private String object;
  private Long usageBytes;
  private String projectId;

  public String object() {
    return object;
  }

  public Long usageBytes() {
    return usageBytes;
  }

  public String projectId() {
    return projectId;
  }

  public static UsageVectorStoresResult fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    UsageVectorStoresResult out = new UsageVectorStoresResult();
    out.object = Json.asString(map.get("object"));
    out.usageBytes = Json.asLong(map.get("usage_bytes"));
    out.projectId = Json.asString(map.get("project_id"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("object", object != null ? object : "organization.usage.vector_stores.result");
    map.put("usage_bytes", usageBytes);
    if (projectId != null) {
      map.put("project_id", projectId);
    }
    return map;
  }
}
