// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

public final class UserProjectsDataItem implements Json.JsonSerializable {
  private String id;
  private String name;
  private String role;

  public String id() {
    return id;
  }

  public String name() {
    return name;
  }

  public String role() {
    return role;
  }

  public static UserProjectsDataItem fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    UserProjectsDataItem out = new UserProjectsDataItem();
    out.id = Json.asString(map.get("id"));
    out.name = Json.asString(map.get("name"));
    out.role = Json.asString(map.get("role"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    if (id != null) {
      map.put("id", id);
    }
    if (name != null) {
      map.put("name", name);
    }
    if (role != null) {
      map.put("role", role);
    }
    return map;
  }
}
