// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

/** Role assignment linking a user to a role. */
public final class UserRoleAssignment implements Json.JsonSerializable {
  private String object;
  private User user;
  private Role role;

  public String object() {
    return object;
  }

  public User user() {
    return user;
  }

  public Role role() {
    return role;
  }

  public static UserRoleAssignment fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    UserRoleAssignment out = new UserRoleAssignment();
    out.object = Json.asString(map.get("object"));
    out.user = User.fromJson(map.get("user"));
    out.role = Role.fromJson(map.get("role"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("object", object != null ? object : "user.role");
    map.put("user", user);
    map.put("role", role);
    return map;
  }
}
