// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

/** A vector store is a collection of processed files can be used by the `file_search` tool. */
public final class VectorStoreObject implements Json.JsonSerializable {
  private String id;
  private String object;
  private Long createdAt;
  private String name;
  private Long usageBytes;
  private VectorStoreObjectFileCounts fileCounts;
  private VectorStoreObjectStatus status;
  private VectorStoreExpirationAfter expiresAfter;
  private Long expiresAt;
  private Long lastActiveAt;
  private Map<String, String> metadata;

  public String id() {
    return id;
  }

  public String object() {
    return object;
  }

  public Long createdAt() {
    return createdAt;
  }

  public String name() {
    return name;
  }

  public Long usageBytes() {
    return usageBytes;
  }

  public VectorStoreObjectFileCounts fileCounts() {
    return fileCounts;
  }

  public VectorStoreObjectStatus status() {
    return status;
  }

  public VectorStoreExpirationAfter expiresAfter() {
    return expiresAfter;
  }

  public Long expiresAt() {
    return expiresAt;
  }

  public Long lastActiveAt() {
    return lastActiveAt;
  }

  public Map<String, String> metadata() {
    return metadata;
  }

  public static VectorStoreObject fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    VectorStoreObject out = new VectorStoreObject();
    out.id = Json.asString(map.get("id"));
    out.object = Json.asString(map.get("object"));
    out.createdAt = Json.asLong(map.get("created_at"));
    out.name = Json.asString(map.get("name"));
    out.usageBytes = Json.asLong(map.get("usage_bytes"));
    out.fileCounts = VectorStoreObjectFileCounts.fromJson(map.get("file_counts"));
    out.status = VectorStoreObjectStatus.fromJson(map.get("status"));
    out.expiresAfter = VectorStoreExpirationAfter.fromJson(map.get("expires_after"));
    out.expiresAt = Json.asLong(map.get("expires_at"));
    out.lastActiveAt = Json.asLong(map.get("last_active_at"));
    out.metadata = Json.mapValues(map.get("metadata"), __e -> Json.asString(__e));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("id", id);
    map.put("object", object != null ? object : "vector_store");
    map.put("created_at", createdAt);
    map.put("name", name);
    map.put("usage_bytes", usageBytes);
    map.put("file_counts", fileCounts);
    map.put("status", status);
    if (expiresAfter != null) {
      map.put("expires_after", expiresAfter);
    }
    if (expiresAt != null) {
      map.put("expires_at", expiresAt);
    }
    map.put("last_active_at", lastActiveAt);
    map.put("metadata", metadata);
    return map;
  }
}
