# Code generated by opensdk. DO NOT EDIT.

module Openai
  module Resources
    class VectorStores
      attr_reader :files

      # @api private
      def initialize(transport)
        @transport = transport
        @files = VectorStoresFiles.new(transport)
      end
    end

    class VectorStoresFiles
      # @api private
      def initialize(transport)
        @transport = transport
      end

      # Retrieve the parsed contents of a vector store file.
      #
      # @param vector_store_id [String]
      # @param file_id [String]
      # @return [Page<Models::VectorStoreFileContentResponseDataItem>]
      def content(vector_store_id, file_id)
        raise ArgumentError, "Expected a non-empty value for `vector_store_id`" if vector_store_id.nil? || vector_store_id.to_s.empty?

        raise ArgumentError, "Expected a non-empty value for `file_id`" if file_id.nil? || file_id.to_s.empty?

        response = @transport.request(
          method: :get,
          path: "/vector_stores/#{vector_store_id}/files/#{file_id}/content"
        )
        Openai::Page.new(data: (response || {})[:data], has_more: (response || {})[:has_more])
      end
    end
  end
end
