# Code generated by opensdk. DO NOT EDIT.

require "minitest/autorun"
require "stringio"
require_relative "../lib/wire_kitchen"

# Shared setup for the generated SDK test suite: a Client bound to a mock base
# URL (override with TEST_API_BASE_URL). Running the suite against a mock server
# is a follow-up; these tests exist to be syntactically and structurally sound.
module TestHelper
  BASE_URL = ENV.fetch("TEST_API_BASE_URL", "http://localhost:4010")

  def build_client
    WireKitchen::Client.new(api_key: "My API Key", base_url: BASE_URL)
  end
end
