// Code generated by opencli2rust. DO NOT EDIT.

use std::process::ExitCode;

use clap::{Arg, ArgMatches, Command};

use crate::gen::runtime::{self, CliOverrides, Context};

pub fn command() -> Command {
    Command::new("fine-tuning")
        .subcommand_required(true)
        .arg_required_else_help(true)
        .subcommand(
            Command::new("checkpoints")
                .subcommand_required(true)
                .arg_required_else_help(true)
                .subcommand(
                    Command::new("permissions")
                        .subcommand_required(true)
                        .arg_required_else_help(true)
                        .subcommand(
                            Command::new("create")
                                .about("**NOTE:** Calling this endpoint requires an [admin API key](../admin-api-keys).\n\nThis enables organization owners to share fine-tuned models with other projects in their organization.\n")
                                .arg(
                                    Arg::new("fine-tuned-model-checkpoint")
                                        .help("The ID of the fine-tuned model checkpoint to create a permission for.\n")
                                        .required(true),
                                )
                                .arg(
                                    Arg::new("project-ids")
                                        .long("project-ids")
                                        .action(clap::ArgAction::Append)
                                        .value_delimiter(',')
                                        .help("The project identifiers to grant access to.")
                                        .required(true),
                                ),
                        ),
                ),
        )
}

pub async fn run<O: CliOverrides>(ctx: &Context, o: &O, cmd_path: &[String], m: &ArgMatches) -> ExitCode {
    let parts: Vec<&str> = cmd_path.iter().map(String::as_str).collect();
    match parts.as_slice() {
        ["fine-tuning", "checkpoints", "permissions", "create"] => handle_fine_tuning_checkpoints_permissions_create(ctx, o, cmd_path, m).await,
        _ => {
            eprintln!("error: unknown command: {}", cmd_path.join(" "));
            ExitCode::FAILURE
        }
    }
}

async fn handle_fine_tuning_checkpoints_permissions_create<O: CliOverrides>(
    ctx: &Context,
    o: &O,
    cmd_path: &[String],
    m: &ArgMatches,
) -> ExitCode {
    let fine_tuned_model_checkpoint = m.get_one::<String>("fine-tuned-model-checkpoint").map(String::as_str).unwrap_or("");
    let path = format!("/fine_tuning/checkpoints/{}/permissions", runtime::path_escape(fine_tuned_model_checkpoint));
    let mut body = serde_json::Map::new();
    if let Some(vs) = m.get_many::<String>("project-ids") {
        body.insert("project_ids".to_string(), serde_json::Value::Array(vs.cloned().map(serde_json::Value::String).collect()));
    }
    let body_bytes = match serde_json::to_vec(&serde_json::Value::Object(body)) {
        Ok(bytes) => bytes,
        Err(err) => return o.print_error(cmd_path, &runtime::Error::Invalid(err.to_string())),
    };
    let req = runtime::Request {
        method: "POST",
        path,
        query: Vec::new(),
        headers: Vec::new(),
        body: Some(body_bytes),
    };
    runtime::run_request(ctx, o, cmd_path, req).await
}
