// Code generated by opensdk. DO NOT EDIT.

import { APIResource } from '../core/resource';
import type { APIClient, RequestOptions } from '../core/request';
import { CursorPage } from '../core/pagination';
import type { ConversationItem, ConversationResource, ConversationsItemsListOrder, DeletedConversationResource, IncludeEnum, InputItem, Metadata } from '../models';
import { decodeConversationItem } from '../models';

export class Conversations extends APIResource {
  readonly items: ConversationsItems;

  constructor(client: APIClient) {
    super(client);
    this.items = new ConversationsItems(client);
  }

  /** Create a conversation. */
  create(body?: ConversationCreateParams, options?: RequestOptions): Promise<ConversationResource> {
    return this._client.request<ConversationResource>({ method: "POST", path: "/conversations", body }, options);
  }

  /** Delete a conversation. Items in the conversation will not be deleted. */
  delete(conversationId: string, options?: RequestOptions): Promise<DeletedConversationResource> {
    if (!conversationId) {
      throw new Error("missing required conversation_id parameter");
    }
    return this._client.request<DeletedConversationResource>({ method: "DELETE", path: `/conversations/${conversationId}` }, options);
  }

  /** Get a conversation */
  retrieve(conversationId: string, options?: RequestOptions): Promise<ConversationResource> {
    if (!conversationId) {
      throw new Error("missing required conversation_id parameter");
    }
    return this._client.request<ConversationResource>({ method: "GET", path: `/conversations/${conversationId}` }, options);
  }

  /** Update a conversation */
  update(conversationId: string, body?: ConversationUpdateParams, options?: RequestOptions): Promise<ConversationResource> {
    if (!conversationId) {
      throw new Error("missing required conversation_id parameter");
    }
    return this._client.request<ConversationResource>({ method: "POST", path: `/conversations/${conversationId}`, body }, options);
  }
}

export class ConversationsItems extends APIResource {
  /** Create items in a conversation with the given ID. */
  create(conversationId: string, params: ConversationItemCreateParams, options?: RequestOptions): Promise<CursorPage<ConversationItem>> {
    if (!conversationId) {
      throw new Error("missing required conversation_id parameter");
    }
    return this._client
      .request<unknown>({ method: "POST", path: `/conversations/${conversationId}/items`, query: { include: params.include }, body: { items: params.items } }, options)
      .then((raw) => CursorPage.fromResponse<ConversationItem>(raw));
  }

  /** Delete an item from a conversation with the given IDs. */
  delete(conversationId: string, itemId: string, options?: RequestOptions): Promise<ConversationResource> {
    if (!conversationId) {
      throw new Error("missing required conversation_id parameter");
    }
    if (!itemId) {
      throw new Error("missing required item_id parameter");
    }
    return this._client.request<ConversationResource>({ method: "DELETE", path: `/conversations/${conversationId}/items/${itemId}` }, options);
  }

  /** List all items for a conversation with the given ID. */
  list(conversationId: string, query?: ConversationItemListParams, options?: RequestOptions): Promise<CursorPage<ConversationItem>> {
    if (!conversationId) {
      throw new Error("missing required conversation_id parameter");
    }
    return this._client
      .request<unknown>({ method: "GET", path: `/conversations/${conversationId}/items`, query }, options)
      .then((raw) => CursorPage.fromResponse<ConversationItem>(raw));
  }

  /** Get a single item from a conversation with the given IDs. */
  retrieve(conversationId: string, itemId: string, query?: ConversationItemRetrieveParams, options?: RequestOptions): Promise<ConversationItem> {
    if (!conversationId) {
      throw new Error("missing required conversation_id parameter");
    }
    if (!itemId) {
      throw new Error("missing required item_id parameter");
    }
    return this._client
      .request<unknown>({ method: "GET", path: `/conversations/${conversationId}/items/${itemId}`, query }, options)
      .then(decodeConversationItem);
  }
}

export interface ConversationCreateParams {
  metadata?: Metadata | null;
  items?: InputItem[] | null;
}

export interface ConversationUpdateParams {
  metadata: Metadata;
}

export interface ConversationItemCreateParams {
  items: InputItem[];
  include?: IncludeEnum[];
}

export interface ConversationItemListParams {
  limit?: number;
  order?: ConversationsItemsListOrder;
  after?: string;
  include?: IncludeEnum[];
}

export interface ConversationItemRetrieveParams {
  include?: IncludeEnum[];
}
