// Code generated by opensdk. DO NOT EDIT.

import { APIResource } from '../core/resource';
import type { APIClient, RequestOptions } from '../core/request';
import type { ProjectServiceAccount } from '../models';

export class Admin extends APIResource {
  readonly organization: AdminOrganization;

  constructor(client: APIClient) {
    super(client);
    this.organization = new AdminOrganization(client);
  }
}

export class AdminOrganization extends APIResource {
  readonly projects: AdminOrganizationProjects;

  constructor(client: APIClient) {
    super(client);
    this.projects = new AdminOrganizationProjects(client);
  }
}

export class AdminOrganizationProjects extends APIResource {
  readonly serviceAccounts: AdminOrganizationProjectsServiceAccounts;

  constructor(client: APIClient) {
    super(client);
    this.serviceAccounts = new AdminOrganizationProjectsServiceAccounts(client);
  }
}

export class AdminOrganizationProjectsServiceAccounts extends APIResource {
  /** Retrieves a service account in the project. */
  retrieve(projectId: string, serviceAccountId: string, options?: RequestOptions): Promise<ProjectServiceAccount> {
    if (!projectId) {
      throw new Error("missing required project_id parameter");
    }
    if (!serviceAccountId) {
      throw new Error("missing required service_account_id parameter");
    }
    return this._client.request<ProjectServiceAccount>({ method: "GET", path: `/organization/projects/${projectId}/service_accounts/${serviceAccountId}` }, options);
  }
}
