// Code generated by opensdk. DO NOT EDIT.

import { APIResource } from '../core/resource';
import type { RequestOptions } from '../core/request';
import type { ParseWebhookResult, ProviderKind } from '../models';

export class ParseWebhook extends APIResource {
  create(body: ParseWebhookCreateParams, options?: RequestOptions): Promise<ParseWebhookResult> {
    return this._client.request<ParseWebhookResult>({ method: "POST", path: "/parse-webhook", body }, options);
  }
}

export interface ParseWebhookCreateParams {
  kind: ProviderKind;
  secret: string;
  headers: Record<string, string>;
  bodyBase64: string;
}
