// Code generated by opensdk. DO NOT EDIT.

package openai

import (
	"context"
	"errors"
	"fmt"
	"net/http"

	"github.com/example/openai/internal/requestconfig"
	"github.com/example/openai/option"
)

// FileService ...
type FileService struct {
	Options []option.RequestOption
}

// NewFileService constructs a service that shares the client's request options.
func NewFileService(opts ...option.RequestOption) (r FileService) {
	r = FileService{}
	r.Options = opts
	return
}

// Returns the contents of the specified file.
func (r *FileService) Content(ctx context.Context, fileID string, opts ...option.RequestOption) (res string, err error) {
	opts = append(r.Options[:], opts...)
	if fileID == "" {
		err = errors.New("missing required file_id parameter")
		return
	}
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, fmt.Sprintf("files/%v/content", fileID), nil, opts...)
	if err != nil {
		return
	}
	err = cfg.Execute(&res)
	return
}
