# Code generated by opensdk. DO NOT EDIT.

module Openai
  module Resources
    class Admin
      attr_reader :organization

      # @api private
      def initialize(transport)
        @transport = transport
        @organization = AdminOrganization.new(transport)
      end
    end

    class AdminOrganization
      attr_reader :projects

      # @api private
      def initialize(transport)
        @transport = transport
        @projects = AdminOrganizationProjects.new(transport)
      end
    end

    class AdminOrganizationProjects
      attr_reader :users

      # @api private
      def initialize(transport)
        @transport = transport
        @users = AdminOrganizationProjectsUsers.new(transport)
      end
    end

    class AdminOrganizationProjectsUsers
      # @api private
      def initialize(transport)
        @transport = transport
      end

      # Modifies a user's role in the project.
      #
      # @param project_id [String]
      # @param user_id [String]
      # @param role [String]
      # @return [Models::ProjectUser]
      def update(project_id, user_id, role: nil)
        raise ArgumentError, "Expected a non-empty value for `project_id`" if project_id.nil? || project_id.to_s.empty?

        raise ArgumentError, "Expected a non-empty value for `user_id`" if user_id.nil? || user_id.to_s.empty?

        @transport.request(
          method: :post,
          path: "/organization/projects/#{project_id}/users/#{user_id}",
          body: { "role" => role }
        )
      end
    end
  end
end
