// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.Optional;

/** Parameters for list: Lists the groups that have access to a project. */
public final class AdminOrganizationProjectGroupListParams {
  private final Long limit;
  private final String after;
  private final AdminOrganizationProjectsGroupsListOrder order;

  private AdminOrganizationProjectGroupListParams(Builder builder) {
    this.limit = builder.limit;
    this.after = builder.after;
    this.order = builder.order;
  }

  public static Builder builder() {
    return new Builder();
  }

  public Optional<Long> limit() {
    return Optional.ofNullable(limit);
  }

  public Optional<String> after() {
    return Optional.ofNullable(after);
  }

  public Optional<AdminOrganizationProjectsGroupsListOrder> order() {
    return Optional.ofNullable(order);
  }

  public static final class Builder {
    private Long limit;
    private String after;
    private AdminOrganizationProjectsGroupsListOrder order;

    public Builder limit(Long limit) {
      this.limit = limit;
      return this;
    }

    public Builder after(String after) {
      this.after = after;
      return this;
    }

    public Builder order(AdminOrganizationProjectsGroupsListOrder order) {
      this.order = order;
      return this;
    }

    public AdminOrganizationProjectGroupListParams build() {
      return new AdminOrganizationProjectGroupListParams(this);
    }
  }
}
