// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.Optional;

/** Parameters for update: Modifies a user's role in the project. */
public final class AdminOrganizationProjectUserUpdateParams {
  private final String role;

  private AdminOrganizationProjectUserUpdateParams(Builder builder) {
    this.role = builder.role;
  }

  public static Builder builder() {
    return new Builder();
  }

  public Optional<String> role() {
    return Optional.ofNullable(role);
  }

  public static final class Builder {
    private String role;

    public Builder role(String role) {
      this.role = role;
      return this;
    }

    public AdminOrganizationProjectUserUpdateParams build() {
      return new AdminOrganizationProjectUserUpdateParams(this);
    }
  }
}
