// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

public final class AdminOrganizationProjectServiceAccountService {
  private final Transport transport;

  AdminOrganizationProjectServiceAccountService(Transport transport) {
    this.transport = transport;
  }

  /** Creates a new service account in the project. This also returns an unredacted API key for the service account. */
  public ProjectServiceAccountCreateResponse create(String projectId, AdminOrganizationProjectServiceAccountCreateParams params) {
    if (projectId == null || projectId.isEmpty()) {
      throw new IllegalArgumentException("missing required project_id parameter");
    }
    Transport.Request request = new Transport.Request("POST", "/organization/projects/" + Transport.encodePath(projectId) + "/service_accounts");
    Map<String, Object> body = new LinkedHashMap<>();
    body.put("name", params.name());
    request.body(body);
    return ProjectServiceAccountCreateResponse.fromJson(transport.execute(request));
  }

  /**
   * Deletes a service account from the project.
   * 
   * Returns confirmation of service account deletion, or an error if the project
   * is archived (archived projects have no service accounts).
   */
  public ProjectServiceAccountDeleteResponse delete(String projectId, String serviceAccountId) {
    if (projectId == null || projectId.isEmpty()) {
      throw new IllegalArgumentException("missing required project_id parameter");
    }
    if (serviceAccountId == null || serviceAccountId.isEmpty()) {
      throw new IllegalArgumentException("missing required service_account_id parameter");
    }
    Transport.Request request = new Transport.Request("DELETE", "/organization/projects/" + Transport.encodePath(projectId) + "/service_accounts/" + Transport.encodePath(serviceAccountId));
    return ProjectServiceAccountDeleteResponse.fromJson(transport.execute(request));
  }

  /** Returns a list of service accounts in the project. */
  public CursorPage<ProjectServiceAccount> list(String projectId, AdminOrganizationProjectServiceAccountListParams params) {
    if (projectId == null || projectId.isEmpty()) {
      throw new IllegalArgumentException("missing required project_id parameter");
    }
    Transport.Request request = new Transport.Request("GET", "/organization/projects/" + Transport.encodePath(projectId) + "/service_accounts");
    params.limit().ifPresent(value -> request.query("limit", String.valueOf(value)));
    params.after().ifPresent(value -> request.query("after", String.valueOf(value)));
    return CursorPage.fromJson(transport.execute(request), __e -> ProjectServiceAccount.fromJson(__e));
  }

  /** Retrieves a service account in the project. */
  public ProjectServiceAccount retrieve(String projectId, String serviceAccountId) {
    if (projectId == null || projectId.isEmpty()) {
      throw new IllegalArgumentException("missing required project_id parameter");
    }
    if (serviceAccountId == null || serviceAccountId.isEmpty()) {
      throw new IllegalArgumentException("missing required service_account_id parameter");
    }
    Transport.Request request = new Transport.Request("GET", "/organization/projects/" + Transport.encodePath(projectId) + "/service_accounts/" + Transport.encodePath(serviceAccountId));
    return ProjectServiceAccount.fromJson(transport.execute(request));
  }
}
