// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

public enum AdminOrganizationUsageAudioSpeechesListGroupByItem implements Json.JsonEnum {
  PROJECT_ID("project_id"),
  USER_ID("user_id"),
  API_KEY_ID("api_key_id"),
  MODEL("model");

  private final String value;

  AdminOrganizationUsageAudioSpeechesListGroupByItem(String value) {
    this.value = value;
  }

  public String value() {
    return value;
  }

  @Override
  public Object jsonValue() {
    return value;
  }

  public static AdminOrganizationUsageAudioSpeechesListGroupByItem fromValue(String value) {
    for (AdminOrganizationUsageAudioSpeechesListGroupByItem item : values()) {
      if (item.value.equals(value)) {
        return item;
      }
    }
    throw new IllegalArgumentException("unknown AdminOrganizationUsageAudioSpeechesListGroupByItem value: " + value);
  }

  public static AdminOrganizationUsageAudioSpeechesListGroupByItem fromJson(Object json) {
    return json == null ? null : fromValue(Json.asString(json));
  }
}
