// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

/** A tool call representing a request to create, delete, or update files using diff patches. */
public final class ApplyPatchToolCallItemParam implements Json.JsonSerializable {
  private String type;
  private String id;
  private String callId;
  private ApplyPatchCallStatusParam status;
  private Object operation;

  public String type() {
    return type;
  }

  public String id() {
    return id;
  }

  public String callId() {
    return callId;
  }

  public ApplyPatchCallStatusParam status() {
    return status;
  }

  public Object operation() {
    return operation;
  }

  public static ApplyPatchToolCallItemParam fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    ApplyPatchToolCallItemParam out = new ApplyPatchToolCallItemParam();
    out.type = Json.asString(map.get("type"));
    out.id = Json.asString(map.get("id"));
    out.callId = Json.asString(map.get("call_id"));
    out.status = ApplyPatchCallStatusParam.fromJson(map.get("status"));
    out.operation = ApplyPatchOperationParam.fromJson(map.get("operation"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("type", type != null ? type : "apply_patch_call");
    if (id != null) {
      map.put("id", id);
    }
    map.put("call_id", callId);
    map.put("status", status);
    map.put("operation", operation);
    return map;
  }
}
