// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

/** Specifies a tool the model should use. Use to force the model to call a specific tool. */
public final class AssistantsNamedToolChoice implements Json.JsonSerializable {
  private AssistantsNamedToolChoiceType type;
  private AssistantsNamedToolChoiceFunction function;

  public AssistantsNamedToolChoiceType type() {
    return type;
  }

  public AssistantsNamedToolChoiceFunction function() {
    return function;
  }

  public static AssistantsNamedToolChoice fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    AssistantsNamedToolChoice out = new AssistantsNamedToolChoice();
    out.type = AssistantsNamedToolChoiceType.fromJson(map.get("type"));
    out.function = AssistantsNamedToolChoiceFunction.fromJson(map.get("function"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("type", type);
    if (function != null) {
      map.put("function", function);
    }
    return map;
  }
}
