// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

/** Information about the created group. */
public final class AuditLogGroupCreatedData implements Json.JsonSerializable {
  private String groupName;

  public String groupName() {
    return groupName;
  }

  public static AuditLogGroupCreatedData fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    AuditLogGroupCreatedData out = new AuditLogGroupCreatedData();
    out.groupName = Json.asString(map.get("group_name"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    if (groupName != null) {
      map.put("group_name", groupName);
    }
    return map;
  }
}
