// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

/** The project that the action was scoped to. Absent for actions not scoped to projects. Note that any admin actions taken via Admin API keys are associated with the default project. */
public final class AuditLogProject implements Json.JsonSerializable {
  private String id;
  private String name;

  public String id() {
    return id;
  }

  public String name() {
    return name;
  }

  public static AuditLogProject fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    AuditLogProject out = new AuditLogProject();
    out.id = Json.asString(map.get("id"));
    out.name = Json.asString(map.get("name"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    if (id != null) {
      map.put("id", id);
    }
    if (name != null) {
      map.put("name", name);
    }
    return map;
  }
}
