// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** Messages sent by the model in response to user messages. */
public final class ChatCompletionRequestAssistantMessage implements Json.JsonSerializable {
  private Object content;
  private String refusal;
  private String role;
  private String name;
  private ChatCompletionRequestAssistantMessageAudio audio;
  private List<Object> toolCalls;
  private ChatCompletionRequestAssistantMessageFunctionCall functionCall;

  public Object content() {
    return content;
  }

  public String refusal() {
    return refusal;
  }

  public String role() {
    return role;
  }

  public String name() {
    return name;
  }

  public ChatCompletionRequestAssistantMessageAudio audio() {
    return audio;
  }

  public List<Object> toolCalls() {
    return toolCalls;
  }

  public ChatCompletionRequestAssistantMessageFunctionCall functionCall() {
    return functionCall;
  }

  public static ChatCompletionRequestAssistantMessage fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    ChatCompletionRequestAssistantMessage out = new ChatCompletionRequestAssistantMessage();
    out.content = map.get("content");
    out.refusal = Json.asString(map.get("refusal"));
    out.role = Json.asString(map.get("role"));
    out.name = Json.asString(map.get("name"));
    out.audio = ChatCompletionRequestAssistantMessageAudio.fromJson(map.get("audio"));
    out.toolCalls = Json.mapList(map.get("tool_calls"), __e -> ChatCompletionMessageToolCallsItem.fromJson(__e));
    out.functionCall = ChatCompletionRequestAssistantMessageFunctionCall.fromJson(map.get("function_call"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    if (content != null) {
      map.put("content", content);
    }
    if (refusal != null) {
      map.put("refusal", refusal);
    }
    map.put("role", role != null ? role : "assistant");
    if (name != null) {
      map.put("name", name);
    }
    if (audio != null) {
      map.put("audio", audio);
    }
    if (toolCalls != null) {
      map.put("tool_calls", toolCalls);
    }
    if (functionCall != null) {
      map.put("function_call", functionCall);
    }
    return map;
  }
}
