// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

/** Specifies a tool the model should use. Use to force the model to call a specific custom tool. */
public final class ChatCompletionNamedToolChoiceCustom implements Json.JsonSerializable {
  private String type;
  private ChatCompletionNamedToolChoiceCustomCustom custom;

  public String type() {
    return type;
  }

  public ChatCompletionNamedToolChoiceCustomCustom custom() {
    return custom;
  }

  public static ChatCompletionNamedToolChoiceCustom fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    ChatCompletionNamedToolChoiceCustom out = new ChatCompletionNamedToolChoiceCustom();
    out.type = Json.asString(map.get("type"));
    out.custom = ChatCompletionNamedToolChoiceCustomCustom.fromJson(map.get("custom"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("type", type != null ? type : "custom");
    map.put("custom", custom);
    return map;
  }
}
