// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

/** A URL citation when using web search. */
public final class ChatCompletionResponseMessageAnnotationsItem implements Json.JsonSerializable {
  private String type;
  private ChatCompletionResponseMessageAnnotationsItemUrlCitation urlCitation;

  public String type() {
    return type;
  }

  public ChatCompletionResponseMessageAnnotationsItemUrlCitation urlCitation() {
    return urlCitation;
  }

  public static ChatCompletionResponseMessageAnnotationsItem fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    ChatCompletionResponseMessageAnnotationsItem out = new ChatCompletionResponseMessageAnnotationsItem();
    out.type = Json.asString(map.get("type"));
    out.urlCitation = ChatCompletionResponseMessageAnnotationsItemUrlCitation.fromJson(map.get("url_citation"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("type", type != null ? type : "url_citation");
    map.put("url_citation", urlCitation);
    return map;
  }
}
