// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

public final class ContextManagementParam implements Json.JsonSerializable {
  private String type;
  private Long compactThreshold;

  public String type() {
    return type;
  }

  public Long compactThreshold() {
    return compactThreshold;
  }

  public static ContextManagementParam fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    ContextManagementParam out = new ContextManagementParam();
    out.type = Json.asString(map.get("type"));
    out.compactThreshold = Json.asLong(map.get("compact_threshold"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("type", type);
    if (compactThreshold != null) {
      map.put("compact_threshold", compactThreshold);
    }
    return map;
  }
}
