// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.Optional;

/** Parameters for create: Creates a container file. */
public final class ContainerFileCreateParams {
  private final String fileId;
  private final byte[] file;

  private ContainerFileCreateParams(Builder builder) {
    this.fileId = builder.fileId;
    this.file = builder.file;
  }

  public static Builder builder() {
    return new Builder();
  }

  public Optional<String> fileId() {
    return Optional.ofNullable(fileId);
  }

  public Optional<byte[]> file() {
    return Optional.ofNullable(file);
  }

  public static final class Builder {
    private String fileId;
    private byte[] file;

    public Builder fileId(String fileId) {
      this.fileId = fileId;
      return this;
    }

    public Builder file(byte[] file) {
      this.file = file;
      return this;
    }

    public ContainerFileCreateParams build() {
      return new ContainerFileCreateParams(this);
    }
  }
}
