// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** Log probability information for the choice. */
public final class CreateChatCompletionResponseChoicesItemLogprobs implements Json.JsonSerializable {
  private List<ChatCompletionTokenLogprob> content;
  private List<ChatCompletionTokenLogprob> refusal;

  public List<ChatCompletionTokenLogprob> content() {
    return content;
  }

  public List<ChatCompletionTokenLogprob> refusal() {
    return refusal;
  }

  public static CreateChatCompletionResponseChoicesItemLogprobs fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    CreateChatCompletionResponseChoicesItemLogprobs out = new CreateChatCompletionResponseChoicesItemLogprobs();
    out.content = Json.mapList(map.get("content"), __e -> ChatCompletionTokenLogprob.fromJson(__e));
    out.refusal = Json.mapList(map.get("refusal"), __e -> ChatCompletionTokenLogprob.fromJson(__e));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("content", content);
    map.put("refusal", refusal);
    return map;
  }
}
