// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public final class CreateResponse implements Json.JsonSerializable {
  private Map<String, String> metadata;
  private Long topLogprobs;
  private Double temperature;
  private Double topP;
  private String user;
  private String safetyIdentifier;
  private String promptCacheKey;
  private ServiceTier serviceTier;
  private CreateResponsePromptCacheRetention promptCacheRetention;
  private String previousResponseId;
  private Object model;
  private Reasoning reasoning;
  private Boolean background;
  private Long maxToolCalls;
  private ResponseTextParam text;
  private List<Object> tools;
  private Object toolChoice;
  private Prompt prompt;
  private CreateResponseTruncation truncation;
  private Object input;
  private List<IncludeEnum> include;
  private Boolean parallelToolCalls;
  private Boolean store;
  private String instructions;
  private Boolean stream;
  private ResponseStreamOptions streamOptions;
  private Object conversation;
  private List<ContextManagementParam> contextManagement;
  private Long maxOutputTokens;

  public Map<String, String> metadata() {
    return metadata;
  }

  public Long topLogprobs() {
    return topLogprobs;
  }

  public Double temperature() {
    return temperature;
  }

  public Double topP() {
    return topP;
  }

  public String user() {
    return user;
  }

  public String safetyIdentifier() {
    return safetyIdentifier;
  }

  public String promptCacheKey() {
    return promptCacheKey;
  }

  public ServiceTier serviceTier() {
    return serviceTier;
  }

  public CreateResponsePromptCacheRetention promptCacheRetention() {
    return promptCacheRetention;
  }

  public String previousResponseId() {
    return previousResponseId;
  }

  public Object model() {
    return model;
  }

  public Reasoning reasoning() {
    return reasoning;
  }

  public Boolean background() {
    return background;
  }

  public Long maxToolCalls() {
    return maxToolCalls;
  }

  public ResponseTextParam text() {
    return text;
  }

  public List<Object> tools() {
    return tools;
  }

  public Object toolChoice() {
    return toolChoice;
  }

  public Prompt prompt() {
    return prompt;
  }

  public CreateResponseTruncation truncation() {
    return truncation;
  }

  public Object input() {
    return input;
  }

  public List<IncludeEnum> include() {
    return include;
  }

  public Boolean parallelToolCalls() {
    return parallelToolCalls;
  }

  public Boolean store() {
    return store;
  }

  public String instructions() {
    return instructions;
  }

  public Boolean stream() {
    return stream;
  }

  public ResponseStreamOptions streamOptions() {
    return streamOptions;
  }

  public Object conversation() {
    return conversation;
  }

  public List<ContextManagementParam> contextManagement() {
    return contextManagement;
  }

  public Long maxOutputTokens() {
    return maxOutputTokens;
  }

  public static CreateResponse fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    CreateResponse out = new CreateResponse();
    out.metadata = Json.mapValues(map.get("metadata"), __e -> Json.asString(__e));
    out.topLogprobs = Json.asLong(map.get("top_logprobs"));
    out.temperature = Json.asDouble(map.get("temperature"));
    out.topP = Json.asDouble(map.get("top_p"));
    out.user = Json.asString(map.get("user"));
    out.safetyIdentifier = Json.asString(map.get("safety_identifier"));
    out.promptCacheKey = Json.asString(map.get("prompt_cache_key"));
    out.serviceTier = ServiceTier.fromJson(map.get("service_tier"));
    out.promptCacheRetention = CreateResponsePromptCacheRetention.fromJson(map.get("prompt_cache_retention"));
    out.previousResponseId = Json.asString(map.get("previous_response_id"));
    out.model = map.get("model");
    out.reasoning = Reasoning.fromJson(map.get("reasoning"));
    out.background = Json.asBoolean(map.get("background"));
    out.maxToolCalls = Json.asLong(map.get("max_tool_calls"));
    out.text = ResponseTextParam.fromJson(map.get("text"));
    out.tools = Json.mapList(map.get("tools"), __e -> Tool.fromJson(__e));
    out.toolChoice = map.get("tool_choice");
    out.prompt = Prompt.fromJson(map.get("prompt"));
    out.truncation = CreateResponseTruncation.fromJson(map.get("truncation"));
    out.input = map.get("input");
    out.include = Json.mapList(map.get("include"), __e -> IncludeEnum.fromJson(__e));
    out.parallelToolCalls = Json.asBoolean(map.get("parallel_tool_calls"));
    out.store = Json.asBoolean(map.get("store"));
    out.instructions = Json.asString(map.get("instructions"));
    out.stream = Json.asBoolean(map.get("stream"));
    out.streamOptions = ResponseStreamOptions.fromJson(map.get("stream_options"));
    out.conversation = map.get("conversation");
    out.contextManagement = Json.mapList(map.get("context_management"), __e -> ContextManagementParam.fromJson(__e));
    out.maxOutputTokens = Json.asLong(map.get("max_output_tokens"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    if (metadata != null) {
      map.put("metadata", metadata);
    }
    if (topLogprobs != null) {
      map.put("top_logprobs", topLogprobs);
    }
    if (temperature != null) {
      map.put("temperature", temperature);
    }
    if (topP != null) {
      map.put("top_p", topP);
    }
    if (user != null) {
      map.put("user", user);
    }
    if (safetyIdentifier != null) {
      map.put("safety_identifier", safetyIdentifier);
    }
    if (promptCacheKey != null) {
      map.put("prompt_cache_key", promptCacheKey);
    }
    if (serviceTier != null) {
      map.put("service_tier", serviceTier);
    }
    if (promptCacheRetention != null) {
      map.put("prompt_cache_retention", promptCacheRetention);
    }
    if (previousResponseId != null) {
      map.put("previous_response_id", previousResponseId);
    }
    if (model != null) {
      map.put("model", model);
    }
    if (reasoning != null) {
      map.put("reasoning", reasoning);
    }
    if (background != null) {
      map.put("background", background);
    }
    if (maxToolCalls != null) {
      map.put("max_tool_calls", maxToolCalls);
    }
    if (text != null) {
      map.put("text", text);
    }
    if (tools != null) {
      map.put("tools", tools);
    }
    if (toolChoice != null) {
      map.put("tool_choice", toolChoice);
    }
    if (prompt != null) {
      map.put("prompt", prompt);
    }
    if (truncation != null) {
      map.put("truncation", truncation);
    }
    if (input != null) {
      map.put("input", input);
    }
    if (include != null) {
      map.put("include", include);
    }
    if (parallelToolCalls != null) {
      map.put("parallel_tool_calls", parallelToolCalls);
    }
    if (store != null) {
      map.put("store", store);
    }
    if (instructions != null) {
      map.put("instructions", instructions);
    }
    if (stream != null) {
      map.put("stream", stream);
    }
    if (streamOptions != null) {
      map.put("stream_options", streamOptions);
    }
    if (conversation != null) {
      map.put("conversation", conversation);
    }
    if (contextManagement != null) {
      map.put("context_management", contextManagement);
    }
    if (maxOutputTokens != null) {
      map.put("max_output_tokens", maxOutputTokens);
    }
    return map;
  }
}
