// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public final class CreateConversationBody implements Json.JsonSerializable {
  private Map<String, String> metadata;
  private List<Object> items;

  public Map<String, String> metadata() {
    return metadata;
  }

  public List<Object> items() {
    return items;
  }

  public static CreateConversationBody fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    CreateConversationBody out = new CreateConversationBody();
    out.metadata = Json.mapValues(map.get("metadata"), __e -> Json.asString(__e));
    out.items = Json.mapList(map.get("items"), __e -> InputItem.fromJson(__e));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    if (metadata != null) {
      map.put("metadata", metadata);
    }
    if (items != null) {
      map.put("items", items);
    }
    return map;
  }
}
