// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

/**
 * A dependency-free assertion test for EmbeddingService — run with plain `java EmbeddingServiceTest`.
 */
public final class EmbeddingServiceTest {
  private static final String BASE_URL =
      System.getenv().getOrDefault("TEST_API_BASE_URL", "http://localhost:4010");

  public static void main(String[] args) {
    Client client = Client.builder().baseUrl(BASE_URL).apiKey("My API Key").build();
    testEmbeddingCreateWithOptionalParams(client);
    System.out.println("EmbeddingServiceTest OK");
  }

  private static void testEmbeddingCreateWithOptionalParams(Client client) {
    try {
      client.embeddings().create(EmbeddingCreateParams.builder()
          .input("x")
          .model("x")
          .encodingFormat(CreateEmbeddingRequestEncodingFormat.FLOAT)
          .dimensions(0L)
          .user("x")
          .build());
    } catch (ApiException expected) {
      // Offline: no mock server answering — a transport/HTTP error is acceptable here.
    }
  }
}
