// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.Optional;

/** Parameters for list: Get a list of runs for an evaluation. */
public final class EvalRunListParams {
  private final String after;
  private final Long limit;
  private final EvalsRunsListOrder order;
  private final EvalsRunsListStatus status;

  private EvalRunListParams(Builder builder) {
    this.after = builder.after;
    this.limit = builder.limit;
    this.order = builder.order;
    this.status = builder.status;
  }

  public static Builder builder() {
    return new Builder();
  }

  public Optional<String> after() {
    return Optional.ofNullable(after);
  }

  public Optional<Long> limit() {
    return Optional.ofNullable(limit);
  }

  public Optional<EvalsRunsListOrder> order() {
    return Optional.ofNullable(order);
  }

  public Optional<EvalsRunsListStatus> status() {
    return Optional.ofNullable(status);
  }

  public static final class Builder {
    private String after;
    private Long limit;
    private EvalsRunsListOrder order;
    private EvalsRunsListStatus status;

    public Builder after(String after) {
      this.after = after;
      return this;
    }

    public Builder limit(Long limit) {
      this.limit = limit;
      return this;
    }

    public Builder order(EvalsRunsListOrder order) {
      this.order = order;
      return this;
    }

    public Builder status(EvalsRunsListStatus status) {
      this.status = status;
      return this;
    }

    public EvalRunListParams build() {
      return new EvalRunListParams(this);
    }
  }
}
