// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

public final class EvalJsonlFileContentSourceContentItem implements Json.JsonSerializable {
  private Map<String, Object> item;
  private Map<String, Object> sample;

  public Map<String, Object> item() {
    return item;
  }

  public Map<String, Object> sample() {
    return sample;
  }

  public static EvalJsonlFileContentSourceContentItem fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    EvalJsonlFileContentSourceContentItem out = new EvalJsonlFileContentSourceContentItem();
    out.item = Json.mapValues(map.get("item"), __e -> __e);
    out.sample = Json.mapValues(map.get("sample"), __e -> __e);
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("item", item);
    if (sample != null) {
      map.put("sample", sample);
    }
    return map;
  }
}
