// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

/** Attachment source referenced by an annotation. */
public final class FileAnnotationSource implements Json.JsonSerializable {
  private String type;
  private String filename;

  public String type() {
    return type;
  }

  public String filename() {
    return filename;
  }

  public static FileAnnotationSource fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    FileAnnotationSource out = new FileAnnotationSource();
    out.type = Json.asString(map.get("type"));
    out.filename = Json.asString(map.get("filename"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("type", type != null ? type : "file");
    map.put("filename", filename);
    return map;
  }
}
