// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

/** The method used for fine-tuning. */
public final class FineTuneMethod implements Json.JsonSerializable {
  private FineTuneMethodType type;
  private FineTuneSupervisedMethod supervised;
  private FineTuneDpoMethod dpo;
  private FineTuneReinforcementMethod reinforcement;

  public FineTuneMethodType type() {
    return type;
  }

  public FineTuneSupervisedMethod supervised() {
    return supervised;
  }

  public FineTuneDpoMethod dpo() {
    return dpo;
  }

  public FineTuneReinforcementMethod reinforcement() {
    return reinforcement;
  }

  public static FineTuneMethod fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    FineTuneMethod out = new FineTuneMethod();
    out.type = FineTuneMethodType.fromJson(map.get("type"));
    out.supervised = FineTuneSupervisedMethod.fromJson(map.get("supervised"));
    out.dpo = FineTuneDpoMethod.fromJson(map.get("dpo"));
    out.reinforcement = FineTuneReinforcementMethod.fromJson(map.get("reinforcement"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("type", type);
    if (supervised != null) {
      map.put("supervised", supervised);
    }
    if (dpo != null) {
      map.put("dpo", dpo);
    }
    if (reinforcement != null) {
      map.put("reinforcement", reinforcement);
    }
    return map;
  }
}
