// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

/** The quality of the image generated. Either `low`, `medium`, or `high`. */
public enum ImagesResponseQuality implements Json.JsonEnum {
  LOW("low"),
  MEDIUM("medium"),
  HIGH("high");

  private final String value;

  ImagesResponseQuality(String value) {
    this.value = value;
  }

  public String value() {
    return value;
  }

  @Override
  public Object jsonValue() {
    return value;
  }

  public static ImagesResponseQuality fromValue(String value) {
    for (ImagesResponseQuality item : values()) {
      if (item.value.equals(value)) {
        return item;
      }
    }
    throw new IllegalArgumentException("unknown ImagesResponseQuality value: " + value);
  }

  public static ImagesResponseQuality fromJson(Object json) {
    return json == null ? null : fromValue(Json.asString(json));
  }
}
