// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

/** Represents a project rate limit config. */
public final class ProjectRateLimit implements Json.JsonSerializable {
  private String object;
  private String id;
  private String model;
  private Long maxRequestsPer1Minute;
  private Long maxTokensPer1Minute;
  private Long maxImagesPer1Minute;
  private Long maxAudioMegabytesPer1Minute;
  private Long maxRequestsPer1Day;
  private Long batch1DayMaxInputTokens;

  public String object() {
    return object;
  }

  public String id() {
    return id;
  }

  public String model() {
    return model;
  }

  public Long maxRequestsPer1Minute() {
    return maxRequestsPer1Minute;
  }

  public Long maxTokensPer1Minute() {
    return maxTokensPer1Minute;
  }

  public Long maxImagesPer1Minute() {
    return maxImagesPer1Minute;
  }

  public Long maxAudioMegabytesPer1Minute() {
    return maxAudioMegabytesPer1Minute;
  }

  public Long maxRequestsPer1Day() {
    return maxRequestsPer1Day;
  }

  public Long batch1DayMaxInputTokens() {
    return batch1DayMaxInputTokens;
  }

  public static ProjectRateLimit fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    ProjectRateLimit out = new ProjectRateLimit();
    out.object = Json.asString(map.get("object"));
    out.id = Json.asString(map.get("id"));
    out.model = Json.asString(map.get("model"));
    out.maxRequestsPer1Minute = Json.asLong(map.get("max_requests_per_1_minute"));
    out.maxTokensPer1Minute = Json.asLong(map.get("max_tokens_per_1_minute"));
    out.maxImagesPer1Minute = Json.asLong(map.get("max_images_per_1_minute"));
    out.maxAudioMegabytesPer1Minute = Json.asLong(map.get("max_audio_megabytes_per_1_minute"));
    out.maxRequestsPer1Day = Json.asLong(map.get("max_requests_per_1_day"));
    out.batch1DayMaxInputTokens = Json.asLong(map.get("batch_1_day_max_input_tokens"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("object", object != null ? object : "project.rate_limit");
    map.put("id", id);
    map.put("model", model);
    map.put("max_requests_per_1_minute", maxRequestsPer1Minute);
    map.put("max_tokens_per_1_minute", maxTokensPer1Minute);
    if (maxImagesPer1Minute != null) {
      map.put("max_images_per_1_minute", maxImagesPer1Minute);
    }
    if (maxAudioMegabytesPer1Minute != null) {
      map.put("max_audio_megabytes_per_1_minute", maxAudioMegabytesPer1Minute);
    }
    if (maxRequestsPer1Day != null) {
      map.put("max_requests_per_1_day", maxRequestsPer1Day);
    }
    if (batch1DayMaxInputTokens != null) {
      map.put("batch_1_day_max_input_tokens", batch1DayMaxInputTokens);
    }
    return map;
  }
}
