// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

/** Configuration for translation input and output audio. */
public final class RealtimeTranslationSessionCreateRequestAudio implements Json.JsonSerializable {
  private RealtimeTranslationSessionCreateRequestAudioInput input;
  private RealtimeTranslationSessionCreateRequestAudioOutput output;

  public RealtimeTranslationSessionCreateRequestAudioInput input() {
    return input;
  }

  public RealtimeTranslationSessionCreateRequestAudioOutput output() {
    return output;
  }

  public static RealtimeTranslationSessionCreateRequestAudio fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    RealtimeTranslationSessionCreateRequestAudio out = new RealtimeTranslationSessionCreateRequestAudio();
    out.input = RealtimeTranslationSessionCreateRequestAudioInput.fromJson(map.get("input"));
    out.output = RealtimeTranslationSessionCreateRequestAudioOutput.fromJson(map.get("output"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    if (input != null) {
      map.put("input", input);
    }
    if (output != null) {
      map.put("output", output);
    }
    return map;
  }
}
