// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Parameters required to transfer a SIP call to a new destination using the
 * Realtime API.
 */
public final class RealtimeCallReferRequest implements Json.JsonSerializable {
  private String targetUri;

  public String targetUri() {
    return targetUri;
  }

  public static RealtimeCallReferRequest fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    RealtimeCallReferRequest out = new RealtimeCallReferRequest();
    out.targetUri = Json.asString(map.get("target_uri"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("target_uri", targetUri);
    return map;
  }
}
