// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** For now, this is always going to be an empty object. */
public final class RunStepDetailsToolCallsFileSearchObjectFileSearch implements Json.JsonSerializable {
  private RunStepDetailsToolCallsFileSearchRankingOptionsObject rankingOptions;
  private List<RunStepDetailsToolCallsFileSearchResultObject> results;

  public RunStepDetailsToolCallsFileSearchRankingOptionsObject rankingOptions() {
    return rankingOptions;
  }

  public List<RunStepDetailsToolCallsFileSearchResultObject> results() {
    return results;
  }

  public static RunStepDetailsToolCallsFileSearchObjectFileSearch fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    RunStepDetailsToolCallsFileSearchObjectFileSearch out = new RunStepDetailsToolCallsFileSearchObjectFileSearch();
    out.rankingOptions = RunStepDetailsToolCallsFileSearchRankingOptionsObject.fromJson(map.get("ranking_options"));
    out.results = Json.mapList(map.get("results"), __e -> RunStepDetailsToolCallsFileSearchResultObject.fromJson(__e));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    if (rankingOptions != null) {
      map.put("ranking_options", rankingOptions);
    }
    if (results != null) {
      map.put("results", results);
    }
    return map;
  }
}
