// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

/** Use this option to force the model to call a specific custom tool. */
public final class ToolChoiceCustom implements Json.JsonSerializable {
  private String type;
  private String name;

  public String type() {
    return type;
  }

  public String name() {
    return name;
  }

  public static ToolChoiceCustom fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    ToolChoiceCustom out = new ToolChoiceCustom();
    out.type = Json.asString(map.get("type"));
    out.name = Json.asString(map.get("name"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("type", type != null ? type : "custom");
    map.put("name", name);
    return map;
  }
}
