// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

public enum ToolSearchExecutionType implements Json.JsonEnum {
  SERVER("server"),
  CLIENT("client");

  private final String value;

  ToolSearchExecutionType(String value) {
    this.value = value;
  }

  public String value() {
    return value;
  }

  @Override
  public Object jsonValue() {
    return value;
  }

  public static ToolSearchExecutionType fromValue(String value) {
    for (ToolSearchExecutionType item : values()) {
      if (item.value.equals(value)) {
        return item;
      }
    }
    throw new IllegalArgumentException("unknown ToolSearchExecutionType value: " + value);
  }

  public static ToolSearchExecutionType fromJson(Object json) {
    return json == null ? null : fromValue(Json.asString(json));
  }
}
