// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

/** Details about the input tokens billed for this request. */
public final class TranscriptTextUsageTokensInputTokenDetails implements Json.JsonSerializable {
  private Long textTokens;
  private Long audioTokens;

  public Long textTokens() {
    return textTokens;
  }

  public Long audioTokens() {
    return audioTokens;
  }

  public static TranscriptTextUsageTokensInputTokenDetails fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    TranscriptTextUsageTokensInputTokenDetails out = new TranscriptTextUsageTokensInputTokenDetails();
    out.textTokens = Json.asLong(map.get("text_tokens"));
    out.audioTokens = Json.asLong(map.get("audio_tokens"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    if (textTokens != null) {
      map.put("text_tokens", textTokens);
    }
    if (audioTokens != null) {
      map.put("audio_tokens", audioTokens);
    }
    return map;
  }
}
