// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

public final class UploadPartService {
  private final Transport transport;

  UploadPartService(Transport transport) {
    this.transport = transport;
  }

  /**
   * Adds a [Part](/docs/api-reference/uploads/part-object) to an [Upload](/docs/api-reference/uploads/object) object. A Part represents a chunk of bytes from the file you are trying to upload.
   * 
   * Each Part can be at most 64 MB, and you can add Parts until you hit the Upload maximum of 8 GB.
   * 
   * It is possible to add multiple Parts in parallel. You can decide the intended order of the Parts when you [complete the Upload](/docs/api-reference/uploads/complete).
   */
  public UploadPart create(String uploadId, UploadPartCreateParams params) {
    if (uploadId == null || uploadId.isEmpty()) {
      throw new IllegalArgumentException("missing required upload_id parameter");
    }
    Transport.Request request = new Transport.Request("POST", "/uploads/" + Transport.encodePath(uploadId) + "/parts");
    Map<String, Object> body = new LinkedHashMap<>();
    body.put("data", params.data());
    request.body(body);
    request.encoding("multipart");
    return UploadPart.fromJson(transport.execute(request));
  }
}
