// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** User-authored messages within a thread. */
public final class UserMessageItem implements Json.JsonSerializable {
  private String id;
  private String object;
  private Long createdAt;
  private String threadId;
  private String type;
  private List<Object> content;
  private List<Attachment> attachments;
  private InferenceOptions inferenceOptions;

  public String id() {
    return id;
  }

  public String object() {
    return object;
  }

  public Long createdAt() {
    return createdAt;
  }

  public String threadId() {
    return threadId;
  }

  public String type() {
    return type;
  }

  public List<Object> content() {
    return content;
  }

  public List<Attachment> attachments() {
    return attachments;
  }

  public InferenceOptions inferenceOptions() {
    return inferenceOptions;
  }

  public static UserMessageItem fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    UserMessageItem out = new UserMessageItem();
    out.id = Json.asString(map.get("id"));
    out.object = Json.asString(map.get("object"));
    out.createdAt = Json.asLong(map.get("created_at"));
    out.threadId = Json.asString(map.get("thread_id"));
    out.type = Json.asString(map.get("type"));
    out.content = Json.mapList(map.get("content"), __e -> UserMessageItemContentItem.fromJson(__e));
    out.attachments = Json.mapList(map.get("attachments"), __e -> Attachment.fromJson(__e));
    out.inferenceOptions = InferenceOptions.fromJson(map.get("inference_options"));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("id", id);
    map.put("object", object != null ? object : "chatkit.thread_item");
    map.put("created_at", createdAt);
    map.put("thread_id", threadId);
    map.put("type", type != null ? type : "chatkit.user_message");
    map.put("content", content);
    map.put("attachments", attachments);
    map.put("inference_options", inferenceOptions);
    return map;
  }
}
