// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

/** The status of the vector store files batch, which can be either `in_progress`, `completed`, `cancelled` or `failed`. */
public enum VectorStoreFileBatchObjectStatus implements Json.JsonEnum {
  IN_PROGRESS("in_progress"),
  COMPLETED("completed"),
  CANCELLED("cancelled"),
  FAILED("failed");

  private final String value;

  VectorStoreFileBatchObjectStatus(String value) {
    this.value = value;
  }

  public String value() {
    return value;
  }

  @Override
  public Object jsonValue() {
    return value;
  }

  public static VectorStoreFileBatchObjectStatus fromValue(String value) {
    for (VectorStoreFileBatchObjectStatus item : values()) {
      if (item.value.equals(value)) {
        return item;
      }
    }
    throw new IllegalArgumentException("unknown VectorStoreFileBatchObjectStatus value: " + value);
  }

  public static VectorStoreFileBatchObjectStatus fromJson(Object json) {
    return json == null ? null : fromValue(Json.asString(json));
  }
}
