// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.List;
import java.util.Map;
import java.util.Optional;

/** Parameters for create: Create a vector store. */
public final class VectorStoreCreateParams {
  private final List<String> fileIds;
  private final String name;
  private final String description;
  private final VectorStoreExpirationAfter expiresAfter;
  private final Object chunkingStrategy;
  private final Map<String, String> metadata;

  private VectorStoreCreateParams(Builder builder) {
    this.fileIds = builder.fileIds;
    this.name = builder.name;
    this.description = builder.description;
    this.expiresAfter = builder.expiresAfter;
    this.chunkingStrategy = builder.chunkingStrategy;
    this.metadata = builder.metadata;
  }

  public static Builder builder() {
    return new Builder();
  }

  public Optional<List<String>> fileIds() {
    return Optional.ofNullable(fileIds);
  }

  public Optional<String> name() {
    return Optional.ofNullable(name);
  }

  public Optional<String> description() {
    return Optional.ofNullable(description);
  }

  public Optional<VectorStoreExpirationAfter> expiresAfter() {
    return Optional.ofNullable(expiresAfter);
  }

  public Optional<Object> chunkingStrategy() {
    return Optional.ofNullable(chunkingStrategy);
  }

  public Optional<Map<String, String>> metadata() {
    return Optional.ofNullable(metadata);
  }

  public static final class Builder {
    private List<String> fileIds;
    private String name;
    private String description;
    private VectorStoreExpirationAfter expiresAfter;
    private Object chunkingStrategy;
    private Map<String, String> metadata;

    public Builder fileIds(List<String> fileIds) {
      this.fileIds = fileIds;
      return this;
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    public Builder description(String description) {
      this.description = description;
      return this;
    }

    public Builder expiresAfter(VectorStoreExpirationAfter expiresAfter) {
      this.expiresAfter = expiresAfter;
      return this;
    }

    public Builder chunkingStrategy(Object chunkingStrategy) {
      this.chunkingStrategy = chunkingStrategy;
      return this;
    }

    public Builder metadata(Map<String, String> metadata) {
      this.metadata = metadata;
      return this;
    }

    public VectorStoreCreateParams build() {
      return new VectorStoreCreateParams(this);
    }
  }
}
