// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** This tool searches the web for relevant results to use in a response. Learn more about the [web search tool](https://platform.openai.com/docs/guides/tools-web-search). */
public final class WebSearchPreviewTool implements Json.JsonSerializable {
  private WebSearchPreviewToolType type;
  private ApproximateLocation userLocation;
  private SearchContextSize searchContextSize;
  private List<SearchContentType> searchContentTypes;

  public WebSearchPreviewToolType type() {
    return type;
  }

  public ApproximateLocation userLocation() {
    return userLocation;
  }

  public SearchContextSize searchContextSize() {
    return searchContextSize;
  }

  public List<SearchContentType> searchContentTypes() {
    return searchContentTypes;
  }

  public static WebSearchPreviewTool fromJson(Object json) {
    if (json == null) {
      return null;
    }
    @SuppressWarnings("unchecked")
    Map<String, Object> map = (Map<String, Object>) json;
    WebSearchPreviewTool out = new WebSearchPreviewTool();
    out.type = WebSearchPreviewToolType.fromJson(map.get("type"));
    out.userLocation = ApproximateLocation.fromJson(map.get("user_location"));
    out.searchContextSize = SearchContextSize.fromJson(map.get("search_context_size"));
    out.searchContentTypes = Json.mapList(map.get("search_content_types"), __e -> SearchContentType.fromJson(__e));
    return out;
  }

  @Override
  public Map<String, Object> toJsonMap() {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("type", type);
    if (userLocation != null) {
      map.put("user_location", userLocation);
    }
    if (searchContextSize != null) {
      map.put("search_context_size", searchContextSize);
    }
    if (searchContentTypes != null) {
      map.put("search_content_types", searchContentTypes);
    }
    return map;
  }
}
