// Code generated by opensdk. DO NOT EDIT.

package openai

import (
	"context"
	"io"
	"net/http"

	"github.com/example/openai/internal/requestconfig"
	"github.com/example/openai/option"
	"github.com/example/openai/packages/param"
)

// AudioService ...
type AudioService struct {
	Options []option.RequestOption
	Translations AudioTranslationService
}

// NewAudioService constructs a service that shares the client's request options.
func NewAudioService(opts ...option.RequestOption) (r AudioService) {
	r = AudioService{}
	r.Options = opts
	r.Translations = NewAudioTranslationService(opts...)
	return
}

// AudioTranslationService ...
type AudioTranslationService struct {
	Options []option.RequestOption
}

// NewAudioTranslationService constructs a service that shares the client's request options.
func NewAudioTranslationService(opts ...option.RequestOption) (r AudioTranslationService) {
	r = AudioTranslationService{}
	r.Options = opts
	return
}

// Translates audio into English.
func (r *AudioTranslationService) New(ctx context.Context, body AudioTranslationNewParams, opts ...option.RequestOption) (res AudioTranslationsCreateResponse, err error) {
	opts = append(r.Options[:], opts...)
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodPost, "audio/translations", body, opts...)
	if err != nil {
		return
	}
	cfg.Encoding = "multipart"
	err = cfg.Execute(&res)
	return
}

type AudioTranslationNewParams struct {
	File io.Reader `json:"file,required"`
	Model CreateTranslationRequestModel `json:"model,required"`
	Prompt param.Opt[string] `json:"prompt,omitempty"`
	ResponseFormat CreateTranslationRequestResponseFormat `json:"response_format,omitempty"`
	Temperature param.Opt[float64] `json:"temperature,omitempty"`
}
