// Code generated by opensdk. DO NOT EDIT.

import { APIResource } from '../core/resource';
import type { APIClient, RequestOptions } from '../core/request';
import { CursorPage } from '../core/pagination';
import type { AdminOrganizationUsageAudioTranscriptionsListBucketWidth, AdminOrganizationUsageAudioTranscriptionsListGroupByItem, UsageTimeBucket } from '../models';

export class Admin extends APIResource {
  readonly organization: AdminOrganization;

  constructor(client: APIClient) {
    super(client);
    this.organization = new AdminOrganization(client);
  }
}

export class AdminOrganization extends APIResource {
  readonly usage: AdminOrganizationUsage;

  constructor(client: APIClient) {
    super(client);
    this.usage = new AdminOrganizationUsage(client);
  }
}

export class AdminOrganizationUsage extends APIResource {
  readonly audioTranscriptions: AdminOrganizationUsageAudioTranscriptions;

  constructor(client: APIClient) {
    super(client);
    this.audioTranscriptions = new AdminOrganizationUsageAudioTranscriptions(client);
  }
}

export class AdminOrganizationUsageAudioTranscriptions extends APIResource {
  /** Get audio transcriptions usage details for the organization. */
  list(query: AdminOrganizationUsageAudioTranscriptionListParams, options?: RequestOptions): Promise<CursorPage<UsageTimeBucket>> {
    return this._client
      .request<unknown>({ method: "GET", path: "/organization/usage/audio_transcriptions", query }, options)
      .then((raw) => CursorPage.fromResponse<UsageTimeBucket>(raw));
  }
}

export interface AdminOrganizationUsageAudioTranscriptionListParams {
  start_time: number;
  end_time?: number;
  bucket_width?: AdminOrganizationUsageAudioTranscriptionsListBucketWidth;
  project_ids?: string[];
  user_ids?: string[];
  api_key_ids?: string[];
  models?: string[];
  group_by?: AdminOrganizationUsageAudioTranscriptionsListGroupByItem[];
  limit?: number;
  page?: string;
}
