// Code generated by opensdk. DO NOT EDIT.

package openai_test

import (
	"context"
	"errors"
	"os"
	"strings"
	"testing"

	"github.com/example/openai"
	"github.com/example/openai/internal/requestconfig"
	"github.com/example/openai/internal/testutil"
	"github.com/example/openai/option"
	"github.com/example/openai/packages/param"
)

func TestBatchCancel(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.Batches.Cancel(context.TODO(), "batch_id")
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestBatchCancelPathParams(t *testing.T) {
	client := openai.NewClient(
		option.WithBaseURL("http://localhost:4010"),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.Batches.Cancel(context.TODO(), "")
	if err == nil || !strings.Contains(err.Error(), "missing required") {
		t.Fatal("expected a missing required path param error")
	}
}

func TestBatchNewWithOptionalParams(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.Batches.New(
		context.TODO(),
		openai.BatchNewParams{
			InputFileID: "x",
			Endpoint: openai.BatchesCreateRequestEndpointV1Responses,
			CompletionWindow: "24h",
			Metadata: map[string]string{"key": "x"},
			OutputExpiresAfter: openai.BatchFileExpirationAfter{Anchor: "created_at", Seconds: 0},
		},
	)
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestBatchListWithOptionalParams(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.Batches.List(
		context.TODO(),
		openai.BatchListParams{
			After: param.NewOpt[string]("after"),
			Limit: param.NewOpt[int64](0),
		},
	)
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestBatchGet(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.Batches.Get(context.TODO(), "batch_id")
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestBatchGetPathParams(t *testing.T) {
	client := openai.NewClient(
		option.WithBaseURL("http://localhost:4010"),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.Batches.Get(context.TODO(), "")
	if err == nil || !strings.Contains(err.Error(), "missing required") {
		t.Fatal("expected a missing required path param error")
	}
}
