// Code generated by opensdk. DO NOT EDIT.

package openai_test

import (
	"context"
	"errors"
	"os"
	"strings"
	"testing"

	"github.com/example/openai"
	"github.com/example/openai/internal/requestconfig"
	"github.com/example/openai/internal/testutil"
	"github.com/example/openai/option"
	"github.com/example/openai/packages/param"
)

func TestChatCompletionNewWithOptionalParams(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.Chat.Completions.New(
		context.TODO(),
		openai.ChatCompletionNewParams{
			Metadata: map[string]string{"key": "x"},
			TopLogprobs: param.NewOpt[int64](0),
			Temperature: param.NewOpt[float64](0),
			TopP: param.NewOpt[float64](0),
			User: param.NewOpt[string]("x"),
			SafetyIdentifier: param.NewOpt[string]("x"),
			PromptCacheKey: param.NewOpt[string]("x"),
			ServiceTier: openai.ServiceTierAuto,
			PromptCacheRetention: openai.CreateChatCompletionRequestPromptCacheRetentionInMemory,
			Messages: []openai.ChatCompletionRequestMessage{openai.ChatCompletionRequestDeveloperMessage{Content: "x", Role: "developer", Name: "x"}},
			Model: "x",
			Modalities: []openai.ResponseModalitiesItem{openai.ResponseModalitiesItemText},
			Verbosity: openai.VerbosityLow,
			ReasoningEffort: openai.ReasoningEffortNone,
			MaxCompletionTokens: param.NewOpt[int64](0),
			FrequencyPenalty: param.NewOpt[float64](0),
			PresencePenalty: param.NewOpt[float64](0),
			WebSearchOptions: openai.CreateChatCompletionRequestWebSearchOptions{UserLocation: openai.CreateChatCompletionRequestWebSearchOptionsUserLocation{Type: "approximate", Approximate: openai.WebSearchLocation{Country: "x", Region: "x", City: "x", Timezone: "x"}}, SearchContextSize: openai.WebSearchContextSizeLow},
			ResponseFormat: openai.ResponseFormatText{Type: "text"},
			Audio: openai.CreateChatCompletionRequestAudio{Voice: "x", Format: openai.CreateChatCompletionRequestAudioFormatWav},
			Store: param.NewOpt[bool](true),
			Stream: param.NewOpt[bool](true),
			Stop: "x",
			LogitBias: map[string]int64{"key": 0},
			Logprobs: param.NewOpt[bool](true),
			MaxTokens: param.NewOpt[int64](0),
			N: param.NewOpt[int64](0),
			Prediction: openai.PredictionContent{Type: "content", Content: "x"},
			Seed: param.NewOpt[int64](0),
			StreamOptions: openai.ChatCompletionStreamOptions{IncludeUsage: true, IncludeObfuscation: true},
			Tools: []openai.CreateChatCompletionRequestToolsItem{openai.ChatCompletionTool{Type: "function", Function: openai.FunctionObject{Name: "x", Description: "x", Parameters: map[string]any{"key": nil}, Strict: true}}},
			ToolChoice: openai.ChatCompletionToolChoiceOptionToolChoiceModeNone,
			ParallelToolCalls: true,
			FunctionCall: openai.CreateChatCompletionRequestFunctionCallStringNone,
			Functions: []openai.ChatCompletionFunctions{openai.ChatCompletionFunctions{Name: "x", Description: "x", Parameters: map[string]any{"key": nil}}},
		},
	)
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestChatCompletionDelete(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.Chat.Completions.Delete(context.TODO(), "completion_id")
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestChatCompletionDeletePathParams(t *testing.T) {
	client := openai.NewClient(
		option.WithBaseURL("http://localhost:4010"),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.Chat.Completions.Delete(context.TODO(), "")
	if err == nil || !strings.Contains(err.Error(), "missing required") {
		t.Fatal("expected a missing required path param error")
	}
}

func TestChatCompletionListWithOptionalParams(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.Chat.Completions.List(
		context.TODO(),
		openai.ChatCompletionListParams{
			Model: param.NewOpt[string]("model"),
			Metadata: map[string]string{"key": "x"},
			After: param.NewOpt[string]("after"),
			Limit: param.NewOpt[int64](0),
			Order: param.NewOpt[openai.ChatCompletionsListOrder](openai.ChatCompletionsListOrderAsc),
		},
	)
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestChatCompletionGet(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.Chat.Completions.Get(context.TODO(), "completion_id")
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestChatCompletionGetPathParams(t *testing.T) {
	client := openai.NewClient(
		option.WithBaseURL("http://localhost:4010"),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.Chat.Completions.Get(context.TODO(), "")
	if err == nil || !strings.Contains(err.Error(), "missing required") {
		t.Fatal("expected a missing required path param error")
	}
}

func TestChatCompletionUpdate(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.Chat.Completions.Update(
		context.TODO(),
		"completion_id",
		openai.ChatCompletionUpdateParams{
			Metadata: map[string]string{"key": "x"},
		},
	)
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestChatCompletionUpdatePathParams(t *testing.T) {
	client := openai.NewClient(
		option.WithBaseURL("http://localhost:4010"),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.Chat.Completions.Update(
		context.TODO(),
		"",
		openai.ChatCompletionUpdateParams{
			Metadata: map[string]string{"key": "x"},
		},
	)
	if err == nil || !strings.Contains(err.Error(), "missing required") {
		t.Fatal("expected a missing required path param error")
	}
}

func TestChatCompletionMessageListWithOptionalParams(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.Chat.Completions.Messages.List(
		context.TODO(),
		"completion_id",
		openai.ChatCompletionMessageListParams{
			After: param.NewOpt[string]("after"),
			Limit: param.NewOpt[int64](0),
			Order: param.NewOpt[openai.ChatCompletionsMessagesListOrder](openai.ChatCompletionsMessagesListOrderAsc),
		},
	)
	if err != nil {
		var apierr *requestconfig.APIError
		if errors.As(err, &apierr) {
			t.Log(apierr.Error())
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestChatCompletionMessageListPathParams(t *testing.T) {
	client := openai.NewClient(
		option.WithBaseURL("http://localhost:4010"),
		option.WithAPIKey("My API Key"),
	)
	_, err := client.Chat.Completions.Messages.List(context.TODO(), "", openai.ChatCompletionMessageListParams{})
	if err == nil || !strings.Contains(err.Error(), "missing required") {
		t.Fatal("expected a missing required path param error")
	}
}
