// Code generated by opensdk. DO NOT EDIT.

package openai

import (
	"context"
	"io"
	"net/http"

	"github.com/example/openai/internal/requestconfig"
	"github.com/example/openai/option"
)

// AudioService ...
type AudioService struct {
	Options []option.RequestOption
	Voices AudioVoiceService
}

// NewAudioService constructs a service that shares the client's request options.
func NewAudioService(opts ...option.RequestOption) (r AudioService) {
	r = AudioService{}
	r.Options = opts
	r.Voices = NewAudioVoiceService(opts...)
	return
}

// AudioVoiceService ...
type AudioVoiceService struct {
	Options []option.RequestOption
}

// NewAudioVoiceService constructs a service that shares the client's request options.
func NewAudioVoiceService(opts ...option.RequestOption) (r AudioVoiceService) {
	r = AudioVoiceService{}
	r.Options = opts
	return
}

// Create a custom voice you can use for audio output (for example, in Text-to-Speech and the Realtime API). This requires an audio sample and a previously uploaded consent recording.
//
// See the [custom voices guide](/docs/guides/text-to-speech#custom-voices) for requirements and best practices. Custom voices are limited to eligible customers.
func (r *AudioVoiceService) New(ctx context.Context, body AudioVoiceNewParams, opts ...option.RequestOption) (res *VoiceResource, err error) {
	opts = append(r.Options[:], opts...)
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodPost, "audio/voices", body, opts...)
	if err != nil {
		return
	}
	cfg.Encoding = "multipart"
	res = &VoiceResource{}
	err = cfg.Execute(res)
	return
}

type AudioVoiceNewParams struct {
	Name string `json:"name,required"`
	AudioSample io.Reader `json:"audio_sample,required"`
	Consent string `json:"consent,required"`
}
