// Code generated by opensdk. DO NOT EDIT.

use std::sync::Arc;

use crate::error::Error;
use crate::models::*;
use crate::transport::{Page, Transport};

pub struct Uploads {
    transport: Arc<Transport>,
}

impl Uploads {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        Uploads { transport }
    }

    /// Creates an intermediate [Upload](/docs/api-reference/uploads/object) object
    /// that you can add [Parts](/docs/api-reference/uploads/part-object) to.
    /// Currently, an Upload can accept at most 8 GB in total and expires after an
    /// hour after you create it.
    ///
    /// Once you complete the Upload, we will create a
    /// [File](/docs/api-reference/files/object) object that contains all the parts
    /// you uploaded. This File is usable in the rest of our platform as a regular
    /// File object.
    ///
    /// For certain `purpose` values, the correct `mime_type` must be specified.
    /// Please refer to documentation for the
    /// [supported MIME types for your use case](/docs/assistants/tools/file-search#supported-files).
    ///
    /// For guidance on the proper filename extensions for each purpose, please
    /// follow the documentation on [creating a
    /// File](/docs/api-reference/files/create).
    ///
    /// Returns the Upload object with status `pending`.
    pub async fn create(&self, params: UploadsCreateParams) -> Result<Upload, Error> {
        let mut req = self.transport.request(reqwest::Method::POST, "/uploads");
        if let Some(value) = &params.filename {
            req = req.json_field("filename", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.purpose {
            req = req.json_field("purpose", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.bytes {
            req = req.json_field("bytes", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.mime_type {
            req = req.json_field("mime_type", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.expires_after {
            req = req.json_field("expires_after", serde_json::to_value(value)?);
        }
        req.send().await
    }
}

#[derive(Debug, Clone, Default)]
pub struct UploadsCreateParams {
    /// The name of the file to upload.
    pub filename: Option<String>,
    /// The intended purpose of the uploaded file.
    ///
    /// See the [documentation on File
    /// purposes](/docs/api-reference/files/create#files-create-purpose).
    pub purpose: Option<CreateUploadRequestPurpose>,
    /// The number of bytes in the file you are uploading.
    pub bytes: Option<i64>,
    /// The MIME type of the file.
    ///
    ///
    /// This must fall within the supported MIME types for your file purpose. See
    /// the supported MIME types for assistants and vision.
    pub mime_type: Option<String>,
    pub expires_after: Option<FileExpirationAfter>,
}
