// Code generated by opensdk. DO NOT EDIT.

package openai

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"

	"github.com/example/openai/internal/requestconfig"
	"github.com/example/openai/option"
)

// UploadService ...
type UploadService struct {
	Options []option.RequestOption
	Parts UploadPartService
}

// NewUploadService constructs a service that shares the client's request options.
func NewUploadService(opts ...option.RequestOption) (r UploadService) {
	r = UploadService{}
	r.Options = opts
	r.Parts = NewUploadPartService(opts...)
	return
}

// UploadPartService ...
type UploadPartService struct {
	Options []option.RequestOption
}

// NewUploadPartService constructs a service that shares the client's request options.
func NewUploadPartService(opts ...option.RequestOption) (r UploadPartService) {
	r = UploadPartService{}
	r.Options = opts
	return
}

// Adds a [Part](/docs/api-reference/uploads/part-object) to an [Upload](/docs/api-reference/uploads/object) object. A Part represents a chunk of bytes from the file you are trying to upload.
//
// Each Part can be at most 64 MB, and you can add Parts until you hit the Upload maximum of 8 GB.
//
// It is possible to add multiple Parts in parallel. You can decide the intended order of the Parts when you [complete the Upload](/docs/api-reference/uploads/complete).
func (r *UploadPartService) New(ctx context.Context, uploadID string, body UploadPartNewParams, opts ...option.RequestOption) (res *UploadPart, err error) {
	opts = append(r.Options[:], opts...)
	if uploadID == "" {
		err = errors.New("missing required upload_id parameter")
		return
	}
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodPost, fmt.Sprintf("uploads/%v/parts", uploadID), body, opts...)
	if err != nil {
		return
	}
	cfg.Encoding = "multipart"
	res = &UploadPart{}
	err = cfg.Execute(res)
	return
}

type UploadPartNewParams struct {
	Data io.Reader `json:"data,required"`
}
