// Code generated by opensdk. DO NOT EDIT.

import { APIResource } from '../core/resource';
import type { APIClient, RequestOptions } from '../core/request';
import { CursorPage } from '../core/pagination';
import type { AdminOrganizationRolesListOrder, Role } from '../models';

export class Admin extends APIResource {
  readonly organization: AdminOrganization;

  constructor(client: APIClient) {
    super(client);
    this.organization = new AdminOrganization(client);
  }
}

export class AdminOrganization extends APIResource {
  readonly roles: AdminOrganizationRoles;

  constructor(client: APIClient) {
    super(client);
    this.roles = new AdminOrganizationRoles(client);
  }
}

export class AdminOrganizationRoles extends APIResource {
  /** Lists the roles configured for the organization. */
  list(query?: AdminOrganizationRoleListParams, options?: RequestOptions): Promise<CursorPage<Role>> {
    return this._client
      .request<unknown>({ method: "GET", path: "/organization/roles", query }, options)
      .then((raw) => CursorPage.fromResponse<Role>(raw));
  }
}

export interface AdminOrganizationRoleListParams {
  limit?: number;
  after?: string;
  order?: AdminOrganizationRolesListOrder;
}
