// Code generated by opensdk. DO NOT EDIT.

import { APIResource } from '../core/resource';
import type { APIClient, RequestOptions } from '../core/request';
import type { VideoReferenceInputParam, VideoResource, VideoSeconds } from '../models';

export class Videos extends APIResource {
  readonly extensions: VideosExtensions;

  constructor(client: APIClient) {
    super(client);
    this.extensions = new VideosExtensions(client);
  }
}

export class VideosExtensions extends APIResource {
  /** Create an extension of a completed video. */
  create(body?: VideoExtensionCreateParams, options?: RequestOptions): Promise<VideoResource> {
    return this._client.request<VideoResource>({ method: "POST", path: "/videos/extensions", body }, options);
  }
}

export interface VideoExtensionCreateParams {
  video: VideoReferenceInputParam;
  prompt: string;
  seconds: VideoSeconds;
}
