# Code generated by opensdk. DO NOT EDIT.

module Openai
  module Resources
    class Conversations
      attr_reader :items

      # @api private
      def initialize(transport)
        @transport = transport
        @items = ConversationsItems.new(transport)
      end

      # Create a conversation.
      #
      # @param metadata [Models::Metadata]
      # @param items [Array<Models::InputItem>]
      # @return [Models::ConversationResource]
      def create(metadata: nil, items: nil)
        @transport.request(
          method: :post,
          path: "/conversations",
          body: { "metadata" => metadata, "items" => items }
        )
      end

      # Delete a conversation. Items in the conversation will not be deleted.
      #
      # @param conversation_id [String]
      # @return [Models::DeletedConversationResource]
      def delete(conversation_id)
        raise ArgumentError, "Expected a non-empty value for `conversation_id`" if conversation_id.nil? || conversation_id.to_s.empty?

        @transport.request(
          method: :delete,
          path: "/conversations/#{conversation_id}"
        )
      end

      # Get a conversation
      #
      # @param conversation_id [String]
      # @return [Models::ConversationResource]
      def retrieve(conversation_id)
        raise ArgumentError, "Expected a non-empty value for `conversation_id`" if conversation_id.nil? || conversation_id.to_s.empty?

        @transport.request(
          method: :get,
          path: "/conversations/#{conversation_id}"
        )
      end

      # Update a conversation
      #
      # @param conversation_id [String]
      # @param metadata [Models::Metadata]
      # @return [Models::ConversationResource]
      def update(conversation_id, metadata:)
        raise ArgumentError, "Expected a non-empty value for `conversation_id`" if conversation_id.nil? || conversation_id.to_s.empty?

        @transport.request(
          method: :post,
          path: "/conversations/#{conversation_id}",
          body: { "metadata" => metadata }
        )
      end
    end

    class ConversationsItems
      # @api private
      def initialize(transport)
        @transport = transport
      end

      # Create items in a conversation with the given ID.
      #
      # @param conversation_id [String]
      # @param include [Array<Models::IncludeEnum>]
      # @param items [Array<Models::InputItem>]
      # @return [Page<Models::ConversationItem>]
      def create(conversation_id, include: nil, items:)
        raise ArgumentError, "Expected a non-empty value for `conversation_id`" if conversation_id.nil? || conversation_id.to_s.empty?

        response = @transport.request(
          method: :post,
          path: "/conversations/#{conversation_id}/items",
          query: { "include" => include },
          body: { "items" => items }
        )
        Openai::Page.new(data: (response || {})[:data], has_more: (response || {})[:has_more])
      end

      # Delete an item from a conversation with the given IDs.
      #
      # @param conversation_id [String]
      # @param item_id [String]
      # @return [Models::ConversationResource]
      def delete(conversation_id, item_id)
        raise ArgumentError, "Expected a non-empty value for `conversation_id`" if conversation_id.nil? || conversation_id.to_s.empty?

        raise ArgumentError, "Expected a non-empty value for `item_id`" if item_id.nil? || item_id.to_s.empty?

        @transport.request(
          method: :delete,
          path: "/conversations/#{conversation_id}/items/#{item_id}"
        )
      end

      # List all items for a conversation with the given ID.
      #
      # @param conversation_id [String]
      # @param limit [Integer]
      # @param order [Models::ConversationsItemsListOrder]
      # @param after [String]
      # @param include [Array<Models::IncludeEnum>]
      # @return [Page<Models::ConversationItem>]
      def list(conversation_id, limit: nil, order: nil, after: nil, include: nil)
        raise ArgumentError, "Expected a non-empty value for `conversation_id`" if conversation_id.nil? || conversation_id.to_s.empty?

        response = @transport.request(
          method: :get,
          path: "/conversations/#{conversation_id}/items",
          query: { "limit" => limit, "order" => order, "after" => after, "include" => include }
        )
        Openai::Page.new(data: (response || {})[:data], has_more: (response || {})[:has_more])
      end

      # Get a single item from a conversation with the given IDs.
      #
      # @param conversation_id [String]
      # @param item_id [String]
      # @param include [Array<Models::IncludeEnum>]
      # @return [Models::ConversationItem]
      def retrieve(conversation_id, item_id, include: nil)
        raise ArgumentError, "Expected a non-empty value for `conversation_id`" if conversation_id.nil? || conversation_id.to_s.empty?

        raise ArgumentError, "Expected a non-empty value for `item_id`" if item_id.nil? || item_id.to_s.empty?

        response = @transport.request(
          method: :get,
          path: "/conversations/#{conversation_id}/items/#{item_id}",
          query: { "include" => include }
        )
        Openai::Models::ConversationItem.decode(response)
      end
    end
  end
end
