// Code generated by opensdk. DO NOT EDIT.

import { APIResource } from '../core/resource';
import type { APIClient, RequestOptions } from '../core/request';
import type { DeletedRoleAssignmentResource } from '../models';

export class Projects extends APIResource {
  readonly users: ProjectsUsers;

  constructor(client: APIClient) {
    super(client);
    this.users = new ProjectsUsers(client);
  }
}

export class ProjectsUsers extends APIResource {
  readonly roles: ProjectsUsersRoles;

  constructor(client: APIClient) {
    super(client);
    this.roles = new ProjectsUsersRoles(client);
  }
}

export class ProjectsUsersRoles extends APIResource {
  /** Unassigns a project role from a user within a project. */
  delete(projectId: string, userId: string, roleId: string, options?: RequestOptions): Promise<DeletedRoleAssignmentResource> {
    if (!projectId) {
      throw new Error("missing required project_id parameter");
    }
    if (!userId) {
      throw new Error("missing required user_id parameter");
    }
    if (!roleId) {
      throw new Error("missing required role_id parameter");
    }
    return this._client.request<DeletedRoleAssignmentResource>({ method: "DELETE", path: `/projects/${projectId}/users/${userId}/roles/${roleId}` }, options);
  }
}
