// Code generated by opensdk. DO NOT EDIT.

package openai

import (
	"context"
	"errors"
	"fmt"
	"net/http"

	"github.com/example/openai/internal/requestconfig"
	"github.com/example/openai/option"
)

// FineTuningService ...
type FineTuningService struct {
	Options []option.RequestOption
	Jobs FineTuningJobService
}

// NewFineTuningService constructs a service that shares the client's request options.
func NewFineTuningService(opts ...option.RequestOption) (r FineTuningService) {
	r = FineTuningService{}
	r.Options = opts
	r.Jobs = NewFineTuningJobService(opts...)
	return
}

// FineTuningJobService ...
type FineTuningJobService struct {
	Options []option.RequestOption
}

// NewFineTuningJobService constructs a service that shares the client's request options.
func NewFineTuningJobService(opts ...option.RequestOption) (r FineTuningJobService) {
	r = FineTuningJobService{}
	r.Options = opts
	return
}

// Get info about a fine-tuning job.
//
// [Learn more about fine-tuning](/docs/guides/model-optimization)
func (r *FineTuningJobService) Get(ctx context.Context, fineTuningJobID string, opts ...option.RequestOption) (res *FineTuningJob, err error) {
	opts = append(r.Options[:], opts...)
	if fineTuningJobID == "" {
		err = errors.New("missing required fine_tuning_job_id parameter")
		return
	}
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, fmt.Sprintf("fine_tuning/jobs/%v", fineTuningJobID), nil, opts...)
	if err != nil {
		return
	}
	res = &FineTuningJob{}
	err = cfg.Execute(res)
	return
}
