# Code generated by opensdk. DO NOT EDIT.

from __future__ import annotations

from typing import BinaryIO, Optional, Union

from ._transport import Transport, decode
from .models import *  # noqa: F401,F403


class AudioResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport
        self.transcriptions = AudioTranscriptionsResource(transport)


class AudioTranscriptionsResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def create(self, *, file: Union[bytes, BinaryIO], model: CreateTranscriptionRequestModel, language: Optional[str] = None, prompt: Optional[str] = None, response_format: Optional[AudioResponseFormat] = None, temperature: Optional[float] = None, include: Optional[list[TranscriptionInclude]] = None, timestamp_granularities: Optional[list[CreateTranscriptionRequestTimestampGranularitiesItem]] = None, stream: Optional[bool] = None, chunking_strategy: Optional[CreateTranscriptionRequestChunkingStrategy] = None, known_speaker_names: Optional[list[str]] = None, known_speaker_references: Optional[list[str]] = None) -> AudioTranscriptionsCreateResponse:
        return decode(AudioTranscriptionsCreateResponse, self._transport.request("POST", "/audio/transcriptions", body={"file": file, "model": model, "language": language, "prompt": prompt, "response_format": response_format, "temperature": temperature, "include": include, "timestamp_granularities": timestamp_granularities, "stream": stream, "chunking_strategy": chunking_strategy, "known_speaker_names": known_speaker_names, "known_speaker_references": known_speaker_references}, encoding="multipart"))
