// Code generated by opensdk. DO NOT EDIT.

package openai

import (
	"context"
	"errors"
	"fmt"
	"net/http"

	"github.com/example/openai/internal/requestconfig"
	"github.com/example/openai/option"
)

// SkillService ...
type SkillService struct {
	Options []option.RequestOption
}

// NewSkillService constructs a service that shares the client's request options.
func NewSkillService(opts ...option.RequestOption) (r SkillService) {
	r = SkillService{}
	r.Options = opts
	return
}

// Delete a skill by its ID.
func (r *SkillService) Delete(ctx context.Context, skillID string, opts ...option.RequestOption) (res *DeletedSkillResource, err error) {
	opts = append(r.Options[:], opts...)
	if skillID == "" {
		err = errors.New("missing required skill_id parameter")
		return
	}
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodDelete, fmt.Sprintf("skills/%v", skillID), nil, opts...)
	if err != nil {
		return
	}
	res = &DeletedSkillResource{}
	err = cfg.Execute(res)
	return
}
