// <auto-generated>
//     Code generated by opensdk. DO NOT EDIT.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace Example.Openai;

public sealed class UploadsService
{
    private readonly Transport _transport;

    internal UploadsService(Transport transport)
    {
        _transport = transport;
    }

    /// <summary>
    /// Cancels the Upload. No Parts may be added after an Upload is cancelled.
    /// Returns the Upload object with status `cancelled`.
    /// </summary>
    public async Task<Upload> Cancel(string uploadId, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrEmpty(uploadId))
        {
            throw new ArgumentException("Expected a non-empty value for uploadId.", nameof(uploadId));
        }
        return await _transport.RequestAsync<Upload>(HttpMethod.Post, $"/uploads/{uploadId}/cancel", cancellationToken: cancellationToken).ConfigureAwait(false);
    }
}
