# Code generated by opensdk. DO NOT EDIT.

module Openai
  module Resources
    class Batches
      # @api private
      def initialize(transport)
        @transport = transport
      end

      # Cancels an in-progress batch. The batch will be in status `cancelling` for up to 10 minutes, before changing to `cancelled`, where it will have partial results (if any) available in the output file.
      #
      # @param batch_id [String]
      # @return [Models::Batch]
      def cancel(batch_id)
        raise ArgumentError, "Expected a non-empty value for `batch_id`" if batch_id.nil? || batch_id.to_s.empty?

        @transport.request(
          method: :post,
          path: "/batches/#{batch_id}/cancel"
        )
      end
    end
  end
end
