# Code generated by opensdk. DO NOT EDIT.

from __future__ import annotations

from ._transport import Transport, decode
from .models import *  # noqa: F401,F403


class ProjectsResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport
        self.roles = RolesResource(transport)


class RolesResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def delete(self, project_id: str, role_id: str) -> RoleDeletedResource:
        if not project_id:
            raise ValueError(f"Expected a non-empty value for `project_id` but received {project_id!r}")
        if not role_id:
            raise ValueError(f"Expected a non-empty value for `role_id` but received {role_id!r}")
        return decode(RoleDeletedResource, self._transport.request("DELETE", f"/projects/{project_id}/roles/{role_id}"))
