// <auto-generated>
//     Code generated by opensdk. DO NOT EDIT.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace Example.Openai;

public sealed class RealtimeService
{
    private readonly Transport _transport;
    public RealtimeSessionsService Sessions { get; }

    internal RealtimeService(Transport transport)
    {
        _transport = transport;
        Sessions = new RealtimeSessionsService(transport);
    }
}

public sealed class RealtimeSessionsService
{
    private readonly Transport _transport;

    internal RealtimeSessionsService(Transport transport)
    {
        _transport = transport;
    }

    /// <summary>
    /// Create an ephemeral API token for use in client-side applications with the
    /// Realtime API. Can be configured with the same session parameters as the
    /// `session.update` client event.
    /// It responds with a session object, plus a `client_secret` key which contains
    /// a usable ephemeral API token that can be used to authenticate browser clients
    /// for the Realtime API.
    /// Returns the created Realtime session object, plus an ephemeral key.
    /// </summary>
    public async Task<RealtimeSessionCreateResponse> Create(RealtimeSessionCreateRequest body, CancellationToken cancellationToken = default)
    {
        return await _transport.RequestAsync<RealtimeSessionCreateResponse>(HttpMethod.Post, "/realtime/sessions", body: body, cancellationToken: cancellationToken).ConfigureAwait(false);
    }
}
