// <auto-generated>
//     Code generated by opensdk. DO NOT EDIT.
// </auto-generated>

using System;
using System.Net.Http;

namespace Example.WireKitchen;

/// <summary>Wire Kitchen API client.</summary>
public sealed class WireKitchenClient
{
    private readonly Transport _transport;
    public FilesService Files { get; }
    public TokensService Tokens { get; }

    /// <summary>Creates a client. When apiKey is null the credential is read from the WIRE_API_KEY environment variable.</summary>
    public WireKitchenClient(string? apiKey = null, string? baseUrl = null, HttpClient? httpClient = null)
    {
        apiKey ??= Environment.GetEnvironmentVariable("WIRE_API_KEY");
        _transport = new Transport(baseUrl ?? "https://api.wire.test/v1", apiKey, httpClient);
        Files = new FilesService(_transport);
        Tokens = new TokensService(_transport);
    }
}
