// <auto-generated>
//     Code generated by opensdk. DO NOT EDIT.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace Example.Openai;

public sealed class ModelsService
{
    private readonly Transport _transport;

    internal ModelsService(Transport transport)
    {
        _transport = transport;
    }

    /// <summary>Retrieves a model instance, providing basic information about the model such as the owner and permissioning.</summary>
    public async Task<Model> Retrieve(string model, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrEmpty(model))
        {
            throw new ArgumentException("Expected a non-empty value for model.", nameof(model));
        }
        return await _transport.RequestAsync<Model>(HttpMethod.Get, $"/models/{model}", cancellationToken: cancellationToken).ConfigureAwait(false);
    }
}
