// Code generated by opensdk. DO NOT EDIT.

import { APIResource } from '../core/resource';
import type { APIClient, RequestOptions } from '../core/request';
import type { DeletedSkillVersionResource } from '../models';

export class Skills extends APIResource {
  readonly versions: SkillsVersions;

  constructor(client: APIClient) {
    super(client);
    this.versions = new SkillsVersions(client);
  }
}

export class SkillsVersions extends APIResource {
  /** Delete a skill version. */
  delete(skillId: string, version: string, options?: RequestOptions): Promise<DeletedSkillVersionResource> {
    if (!skillId) {
      throw new Error("missing required skill_id parameter");
    }
    if (!version) {
      throw new Error("missing required version parameter");
    }
    return this._client.request<DeletedSkillVersionResource>({ method: "DELETE", path: `/skills/${skillId}/versions/${version}` }, options);
  }
}
