// Code generated by opensdk. DO NOT EDIT.

import { APIResource } from '../core/resource';
import type { RequestOptions } from '../core/request';
import type { ConversationResource, InputItem, Metadata } from '../models';

export class Conversations extends APIResource {
  /** Create a conversation. */
  create(body?: ConversationCreateParams, options?: RequestOptions): Promise<ConversationResource> {
    return this._client.request<ConversationResource>({ method: "POST", path: "/conversations", body }, options);
  }
}

export interface ConversationCreateParams {
  metadata?: Metadata | null;
  items?: InputItem[] | null;
}
