// Code generated by opensdk. DO NOT EDIT.

import { APIResource } from '../core/resource';
import type { APIClient, RequestOptions } from '../core/request';
import type { SkillVersionResource } from '../models';

export class Skills extends APIResource {
  readonly versions: SkillsVersions;

  constructor(client: APIClient) {
    super(client);
    this.versions = new SkillsVersions(client);
  }
}

export class SkillsVersions extends APIResource {
  /** Get a specific skill version. */
  retrieve(skillId: string, version: string, options?: RequestOptions): Promise<SkillVersionResource> {
    if (!skillId) {
      throw new Error("missing required skill_id parameter");
    }
    if (!version) {
      throw new Error("missing required version parameter");
    }
    return this._client.request<SkillVersionResource>({ method: "GET", path: `/skills/${skillId}/versions/${version}` }, options);
  }
}
