# Code generated by opensdk. DO NOT EDIT.

from __future__ import annotations

from ._transport import Transport, decode
from .models import *  # noqa: F401,F403


class AdminResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport
        self.organization = AdminOrganizationResource(transport)


class AdminOrganizationResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport
        self.projects = AdminOrganizationProjectsResource(transport)


class AdminOrganizationProjectsResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport
        self.groups = AdminOrganizationProjectsGroupsResource(transport)


class AdminOrganizationProjectsGroupsResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def delete(self, project_id: str, group_id: str) -> ProjectGroupDeletedResource:
        if not project_id:
            raise ValueError(f"Expected a non-empty value for `project_id` but received {project_id!r}")
        if not group_id:
            raise ValueError(f"Expected a non-empty value for `group_id` but received {group_id!r}")
        return decode(ProjectGroupDeletedResource, self._transport.request("DELETE", f"/organization/projects/{project_id}/groups/{group_id}"))
