// Code generated by opensdk. DO NOT EDIT.

import { APIResource } from '../core/resource';
import type { APIClient, RequestOptions } from '../core/request';
import type { ChunkingStrategyRequestParam, VectorStoreFileAttributes, VectorStoreFileObject } from '../models';

export class VectorStores extends APIResource {
  readonly files: VectorStoresFiles;

  constructor(client: APIClient) {
    super(client);
    this.files = new VectorStoresFiles(client);
  }
}

export class VectorStoresFiles extends APIResource {
  /**
   * This endpoint is subject to a per-vector-store write rate limit of 300 requests per minute, shared with `/vector_stores/{vector_store_id}/file_batches`.
   * For uploading multiple files to the same vector store, use the file batches endpoint to reduce request volume.
   */
  create(vectorStoreId: string, body: VectorStoreFileCreateParams, options?: RequestOptions): Promise<VectorStoreFileObject> {
    if (!vectorStoreId) {
      throw new Error("missing required vector_store_id parameter");
    }
    return this._client.request<VectorStoreFileObject>({ method: "POST", path: `/vector_stores/${vectorStoreId}/files`, body }, options);
  }
}

export interface VectorStoreFileCreateParams {
  file_id: string;
  chunking_strategy?: ChunkingStrategyRequestParam;
  attributes?: VectorStoreFileAttributes;
}
