// Code generated by opensdk. DO NOT EDIT.

package com.example.openai;

import java.util.LinkedHashMap;
import java.util.Map;

public final class AdminOrganizationUserService {
  private final Transport transport;

  AdminOrganizationUserService(Transport transport) {
    this.transport = transport;
  }

  /** Modifies a user's role in the organization. */
  public User update(String userId, AdminOrganizationUserUpdateParams params) {
    if (userId == null || userId.isEmpty()) {
      throw new IllegalArgumentException("missing required user_id parameter");
    }
    Transport.Request request = new Transport.Request("POST", "/organization/users/" + Transport.encodePath(userId));
    Map<String, Object> body = new LinkedHashMap<>();
    params.role().ifPresent(value -> body.put("role", value));
    params.roleId().ifPresent(value -> body.put("role_id", value));
    params.technicalLevel().ifPresent(value -> body.put("technical_level", value));
    params.developerPersona().ifPresent(value -> body.put("developer_persona", value));
    request.body(body);
    return User.fromJson(transport.execute(request));
  }
}
