// Code generated by opensdk. DO NOT EDIT.

import { APIResource } from '../core/resource';
import type { RequestOptions } from '../core/request';
import { CursorPage } from '../core/pagination';
import type { VectorStoreSearchRequestFilters, VectorStoreSearchRequestQuery, VectorStoreSearchRequestRankingOptions, VectorStoreSearchResultItem } from '../models';

export class VectorStores extends APIResource {
  /** Search a vector store for relevant chunks based on a query and file attributes filter. */
  search(vectorStoreId: string, body: VectorStoreSearchParams, options?: RequestOptions): Promise<CursorPage<VectorStoreSearchResultItem>> {
    if (!vectorStoreId) {
      throw new Error("missing required vector_store_id parameter");
    }
    return this._client
      .request<unknown>({ method: "POST", path: `/vector_stores/${vectorStoreId}/search`, body }, options)
      .then((raw) => CursorPage.fromResponse<VectorStoreSearchResultItem>(raw));
  }
}

export interface VectorStoreSearchParams {
  query: VectorStoreSearchRequestQuery;
  rewrite_query?: boolean;
  max_num_results?: number;
  filters?: VectorStoreSearchRequestFilters;
  ranking_options?: VectorStoreSearchRequestRankingOptions;
}
