# Code generated by opensdk. DO NOT EDIT.

from __future__ import annotations

from ._transport import Transport, decode
from .models import *  # noqa: F401,F403


class AdminResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport
        self.organization = AdminOrganizationResource(transport)


class AdminOrganizationResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport
        self.admin_api_keys = AdminOrganizationAdminApiKeysResource(transport)


class AdminOrganizationAdminApiKeysResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def create(self, *, name: str) -> AdminApiKeyCreateResponse:
        return decode(AdminApiKeyCreateResponse, self._transport.request("POST", "/organization/admin_api_keys", body={"name": name}))
