# Code generated by opensdk. DO NOT EDIT.

from __future__ import annotations

from ._transport import Transport, decode
from .models import *  # noqa: F401,F403


class UploadsResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def cancel(self, upload_id: str) -> Upload:
        return decode(Upload, self._transport.request("POST", f"/uploads/{upload_id}/cancel"))
