// Code generated by opensdk. DO NOT EDIT.

use std::sync::Arc;

use crate::error::Error;
use crate::models::*;
use crate::transport::{Page, Transport};

pub struct Files {
    transport: Arc<Transport>,
}

impl Files {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        Files { transport }
    }

    /// Returns the contents of the specified file.
    pub async fn content(&self, file_id: &str) -> Result<String, Error> {
        if file_id.is_empty() {
            return Err(Error::InvalidArgument("file_id".to_string()));
        }

        let req = self.transport.request(reqwest::Method::GET, format!("/files/{}/content", file_id));
        req.send().await
    }

    /// Upload a file that can be used across various endpoints. Individual files
    /// can be up to 512 MB, and each project can store up to 2.5 TB of files in
    /// total. There is no organization-wide storage limit. Uploads to this
    /// endpoint are rate-limited to 1,000 requests per minute per authenticated
    /// user.
    ///
    /// - The Assistants API supports files up to 2 million tokens and of specific
    /// file types. See the [Assistants Tools guide](/docs/assistants/tools) for
    /// details.
    /// - The Fine-tuning API only supports `.jsonl` files. The input also has
    /// certain required formats for fine-tuning
    /// [chat](/docs/api-reference/fine-tuning/chat-input) or
    /// [completions](/docs/api-reference/fine-tuning/completions-input) models.
    /// - The Batch API only supports `.jsonl` files up to 200 MB in size. The input
    /// also has a specific required
    /// [format](/docs/api-reference/batch/request-input).
    /// - For Retrieval or `file_search` ingestion, upload files here first. If
    /// you need to attach multiple uploaded files to the same vector store, use
    /// [`/vector_stores/{vector_store_id}/file_batches`](/docs/api-reference/vector-stores-file-batches/createBatch)
    /// instead of attaching them one by one. Vector store attachment has separate
    /// limits from file upload, including 2,000 attached files per minute per
    /// organization.
    ///
    /// Please [contact us](https://help.openai.com/) if you need to increase these
    /// storage limits.
    pub async fn create(&self, params: FilesCreateParams) -> Result<OpenAiFile, Error> {
        let mut req = self.transport.request(reqwest::Method::POST, "/files");
        if let Some(value) = &params.file {
            req = req.multipart_file("file", value.clone());
        }
        if let Some(value) = &params.purpose {
            req = req.multipart_json("purpose", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.expires_after {
            req = req.multipart_json("expires_after", serde_json::to_value(value)?);
        }
        req.send().await
    }

    /// Delete a file and remove it from all vector stores.
    pub async fn delete(&self, file_id: &str) -> Result<DeleteFileResponse, Error> {
        if file_id.is_empty() {
            return Err(Error::InvalidArgument("file_id".to_string()));
        }

        let req = self.transport.request(reqwest::Method::DELETE, format!("/files/{}", file_id));
        req.send().await
    }

    /// Returns a list of files.
    pub async fn list(&self, params: FilesListParams) -> Result<Page<OpenAiFile>, Error> {
        let mut req = self.transport.request(reqwest::Method::GET, "/files");
        if let Some(value) = &params.purpose {
            req = req.query("purpose", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.limit {
            req = req.query("limit", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.order {
            req = req.query("order", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.after {
            req = req.query("after", serde_json::to_value(value)?);
        }
        let value = req.send_value().await?;
        Page::from_value(value, "data", Some("has_more"))
    }

    /// Returns information about a specific file.
    pub async fn retrieve(&self, file_id: &str) -> Result<OpenAiFile, Error> {
        if file_id.is_empty() {
            return Err(Error::InvalidArgument("file_id".to_string()));
        }

        let req = self.transport.request(reqwest::Method::GET, format!("/files/{}", file_id));
        req.send().await
    }
}

#[derive(Debug, Clone, Default)]
pub struct FilesCreateParams {
    /// The File object (not file name) to be uploaded.
    pub file: Option<Vec<u8>>,
    /// The intended purpose of the uploaded file. One of:
    /// - `assistants`: Used in the Assistants API
    /// - `batch`: Used in the Batch API
    /// - `fine-tune`: Used for fine-tuning
    /// - `vision`: Images used for vision fine-tuning
    /// - `user_data`: Flexible file type for any purpose
    /// - `evals`: Used for eval data sets
    pub purpose: Option<CreateFileRequestPurpose>,
    pub expires_after: Option<FileExpirationAfter>,
}

#[derive(Debug, Clone, Default)]
pub struct FilesListParams {
    /// Only return files with the given purpose.
    pub purpose: Option<String>,
    /// A limit on the number of objects to be returned. Limit can range between 1 and 10,000, and the default is 10,000.
    pub limit: Option<i64>,
    /// Sort order by the `created_at` timestamp of the objects. `asc` for ascending order and `desc` for descending order.
    pub order: Option<FilesListOrder>,
    /// A cursor for use in pagination. `after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with obj_foo, your subsequent call can include after=obj_foo in order to fetch the next page of the list.
    pub after: Option<String>,
}
