// Code generated by opensdk. DO NOT EDIT.

use std::sync::Arc;

use crate::error::Error;
use crate::models::*;
use crate::transport::{Page, Transport};

pub struct FineTuning {
    transport: Arc<Transport>,
}

impl FineTuning {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        FineTuning { transport }
    }

    pub fn alpha(&self) -> FineTuningAlpha {
        FineTuningAlpha::new(self.transport.clone())
    }

    pub fn checkpoints(&self) -> FineTuningCheckpoints {
        FineTuningCheckpoints::new(self.transport.clone())
    }

    pub fn jobs(&self) -> FineTuningJobs {
        FineTuningJobs::new(self.transport.clone())
    }
}

pub struct FineTuningAlpha {
    transport: Arc<Transport>,
}

impl FineTuningAlpha {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        FineTuningAlpha { transport }
    }

    pub fn graders(&self) -> FineTuningAlphaGraders {
        FineTuningAlphaGraders::new(self.transport.clone())
    }
}

pub struct FineTuningAlphaGraders {
    transport: Arc<Transport>,
}

impl FineTuningAlphaGraders {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        FineTuningAlphaGraders { transport }
    }

    pub fn run(&self) -> FineTuningAlphaGradersRun {
        FineTuningAlphaGradersRun::new(self.transport.clone())
    }

    pub fn validate(&self) -> FineTuningAlphaGradersValidate {
        FineTuningAlphaGradersValidate::new(self.transport.clone())
    }
}

pub struct FineTuningAlphaGradersRun {
    transport: Arc<Transport>,
}

impl FineTuningAlphaGradersRun {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        FineTuningAlphaGradersRun { transport }
    }

    /// Run a grader.
    pub async fn create(&self, params: FineTuningAlphaGradersRunCreateParams) -> Result<RunGraderResponse, Error> {
        let mut req = self.transport.request(reqwest::Method::POST, "/fine_tuning/alpha/graders/run");
        if let Some(value) = &params.grader {
            req = req.json_field("grader", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.item {
            req = req.json_field("item", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.model_sample {
            req = req.json_field("model_sample", serde_json::to_value(value)?);
        }
        req.send().await
    }
}

#[derive(Debug, Clone, Default)]
pub struct FineTuningAlphaGradersRunCreateParams {
    /// The grader used for the fine-tuning job.
    pub grader: Option<RunGraderRequestGrader>,
    /// The dataset item provided to the grader. This will be used to populate
    /// the `item` namespace. See [the guide](/docs/guides/graders) for more details.
    pub item: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// The model sample to be evaluated. This value will be used to populate
    /// the `sample` namespace. See [the guide](/docs/guides/graders) for more details.
    /// The `output_json` variable will be populated if the model sample is a
    /// valid JSON string.
    pub model_sample: Option<String>,
}

pub struct FineTuningAlphaGradersValidate {
    transport: Arc<Transport>,
}

impl FineTuningAlphaGradersValidate {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        FineTuningAlphaGradersValidate { transport }
    }

    /// Validate a grader.
    pub async fn create(&self, params: FineTuningAlphaGradersValidateCreateParams) -> Result<ValidateGraderResponse, Error> {
        let mut req = self.transport.request(reqwest::Method::POST, "/fine_tuning/alpha/graders/validate");
        if let Some(value) = &params.grader {
            req = req.json_field("grader", serde_json::to_value(value)?);
        }
        req.send().await
    }
}

#[derive(Debug, Clone, Default)]
pub struct FineTuningAlphaGradersValidateCreateParams {
    /// The grader used for the fine-tuning job.
    pub grader: Option<ValidateGraderRequestGrader>,
}

pub struct FineTuningCheckpoints {
    transport: Arc<Transport>,
}

impl FineTuningCheckpoints {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        FineTuningCheckpoints { transport }
    }

    pub fn permissions(&self) -> FineTuningCheckpointsPermissions {
        FineTuningCheckpointsPermissions::new(self.transport.clone())
    }
}

pub struct FineTuningCheckpointsPermissions {
    transport: Arc<Transport>,
}

impl FineTuningCheckpointsPermissions {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        FineTuningCheckpointsPermissions { transport }
    }

    /// **NOTE:** Calling this endpoint requires an [admin API key](../admin-api-keys).
    ///
    /// This enables organization owners to share fine-tuned models with other projects in their organization.
    pub async fn create(&self, fine_tuned_model_checkpoint: &str, params: FineTuningCheckpointsPermissionsCreateParams) -> Result<Page<FineTuningCheckpointPermission>, Error> {
        if fine_tuned_model_checkpoint.is_empty() {
            return Err(Error::InvalidArgument("fine_tuned_model_checkpoint".to_string()));
        }

        let mut req = self.transport.request(reqwest::Method::POST, format!("/fine_tuning/checkpoints/{}/permissions", fine_tuned_model_checkpoint));
        if let Some(value) = &params.project_ids {
            req = req.json_field("project_ids", serde_json::to_value(value)?);
        }
        let value = req.send_value().await?;
        Page::from_value(value, "data", Some("has_more"))
    }

    /// **NOTE:** This endpoint requires an [admin API key](../admin-api-keys).
    ///
    /// Organization owners can use this endpoint to delete a permission for a fine-tuned model checkpoint.
    pub async fn delete(&self, fine_tuned_model_checkpoint: &str, permission_id: &str) -> Result<DeleteFineTuningCheckpointPermissionResponse, Error> {
        if fine_tuned_model_checkpoint.is_empty() {
            return Err(Error::InvalidArgument("fine_tuned_model_checkpoint".to_string()));
        }
        if permission_id.is_empty() {
            return Err(Error::InvalidArgument("permission_id".to_string()));
        }

        let req = self.transport.request(reqwest::Method::DELETE, format!("/fine_tuning/checkpoints/{}/permissions/{}", fine_tuned_model_checkpoint, permission_id));
        req.send().await
    }

    /// **NOTE:** This endpoint requires an [admin API key](../admin-api-keys).
    ///
    /// Organization owners can use this endpoint to view all permissions for a fine-tuned model checkpoint.
    pub async fn list(&self, fine_tuned_model_checkpoint: &str, params: FineTuningCheckpointsPermissionsListParams) -> Result<Page<FineTuningCheckpointPermission>, Error> {
        if fine_tuned_model_checkpoint.is_empty() {
            return Err(Error::InvalidArgument("fine_tuned_model_checkpoint".to_string()));
        }

        let mut req = self.transport.request(reqwest::Method::GET, format!("/fine_tuning/checkpoints/{}/permissions", fine_tuned_model_checkpoint));
        if let Some(value) = &params.project_id {
            req = req.query("project_id", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.after {
            req = req.query("after", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.limit {
            req = req.query("limit", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.order {
            req = req.query("order", serde_json::to_value(value)?);
        }
        let value = req.send_value().await?;
        Page::from_value(value, "data", Some("has_more"))
    }
}

#[derive(Debug, Clone, Default)]
pub struct FineTuningCheckpointsPermissionsCreateParams {
    /// The project identifiers to grant access to.
    pub project_ids: Option<Vec<String>>,
}

#[derive(Debug, Clone, Default)]
pub struct FineTuningCheckpointsPermissionsListParams {
    /// The ID of the project to get permissions for.
    pub project_id: Option<String>,
    /// Identifier for the last permission ID from the previous pagination request.
    pub after: Option<String>,
    /// Number of permissions to retrieve.
    pub limit: Option<i64>,
    /// The order in which to retrieve permissions.
    pub order: Option<FineTuningCheckpointsPermissionsListOrder>,
}

pub struct FineTuningJobs {
    transport: Arc<Transport>,
}

impl FineTuningJobs {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        FineTuningJobs { transport }
    }

    pub fn checkpoints(&self) -> FineTuningJobsCheckpoints {
        FineTuningJobsCheckpoints::new(self.transport.clone())
    }

    /// Immediately cancel a fine-tune job.
    pub async fn cancel(&self, fine_tuning_job_id: &str) -> Result<FineTuningJob, Error> {
        if fine_tuning_job_id.is_empty() {
            return Err(Error::InvalidArgument("fine_tuning_job_id".to_string()));
        }

        let req = self.transport.request(reqwest::Method::POST, format!("/fine_tuning/jobs/{}/cancel", fine_tuning_job_id));
        req.send().await
    }

    /// Creates a fine-tuning job which begins the process of creating a new model from a given dataset.
    ///
    /// Response includes details of the enqueued job including job status and the name of the fine-tuned models once complete.
    ///
    /// [Learn more about fine-tuning](/docs/guides/model-optimization)
    pub async fn create(&self, params: FineTuningJobsCreateParams) -> Result<FineTuningJob, Error> {
        let mut req = self.transport.request(reqwest::Method::POST, "/fine_tuning/jobs");
        if let Some(value) = &params.model {
            req = req.json_field("model", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.training_file {
            req = req.json_field("training_file", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.hyperparameters {
            req = req.json_field("hyperparameters", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.suffix {
            req = req.json_field("suffix", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.validation_file {
            req = req.json_field("validation_file", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.integrations {
            req = req.json_field("integrations", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.seed {
            req = req.json_field("seed", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.method {
            req = req.json_field("method", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.metadata {
            req = req.json_field("metadata", serde_json::to_value(value)?);
        }
        req.send().await
    }

    /// List your organization's fine-tuning jobs
    pub async fn list(&self, params: FineTuningJobsListParams) -> Result<Page<FineTuningJob>, Error> {
        let mut req = self.transport.request(reqwest::Method::GET, "/fine_tuning/jobs");
        if let Some(value) = &params.after {
            req = req.query("after", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.limit {
            req = req.query("limit", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.metadata {
            req = req.query("metadata", serde_json::to_value(value)?);
        }
        let value = req.send_value().await?;
        Page::from_value(value, "data", Some("has_more"))
    }

    /// Get status updates for a fine-tuning job.
    pub async fn list_events(&self, fine_tuning_job_id: &str, params: FineTuningJobsListEventsParams) -> Result<Page<FineTuningJobEvent>, Error> {
        if fine_tuning_job_id.is_empty() {
            return Err(Error::InvalidArgument("fine_tuning_job_id".to_string()));
        }

        let mut req = self.transport.request(reqwest::Method::GET, format!("/fine_tuning/jobs/{}/events", fine_tuning_job_id));
        if let Some(value) = &params.after {
            req = req.query("after", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.limit {
            req = req.query("limit", serde_json::to_value(value)?);
        }
        let value = req.send_value().await?;
        Page::from_value(value, "data", Some("has_more"))
    }

    /// Pause a fine-tune job.
    pub async fn pause(&self, fine_tuning_job_id: &str) -> Result<FineTuningJob, Error> {
        if fine_tuning_job_id.is_empty() {
            return Err(Error::InvalidArgument("fine_tuning_job_id".to_string()));
        }

        let req = self.transport.request(reqwest::Method::POST, format!("/fine_tuning/jobs/{}/pause", fine_tuning_job_id));
        req.send().await
    }

    /// Resume a fine-tune job.
    pub async fn resume(&self, fine_tuning_job_id: &str) -> Result<FineTuningJob, Error> {
        if fine_tuning_job_id.is_empty() {
            return Err(Error::InvalidArgument("fine_tuning_job_id".to_string()));
        }

        let req = self.transport.request(reqwest::Method::POST, format!("/fine_tuning/jobs/{}/resume", fine_tuning_job_id));
        req.send().await
    }

    /// Get info about a fine-tuning job.
    ///
    /// [Learn more about fine-tuning](/docs/guides/model-optimization)
    pub async fn retrieve(&self, fine_tuning_job_id: &str) -> Result<FineTuningJob, Error> {
        if fine_tuning_job_id.is_empty() {
            return Err(Error::InvalidArgument("fine_tuning_job_id".to_string()));
        }

        let req = self.transport.request(reqwest::Method::GET, format!("/fine_tuning/jobs/{}", fine_tuning_job_id));
        req.send().await
    }
}

#[derive(Debug, Clone, Default)]
pub struct FineTuningJobsCreateParams {
    /// The name of the model to fine-tune. You can select one of the
    /// [supported models](/docs/guides/fine-tuning#which-models-can-be-fine-tuned).
    pub model: Option<CreateFineTuningJobRequestModel>,
    /// The ID of an uploaded file that contains training data.
    ///
    /// See [upload file](/docs/api-reference/files/create) for how to upload a file.
    ///
    /// Your dataset must be formatted as a JSONL file. Additionally, you must upload your file with the purpose `fine-tune`.
    ///
    /// The contents of the file should differ depending on if the model uses the [chat](/docs/api-reference/fine-tuning/chat-input), [completions](/docs/api-reference/fine-tuning/completions-input) format, or if the fine-tuning method uses the [preference](/docs/api-reference/fine-tuning/preference-input) format.
    ///
    /// See the [fine-tuning guide](/docs/guides/model-optimization) for more details.
    pub training_file: Option<String>,
    /// The hyperparameters used for the fine-tuning job.
    /// This value is now deprecated in favor of `method`, and should be passed in under the `method` parameter.
    pub hyperparameters: Option<CreateFineTuningJobRequestHyperparameters>,
    /// A string of up to 64 characters that will be added to your fine-tuned model name.
    ///
    /// For example, a `suffix` of "custom-model-name" would produce a model name like `ft:gpt-4o-mini:openai:custom-model-name:7p4lURel`.
    pub suffix: Option<String>,
    /// The ID of an uploaded file that contains validation data.
    ///
    /// If you provide this file, the data is used to generate validation
    /// metrics periodically during fine-tuning. These metrics can be viewed in
    /// the fine-tuning results file.
    /// The same data should not be present in both train and validation files.
    ///
    /// Your dataset must be formatted as a JSONL file. You must upload your file with the purpose `fine-tune`.
    ///
    /// See the [fine-tuning guide](/docs/guides/model-optimization) for more details.
    pub validation_file: Option<String>,
    /// A list of integrations to enable for your fine-tuning job.
    pub integrations: Option<Vec<CreateFineTuningJobRequestIntegrationsItem>>,
    /// The seed controls the reproducibility of the job. Passing in the same seed and job parameters should produce the same results, but may differ in rare cases.
    /// If a seed is not specified, one will be generated for you.
    pub seed: Option<i64>,
    pub method: Option<FineTuneMethod>,
    pub metadata: Option<Metadata>,
}

#[derive(Debug, Clone, Default)]
pub struct FineTuningJobsListParams {
    /// Identifier for the last job from the previous pagination request.
    pub after: Option<String>,
    /// Number of fine-tuning jobs to retrieve.
    pub limit: Option<i64>,
    /// Optional metadata filter. To filter, use the syntax `metadata[k]=v`. Alternatively, set `metadata=null` to indicate no metadata.
    pub metadata: Option<std::collections::HashMap<String, String>>,
}

#[derive(Debug, Clone, Default)]
pub struct FineTuningJobsListEventsParams {
    /// Identifier for the last event from the previous pagination request.
    pub after: Option<String>,
    /// Number of events to retrieve.
    pub limit: Option<i64>,
}

pub struct FineTuningJobsCheckpoints {
    transport: Arc<Transport>,
}

impl FineTuningJobsCheckpoints {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        FineTuningJobsCheckpoints { transport }
    }

    /// List checkpoints for a fine-tuning job.
    pub async fn list(&self, fine_tuning_job_id: &str, params: FineTuningJobsCheckpointsListParams) -> Result<Page<FineTuningJobCheckpoint>, Error> {
        if fine_tuning_job_id.is_empty() {
            return Err(Error::InvalidArgument("fine_tuning_job_id".to_string()));
        }

        let mut req = self.transport.request(reqwest::Method::GET, format!("/fine_tuning/jobs/{}/checkpoints", fine_tuning_job_id));
        if let Some(value) = &params.after {
            req = req.query("after", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.limit {
            req = req.query("limit", serde_json::to_value(value)?);
        }
        let value = req.send_value().await?;
        Page::from_value(value, "data", Some("has_more"))
    }
}

#[derive(Debug, Clone, Default)]
pub struct FineTuningJobsCheckpointsListParams {
    /// Identifier for the last checkpoint ID from the previous pagination request.
    pub after: Option<String>,
    /// Number of checkpoints to retrieve.
    pub limit: Option<i64>,
}
