// Code generated by opensdk. DO NOT EDIT.

use std::sync::Arc;

use crate::error::Error;
use crate::models::*;
use crate::transport::{Page, Transport};

pub struct Images {
    transport: Arc<Transport>,
}

impl Images {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        Images { transport }
    }

    pub fn edits(&self) -> ImagesEdits {
        ImagesEdits::new(self.transport.clone())
    }

    pub fn generations(&self) -> ImagesGenerations {
        ImagesGenerations::new(self.transport.clone())
    }

    pub fn variations(&self) -> ImagesVariations {
        ImagesVariations::new(self.transport.clone())
    }
}

pub struct ImagesEdits {
    transport: Arc<Transport>,
}

impl ImagesEdits {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        ImagesEdits { transport }
    }

    /// You can call this endpoint with either:
    ///
    /// - `multipart/form-data`: use binary uploads via `image` (and optional `mask`).
    /// - `application/json`: use `images` (and optional `mask`) as references with either `image_url` or `file_id`.
    ///
    /// Note that JSON requests use `images` (array) instead of the multipart `image` field.
    pub async fn create(&self, params: ImagesEditsCreateParams) -> Result<ImagesResponse, Error> {
        let mut req = self.transport.request(reqwest::Method::POST, "/images/edits");
        if let Some(value) = &params.model {
            req = req.json_field("model", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.images {
            req = req.json_field("images", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.mask {
            req = req.json_field("mask", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.prompt {
            req = req.json_field("prompt", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.n {
            req = req.json_field("n", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.quality {
            req = req.json_field("quality", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.input_fidelity {
            req = req.json_field("input_fidelity", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.size {
            req = req.json_field("size", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.user {
            req = req.json_field("user", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.output_format {
            req = req.json_field("output_format", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.output_compression {
            req = req.json_field("output_compression", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.moderation {
            req = req.json_field("moderation", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.background {
            req = req.json_field("background", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.stream {
            req = req.json_field("stream", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.partial_images {
            req = req.json_field("partial_images", serde_json::to_value(value)?);
        }
        req.send().await
    }
}

#[derive(Debug, Clone, Default)]
pub struct ImagesEditsCreateParams {
    /// The model to use for image editing.
    pub model: Option<EditImageBodyJsonParamModel>,
    /// Input image references to edit.
    /// For GPT image models, you can provide up to 16 images.
    pub images: Option<Vec<ImageRefParam>>,
    pub mask: Option<ImageRefParam>,
    /// A text description of the desired image edit.
    pub prompt: Option<String>,
    /// The number of edited images to generate.
    pub n: Option<i64>,
    /// Output quality for GPT image models.
    pub quality: Option<EditImageBodyJsonParamQuality>,
    /// Controls fidelity to the original input image(s).
    pub input_fidelity: Option<EditImageBodyJsonParamInputFidelity>,
    /// Requested output image size.
    pub size: Option<EditImageBodyJsonParamSize>,
    /// A unique identifier representing your end-user, which can help OpenAI
    /// monitor and detect abuse.
    pub user: Option<String>,
    /// Output image format. Supported for GPT image models.
    pub output_format: Option<EditImageBodyJsonParamOutputFormat>,
    /// Compression level for `jpeg` or `webp` output.
    pub output_compression: Option<i64>,
    /// Moderation level for GPT image models.
    pub moderation: Option<EditImageBodyJsonParamModeration>,
    /// Background behavior for generated image output.
    pub background: Option<EditImageBodyJsonParamBackground>,
    /// Stream partial image results as events.
    pub stream: Option<bool>,
    pub partial_images: Option<PartialImages>,
}

pub struct ImagesGenerations {
    transport: Arc<Transport>,
}

impl ImagesGenerations {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        ImagesGenerations { transport }
    }

    /// Creates an image given a prompt. [Learn more](/docs/guides/images).
    pub async fn create(&self, params: ImagesGenerationsCreateParams) -> Result<ImagesResponse, Error> {
        let mut req = self.transport.request(reqwest::Method::POST, "/images/generations");
        if let Some(value) = &params.prompt {
            req = req.json_field("prompt", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.model {
            req = req.json_field("model", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.n {
            req = req.json_field("n", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.quality {
            req = req.json_field("quality", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.response_format {
            req = req.json_field("response_format", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.output_format {
            req = req.json_field("output_format", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.output_compression {
            req = req.json_field("output_compression", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.stream {
            req = req.json_field("stream", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.partial_images {
            req = req.json_field("partial_images", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.size {
            req = req.json_field("size", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.moderation {
            req = req.json_field("moderation", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.background {
            req = req.json_field("background", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.style {
            req = req.json_field("style", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.user {
            req = req.json_field("user", serde_json::to_value(value)?);
        }
        req.send().await
    }
}

#[derive(Debug, Clone, Default)]
pub struct ImagesGenerationsCreateParams {
    /// A text description of the desired image(s). The maximum length is 32000 characters for the GPT image models, 1000 characters for `dall-e-2` and 4000 characters for `dall-e-3`.
    pub prompt: Option<String>,
    /// The model to use for image generation. One of `dall-e-2`, `dall-e-3`, or a GPT image model (`gpt-image-1`, `gpt-image-1-mini`, `gpt-image-1.5`). Defaults to `dall-e-2` unless a parameter specific to the GPT image models is used.
    pub model: Option<CreateImageRequestModel>,
    /// The number of images to generate. Must be between 1 and 10. For `dall-e-3`, only `n=1` is supported.
    pub n: Option<i64>,
    /// The quality of the image that will be generated.
    ///
    /// - `auto` (default value) will automatically select the best quality for the given model.
    /// - `high`, `medium` and `low` are supported for the GPT image models.
    /// - `hd` and `standard` are supported for `dall-e-3`.
    /// - `standard` is the only option for `dall-e-2`.
    pub quality: Option<CreateImageRequestQuality>,
    /// The format in which generated images with `dall-e-2` and `dall-e-3` are returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes after the image has been generated. This parameter isn't supported for the GPT image models, which always return base64-encoded images.
    pub response_format: Option<CreateImageRequestResponseFormat>,
    /// The format in which the generated images are returned. This parameter is only supported for the GPT image models. Must be one of `png`, `jpeg`, or `webp`.
    pub output_format: Option<CreateImageRequestOutputFormat>,
    /// The compression level (0-100%) for the generated images. This parameter is only supported for the GPT image models with the `webp` or `jpeg` output formats, and defaults to 100.
    pub output_compression: Option<i64>,
    /// Generate the image in streaming mode. Defaults to `false`. See the
    /// [Image generation guide](/docs/guides/image-generation) for more information.
    /// This parameter is only supported for the GPT image models.
    pub stream: Option<bool>,
    pub partial_images: Option<PartialImages>,
    /// The size of the generated images. For `gpt-image-2` and `gpt-image-2-2026-04-21`, arbitrary resolutions are supported as `WIDTHxHEIGHT` strings, for example `1536x864`. Width and height must both be divisible by 16 and the requested aspect ratio must be between 1:3 and 3:1. Resolutions above `2560x1440` are experimental, and the maximum supported resolution is `3840x2160`. The requested size must also satisfy the model's current pixel and edge limits. The standard sizes `1024x1024`, `1536x1024`, and `1024x1536` are supported by the GPT image models; `auto` is supported for models that allow automatic sizing. For `dall-e-2`, use one of `256x256`, `512x512`, or `1024x1024`. For `dall-e-3`, use one of `1024x1024`, `1792x1024`, or `1024x1792`.
    pub size: Option<CreateImageRequestSize>,
    /// Control the content-moderation level for images generated by the GPT image models. Must be either `low` for less restrictive filtering or `auto` (default value).
    pub moderation: Option<CreateImageRequestModeration>,
    /// Allows to set transparency for the background of the generated image(s).
    /// This parameter is only supported for the GPT image models. Must be one of
    /// `transparent`, `opaque` or `auto` (default value). When `auto` is used, the
    /// model will automatically determine the best background for the image.
    ///
    /// If `transparent`, the output format needs to support transparency, so it
    /// should be set to either `png` (default value) or `webp`.
    pub background: Option<CreateImageRequestBackground>,
    /// The style of the generated images. This parameter is only supported for `dall-e-3`. Must be one of `vivid` or `natural`. Vivid causes the model to lean towards generating hyper-real and dramatic images. Natural causes the model to produce more natural, less hyper-real looking images.
    pub style: Option<CreateImageRequestStyle>,
    /// A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices#end-user-ids).
    pub user: Option<String>,
}

pub struct ImagesVariations {
    transport: Arc<Transport>,
}

impl ImagesVariations {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        ImagesVariations { transport }
    }

    /// Creates a variation of a given image. This endpoint only supports `dall-e-2`.
    pub async fn create(&self, params: ImagesVariationsCreateParams) -> Result<ImagesResponse, Error> {
        let mut req = self.transport.request(reqwest::Method::POST, "/images/variations");
        if let Some(value) = &params.image {
            req = req.multipart_file("image", value.clone());
        }
        if let Some(value) = &params.model {
            req = req.multipart_json("model", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.n {
            req = req.multipart_json("n", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.response_format {
            req = req.multipart_json("response_format", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.size {
            req = req.multipart_json("size", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.user {
            req = req.multipart_json("user", serde_json::to_value(value)?);
        }
        req.send().await
    }
}

#[derive(Debug, Clone, Default)]
pub struct ImagesVariationsCreateParams {
    /// The image to use as the basis for the variation(s). Must be a valid PNG file, less than 4MB, and square.
    pub image: Option<Vec<u8>>,
    /// The model to use for image generation. Only `dall-e-2` is supported at this time.
    pub model: Option<CreateImageVariationRequestModel>,
    /// The number of images to generate. Must be between 1 and 10.
    pub n: Option<i64>,
    /// The format in which the generated images are returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes after the image has been generated.
    pub response_format: Option<CreateImageVariationRequestResponseFormat>,
    /// The size of the generated images. Must be one of `256x256`, `512x512`, or `1024x1024`.
    pub size: Option<CreateImageVariationRequestSize>,
    /// A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices#end-user-ids).
    pub user: Option<String>,
}
