// Code generated by opensdk. DO NOT EDIT.

use std::sync::Arc;

use crate::error::Error;
use crate::models::*;
use crate::transport::{Page, Transport};

pub struct VectorStores {
    transport: Arc<Transport>,
}

impl VectorStores {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        VectorStores { transport }
    }

    pub fn file_batches(&self) -> VectorStoresFileBatches {
        VectorStoresFileBatches::new(self.transport.clone())
    }

    pub fn files(&self) -> VectorStoresFiles {
        VectorStoresFiles::new(self.transport.clone())
    }

    /// Create a vector store.
    pub async fn create(&self, params: VectorStoresCreateParams) -> Result<VectorStoreObject, Error> {
        let mut req = self.transport.request(reqwest::Method::POST, "/vector_stores");
        if let Some(value) = &params.file_ids {
            req = req.json_field("file_ids", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.name {
            req = req.json_field("name", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.description {
            req = req.json_field("description", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.expires_after {
            req = req.json_field("expires_after", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.chunking_strategy {
            req = req.json_field("chunking_strategy", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.metadata {
            req = req.json_field("metadata", serde_json::to_value(value)?);
        }
        req.send().await
    }

    /// Delete a vector store.
    pub async fn delete(&self, vector_store_id: &str) -> Result<DeleteVectorStoreResponse, Error> {
        if vector_store_id.is_empty() {
            return Err(Error::InvalidArgument("vector_store_id".to_string()));
        }

        let req = self.transport.request(reqwest::Method::DELETE, format!("/vector_stores/{}", vector_store_id));
        req.send().await
    }

    /// Returns a list of vector stores.
    pub async fn list(&self, params: VectorStoresListParams) -> Result<Page<VectorStoreObject>, Error> {
        let mut req = self.transport.request(reqwest::Method::GET, "/vector_stores");
        if let Some(value) = &params.limit {
            req = req.query("limit", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.order {
            req = req.query("order", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.after {
            req = req.query("after", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.before {
            req = req.query("before", serde_json::to_value(value)?);
        }
        let value = req.send_value().await?;
        Page::from_value(value, "data", Some("has_more"))
    }

    /// Retrieves a vector store.
    pub async fn retrieve(&self, vector_store_id: &str) -> Result<VectorStoreObject, Error> {
        if vector_store_id.is_empty() {
            return Err(Error::InvalidArgument("vector_store_id".to_string()));
        }

        let req = self.transport.request(reqwest::Method::GET, format!("/vector_stores/{}", vector_store_id));
        req.send().await
    }

    /// Search a vector store for relevant chunks based on a query and file attributes filter.
    pub async fn search(&self, vector_store_id: &str, params: VectorStoresSearchParams) -> Result<Page<VectorStoreSearchResultItem>, Error> {
        if vector_store_id.is_empty() {
            return Err(Error::InvalidArgument("vector_store_id".to_string()));
        }

        let mut req = self.transport.request(reqwest::Method::POST, format!("/vector_stores/{}/search", vector_store_id));
        if let Some(value) = &params.query {
            req = req.json_field("query", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.rewrite_query {
            req = req.json_field("rewrite_query", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.max_num_results {
            req = req.json_field("max_num_results", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.filters {
            req = req.json_field("filters", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.ranking_options {
            req = req.json_field("ranking_options", serde_json::to_value(value)?);
        }
        let value = req.send_value().await?;
        Page::from_value(value, "data", Some("has_more"))
    }

    /// Modifies a vector store.
    pub async fn update(&self, vector_store_id: &str, params: VectorStoresUpdateParams) -> Result<VectorStoreObject, Error> {
        if vector_store_id.is_empty() {
            return Err(Error::InvalidArgument("vector_store_id".to_string()));
        }

        let mut req = self.transport.request(reqwest::Method::POST, format!("/vector_stores/{}", vector_store_id));
        if let Some(value) = &params.name {
            req = req.json_field("name", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.expires_after {
            req = req.json_field("expires_after", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.metadata {
            req = req.json_field("metadata", serde_json::to_value(value)?);
        }
        req.send().await
    }
}

#[derive(Debug, Clone, Default)]
pub struct VectorStoresCreateParams {
    /// A list of [File](/docs/api-reference/files) IDs that the vector store should use. Useful for tools like `file_search` that can access files.
    pub file_ids: Option<Vec<String>>,
    /// The name of the vector store.
    pub name: Option<String>,
    /// A description for the vector store. Can be used to describe the vector store's purpose.
    pub description: Option<String>,
    pub expires_after: Option<VectorStoreExpirationAfter>,
    /// The chunking strategy used to chunk the file(s). If not set, will use the `auto` strategy. Only applicable if `file_ids` is non-empty.
    pub chunking_strategy: Option<CreateVectorStoreRequestChunkingStrategy>,
    pub metadata: Option<Metadata>,
}

#[derive(Debug, Clone, Default)]
pub struct VectorStoresListParams {
    /// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 20.
    pub limit: Option<i64>,
    /// Sort order by the `created_at` timestamp of the objects. `asc` for ascending order and `desc` for descending order.
    pub order: Option<VectorStoresListOrder>,
    /// A cursor for use in pagination. `after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with obj_foo, your subsequent call can include after=obj_foo in order to fetch the next page of the list.
    pub after: Option<String>,
    /// A cursor for use in pagination. `before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with obj_foo, your subsequent call can include before=obj_foo in order to fetch the previous page of the list.
    pub before: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct VectorStoresSearchParams {
    /// A query string for a search
    pub query: Option<VectorStoreSearchRequestQuery>,
    /// Whether to rewrite the natural language query for vector search.
    pub rewrite_query: Option<bool>,
    /// The maximum number of results to return. This number should be between 1 and 50 inclusive.
    pub max_num_results: Option<i64>,
    /// A filter to apply based on file attributes.
    pub filters: Option<VectorStoreSearchRequestFilters>,
    /// Ranking options for search.
    pub ranking_options: Option<VectorStoreSearchRequestRankingOptions>,
}

#[derive(Debug, Clone, Default)]
pub struct VectorStoresUpdateParams {
    /// The name of the vector store.
    pub name: Option<String>,
    pub expires_after: Option<VectorStoreExpirationAfter>,
    pub metadata: Option<Metadata>,
}

pub struct VectorStoresFileBatches {
    transport: Arc<Transport>,
}

impl VectorStoresFileBatches {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        VectorStoresFileBatches { transport }
    }

    /// Cancel a vector store file batch. This attempts to cancel the processing of files in this batch as soon as possible.
    pub async fn cancel(&self, vector_store_id: &str, batch_id: &str) -> Result<VectorStoreFileBatchObject, Error> {
        if vector_store_id.is_empty() {
            return Err(Error::InvalidArgument("vector_store_id".to_string()));
        }
        if batch_id.is_empty() {
            return Err(Error::InvalidArgument("batch_id".to_string()));
        }

        let req = self.transport.request(reqwest::Method::POST, format!("/vector_stores/{}/file_batches/{}/cancel", vector_store_id, batch_id));
        req.send().await
    }

    /// The maximum number of files in a single batch request is 2000.
    /// Vector store file attach requests are rate limited per vector store (300 requests per minute across both this endpoint and `/vector_stores/{vector_store_id}/files`).
    /// For ingesting multiple files into the same vector store, this batch endpoint is recommended.
    pub async fn create(&self, vector_store_id: &str) -> Result<VectorStoreFileBatchObject, Error> {
        if vector_store_id.is_empty() {
            return Err(Error::InvalidArgument("vector_store_id".to_string()));
        }

        let req = self.transport.request(reqwest::Method::POST, format!("/vector_stores/{}/file_batches", vector_store_id));
        req.send().await
    }

    /// Returns a list of vector store files in a batch.
    pub async fn list_files(&self, vector_store_id: &str, batch_id: &str, params: VectorStoresFileBatchesListFilesParams) -> Result<Page<VectorStoreFileObject>, Error> {
        if vector_store_id.is_empty() {
            return Err(Error::InvalidArgument("vector_store_id".to_string()));
        }
        if batch_id.is_empty() {
            return Err(Error::InvalidArgument("batch_id".to_string()));
        }

        let mut req = self.transport.request(reqwest::Method::GET, format!("/vector_stores/{}/file_batches/{}/files", vector_store_id, batch_id));
        if let Some(value) = &params.limit {
            req = req.query("limit", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.order {
            req = req.query("order", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.after {
            req = req.query("after", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.before {
            req = req.query("before", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.filter {
            req = req.query("filter", serde_json::to_value(value)?);
        }
        let value = req.send_value().await?;
        Page::from_value(value, "data", Some("has_more"))
    }

    /// Retrieves a vector store file batch.
    pub async fn retrieve(&self, vector_store_id: &str, batch_id: &str) -> Result<VectorStoreFileBatchObject, Error> {
        if vector_store_id.is_empty() {
            return Err(Error::InvalidArgument("vector_store_id".to_string()));
        }
        if batch_id.is_empty() {
            return Err(Error::InvalidArgument("batch_id".to_string()));
        }

        let req = self.transport.request(reqwest::Method::GET, format!("/vector_stores/{}/file_batches/{}", vector_store_id, batch_id));
        req.send().await
    }
}

#[derive(Debug, Clone, Default)]
pub struct VectorStoresFileBatchesListFilesParams {
    /// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 20.
    pub limit: Option<i64>,
    /// Sort order by the `created_at` timestamp of the objects. `asc` for ascending order and `desc` for descending order.
    pub order: Option<VectorStoresFileBatchesListFilesOrder>,
    /// A cursor for use in pagination. `after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with obj_foo, your subsequent call can include after=obj_foo in order to fetch the next page of the list.
    pub after: Option<String>,
    /// A cursor for use in pagination. `before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with obj_foo, your subsequent call can include before=obj_foo in order to fetch the previous page of the list.
    pub before: Option<String>,
    /// Filter by file status. One of `in_progress`, `completed`, `failed`, `cancelled`.
    pub filter: Option<VectorStoresFileBatchesListFilesFilter>,
}

pub struct VectorStoresFiles {
    transport: Arc<Transport>,
}

impl VectorStoresFiles {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        VectorStoresFiles { transport }
    }

    /// Retrieve the parsed contents of a vector store file.
    pub async fn content(&self, vector_store_id: &str, file_id: &str) -> Result<Page<VectorStoreFileContentResponseDataItem>, Error> {
        if vector_store_id.is_empty() {
            return Err(Error::InvalidArgument("vector_store_id".to_string()));
        }
        if file_id.is_empty() {
            return Err(Error::InvalidArgument("file_id".to_string()));
        }

        let req = self.transport.request(reqwest::Method::GET, format!("/vector_stores/{}/files/{}/content", vector_store_id, file_id));
        let value = req.send_value().await?;
        Page::from_value(value, "data", Some("has_more"))
    }

    /// This endpoint is subject to a per-vector-store write rate limit of 300 requests per minute, shared with `/vector_stores/{vector_store_id}/file_batches`.
    /// For uploading multiple files to the same vector store, use the file batches endpoint to reduce request volume.
    pub async fn create(&self, vector_store_id: &str, params: VectorStoresFilesCreateParams) -> Result<VectorStoreFileObject, Error> {
        if vector_store_id.is_empty() {
            return Err(Error::InvalidArgument("vector_store_id".to_string()));
        }

        let mut req = self.transport.request(reqwest::Method::POST, format!("/vector_stores/{}/files", vector_store_id));
        if let Some(value) = &params.file_id {
            req = req.json_field("file_id", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.chunking_strategy {
            req = req.json_field("chunking_strategy", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.attributes {
            req = req.json_field("attributes", serde_json::to_value(value)?);
        }
        req.send().await
    }

    /// Delete a vector store file. This will remove the file from the vector store but the file itself will not be deleted. To delete the file, use the [delete file](/docs/api-reference/files/delete) endpoint.
    pub async fn delete(&self, vector_store_id: &str, file_id: &str) -> Result<DeleteVectorStoreFileResponse, Error> {
        if vector_store_id.is_empty() {
            return Err(Error::InvalidArgument("vector_store_id".to_string()));
        }
        if file_id.is_empty() {
            return Err(Error::InvalidArgument("file_id".to_string()));
        }

        let req = self.transport.request(reqwest::Method::DELETE, format!("/vector_stores/{}/files/{}", vector_store_id, file_id));
        req.send().await
    }

    /// Returns a list of vector store files.
    pub async fn list(&self, vector_store_id: &str, params: VectorStoresFilesListParams) -> Result<Page<VectorStoreFileObject>, Error> {
        if vector_store_id.is_empty() {
            return Err(Error::InvalidArgument("vector_store_id".to_string()));
        }

        let mut req = self.transport.request(reqwest::Method::GET, format!("/vector_stores/{}/files", vector_store_id));
        if let Some(value) = &params.limit {
            req = req.query("limit", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.order {
            req = req.query("order", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.after {
            req = req.query("after", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.before {
            req = req.query("before", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.filter {
            req = req.query("filter", serde_json::to_value(value)?);
        }
        let value = req.send_value().await?;
        Page::from_value(value, "data", Some("has_more"))
    }

    /// Retrieves a vector store file.
    pub async fn retrieve(&self, vector_store_id: &str, file_id: &str) -> Result<VectorStoreFileObject, Error> {
        if vector_store_id.is_empty() {
            return Err(Error::InvalidArgument("vector_store_id".to_string()));
        }
        if file_id.is_empty() {
            return Err(Error::InvalidArgument("file_id".to_string()));
        }

        let req = self.transport.request(reqwest::Method::GET, format!("/vector_stores/{}/files/{}", vector_store_id, file_id));
        req.send().await
    }

    /// Update attributes on a vector store file.
    pub async fn update(&self, vector_store_id: &str, file_id: &str, params: VectorStoresFilesUpdateParams) -> Result<VectorStoreFileObject, Error> {
        if vector_store_id.is_empty() {
            return Err(Error::InvalidArgument("vector_store_id".to_string()));
        }
        if file_id.is_empty() {
            return Err(Error::InvalidArgument("file_id".to_string()));
        }

        let mut req = self.transport.request(reqwest::Method::POST, format!("/vector_stores/{}/files/{}", vector_store_id, file_id));
        if let Some(value) = &params.attributes {
            req = req.json_field("attributes", serde_json::to_value(value)?);
        }
        req.send().await
    }
}

#[derive(Debug, Clone, Default)]
pub struct VectorStoresFilesCreateParams {
    /// A [File](/docs/api-reference/files) ID that the vector store should use. Useful for tools like `file_search` that can access files. For multi-file ingestion, we recommend [`file_batches`](/docs/api-reference/vector-stores-file-batches/createBatch) to minimize per-vector-store write requests.
    pub file_id: Option<String>,
    pub chunking_strategy: Option<ChunkingStrategyRequestParam>,
    pub attributes: Option<VectorStoreFileAttributes>,
}

#[derive(Debug, Clone, Default)]
pub struct VectorStoresFilesListParams {
    /// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 20.
    pub limit: Option<i64>,
    /// Sort order by the `created_at` timestamp of the objects. `asc` for ascending order and `desc` for descending order.
    pub order: Option<VectorStoresFilesListOrder>,
    /// A cursor for use in pagination. `after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with obj_foo, your subsequent call can include after=obj_foo in order to fetch the next page of the list.
    pub after: Option<String>,
    /// A cursor for use in pagination. `before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with obj_foo, your subsequent call can include before=obj_foo in order to fetch the previous page of the list.
    pub before: Option<String>,
    /// Filter by file status. One of `in_progress`, `completed`, `failed`, `cancelled`.
    pub filter: Option<VectorStoresFilesListFilter>,
}

#[derive(Debug, Clone, Default)]
pub struct VectorStoresFilesUpdateParams {
    pub attributes: Option<VectorStoreFileAttributes>,
}
