// Code generated by opencli2rust. DO NOT EDIT.

use std::process::ExitCode;

use clap::{Arg, ArgMatches, Command};

use crate::gen::runtime::{self, CliOverrides, Context};

pub fn command() -> Command {
    Command::new("containers")
        .subcommand_required(true)
        .arg_required_else_help(true)
        .subcommand(
            Command::new("create")
                .about("Create Container")
                .arg(
                    Arg::new("name")
                        .long("name")
                        .help("Name of the container to create.")
                        .required(true),
                )
                .arg(
                    Arg::new("file-ids")
                        .long("file-ids")
                        .action(clap::ArgAction::Append)
                        .value_delimiter(',')
                        .help("IDs of files to copy to the container."),
                )
                .arg(
                    Arg::new("expires-after")
                        .long("expires-after")
                        .help("Container expiration time in seconds relative to the 'anchor' time."),
                )
                .arg(
                    Arg::new("skills")
                        .long("skills")
                        .action(clap::ArgAction::Append)
                        .value_delimiter(',')
                        .help("An optional list of skills referenced by id or inline data."),
                )
                .arg(
                    Arg::new("memory-limit")
                        .long("memory-limit")
                        .help("Optional memory limit for the container. Defaults to \"1g\"."),
                )
                .arg(
                    Arg::new("network-policy")
                        .long("network-policy")
                        .help("Network access policy for the container."),
                ),
        )
}

pub async fn run<O: CliOverrides>(ctx: &Context, o: &O, cmd_path: &[String], m: &ArgMatches) -> ExitCode {
    let parts: Vec<&str> = cmd_path.iter().map(String::as_str).collect();
    match parts.as_slice() {
        ["containers", "create"] => handle_containers_create(ctx, o, cmd_path, m).await,
        _ => {
            eprintln!("error: unknown command: {}", cmd_path.join(" "));
            ExitCode::FAILURE
        }
    }
}

async fn handle_containers_create<O: CliOverrides>(
    ctx: &Context,
    o: &O,
    cmd_path: &[String],
    m: &ArgMatches,
) -> ExitCode {
    let path = "/containers".to_string();
    let mut body = serde_json::Map::new();
    if let Some(v) = m.get_one::<String>("name") {
        body.insert("name".to_string(), serde_json::Value::String(v.clone()));
    }
    if let Some(vs) = m.get_many::<String>("file-ids") {
        body.insert("file_ids".to_string(), serde_json::Value::Array(vs.cloned().map(serde_json::Value::String).collect()));
    }
    if let Some(v) = m.get_one::<String>("expires-after") {
        let value = serde_json::from_str::<serde_json::Value>(v)
            .unwrap_or_else(|_| serde_json::Value::String(v.clone()));
        body.insert("expires_after".to_string(), value);
    }
    if let Some(vs) = m.get_many::<String>("skills") {
        body.insert("skills".to_string(), serde_json::Value::Array(vs.cloned().map(serde_json::Value::String).collect()));
    }
    if let Some(v) = m.get_one::<String>("memory-limit") {
        body.insert("memory_limit".to_string(), serde_json::Value::String(v.clone()));
    }
    if let Some(v) = m.get_one::<String>("network-policy") {
        let value = serde_json::from_str::<serde_json::Value>(v)
            .unwrap_or_else(|_| serde_json::Value::String(v.clone()));
        body.insert("network_policy".to_string(), value);
    }
    let body_bytes = match serde_json::to_vec(&serde_json::Value::Object(body)) {
        Ok(bytes) => bytes,
        Err(err) => return o.print_error(cmd_path, &runtime::Error::Invalid(err.to_string())),
    };
    let req = runtime::Request {
        method: "POST",
        path,
        query: Vec::new(),
        headers: Vec::new(),
        body: Some(body_bytes),
    };
    runtime::run_request(ctx, o, cmd_path, req).await
}
