// Code generated by opensdk. DO NOT EDIT.

use std::sync::Arc;

use crate::error::Error;
use crate::models::*;
use crate::transport::{Page, Transport};

pub struct Responses {
    transport: Arc<Transport>,
}

impl Responses {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        Responses { transport }
    }

    pub fn input_items(&self) -> ResponsesInputItems {
        ResponsesInputItems::new(self.transport.clone())
    }
}

pub struct ResponsesInputItems {
    transport: Arc<Transport>,
}

impl ResponsesInputItems {
    pub(crate) fn new(transport: Arc<Transport>) -> Self {
        ResponsesInputItems { transport }
    }

    /// Returns a list of input items for a given response.
    pub async fn list(&self, response_id: &str, params: ResponsesInputItemsListParams) -> Result<Page<ItemResource>, Error> {
        if response_id.is_empty() {
            return Err(Error::InvalidArgument("response_id".to_string()));
        }

        let mut req = self.transport.request(reqwest::Method::GET, format!("/responses/{}/input_items", response_id));
        if let Some(value) = &params.limit {
            req = req.query("limit", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.order {
            req = req.query("order", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.after {
            req = req.query("after", serde_json::to_value(value)?);
        }
        if let Some(value) = &params.include {
            req = req.query("include", serde_json::to_value(value)?);
        }
        let value = req.send_value().await?;
        Page::from_value(value, "data", Some("has_more"))
    }
}

#[derive(Debug, Clone, Default)]
pub struct ResponsesInputItemsListParams {
    /// A limit on the number of objects to be returned. Limit can range between
    /// 1 and 100, and the default is 20.
    pub limit: Option<i64>,
    /// The order to return the input items in. Default is `desc`.
    /// - `asc`: Return the input items in ascending order.
    /// - `desc`: Return the input items in descending order.
    pub order: Option<ResponsesInputItemsListOrder>,
    /// An item ID to list items after, used in pagination.
    pub after: Option<String>,
    /// Additional fields to include in the response. See the `include`
    /// parameter for Response creation above for more information.
    pub include: Option<Vec<IncludeEnum>>,
}
