//! `xyd_opensdk_node` — pure Rust port of the `@xyd-js/opensdk-node` emitter
//! (OpenSDK IR → an openai-node-shaped TypeScript SDK). W7 of the S6+ Rust
//! migration.
//!
//! Scope: the full buildable-SDK file tree — `package.json` / `tsconfig.json` /
//! `README.md`, `src/index.ts`, `src/client.ts`, `src/models.ts`,
//! `src/resources/index.ts`, `src/resources/<resource>.ts`, the vendored
//! dependency-free `src/core/**` runtime (error/resource/request + optional
//! pagination), and the generated `tests/**` suite (`tsconfig.test.json`,
//! `_shims.d.ts`, `setup.ts`, one `<resource>.test.ts` per top-level resource).
//! Deferred (not ported here): the optional busybox helpers, `publish.ts`, and
//! the napi surface + JS shim.
//!
//! Entry point: [`generate_node`] — pure, IR JSON in, virtual file map out.

use std::collections::BTreeMap;

mod behavior;
mod cli;
mod client;
mod example;
mod example_plan;
mod ir;
mod jsrt;
mod model;
mod plan;
mod project;
mod resource;
mod runtime;
mod tests_gen;

use ir::{Resource, Spec};
use resource::NodeCtx;

/// The machine-ownership marker prepended (as `// …`) to every generated `.ts`
/// file — matches `nodeEmitter.fileHeader()`.
const FILE_HEADER: &str = "Code generated by opensdk. DO NOT EDIT.";

/// Generate the buildable Node SDK's generated-code files from an OpenSDK IR
/// document. Returns a virtual file map `{ relativePath: contents }` (the
/// framework orchestrator's contract, minus the deferred runtime/test files).
pub fn generate_node(spec_json: &serde_json::Value) -> BTreeMap<String, String> {
    let spec: Spec = serde_json::from_value(spec_json.clone())
        .expect("OpenSDK IR did not match the expected shape");
    if xyd_opensdk_cli_common::is_cli_spec(spec_json) {
        return cli::generate_cli(&spec, spec_json);
    }
    generate_from_spec(&spec, spec_json)
}

/// Whether some method returns a vendored page container (gates `pagination.ts`).
fn uses_pagination(resources: &[Resource], types: &[&ir::NamedType]) -> bool {
    resources.iter().any(|r| {
        r.methods
            .iter()
            .any(|m| plan::plan_operation(m, types).page_name.is_some())
            || uses_pagination(&r.resources, types)
    })
}

fn generate_from_spec(spec: &Spec, spec_json: &serde_json::Value) -> BTreeMap<String, String> {
    let opts = project::resolve_node_options(spec);
    let error_classes = behavior::error_class_names(spec);
    let types: Vec<&ir::NamedType> = spec.types.iter().collect();
    let auto_generate_for_post = spec
        .sdk
        .as_ref()
        .and_then(|s| s.idempotency.as_ref())
        .and_then(|i| i.auto_generate_for_post)
        .unwrap_or(true);
    let ctx = NodeCtx {
        types,
        auto_generate_for_post,
    };

    let mut files: BTreeMap<String, String> = BTreeMap::new();
    let mut add = |path: &str, content: String| {
        let content = with_file_header(path, content);
        if files.insert(path.to_string(), content).is_some() {
            panic!("emitter \"node\": re-emitted {path}");
        }
    };

    // generateProject (no ownership header on .json / .md)
    add("package.json", project::package_json(&opts.pkg, spec));
    add("tsconfig.json", project::tsconfig_json());
    add(
        "README.md",
        project::readme(&opts.pkg, spec, &opts.client_name, opts.default_export),
    );

    // generateClient
    add(
        "src/index.ts",
        client::render_root_index_file(
            spec,
            &error_classes,
            &opts.client_name,
            opts.default_export,
        ),
    );
    add(
        "src/client.ts",
        client::render_client_file(spec, &opts.env_var, &opts.client_name),
    );

    // generateTypes
    add("src/models.ts", model::render_models_file(spec));

    // generateResources
    if !spec.resources.is_empty() {
        for r in &spec.resources {
            let (path, content) = resource::render_resource_file(r, &ctx);
            add(&path, content);
        }
        add(
            "src/resources/index.ts",
            resource::render_resources_index_file(&spec.resources),
        );
    }

    // generateRuntime — the vendored dependency-free fetch runtime. pagination.ts
    // is included only when some list method returns a vendored page container.
    let with_pagination = uses_pagination(&spec.resources, &ctx.types);
    for (path, content) in
        runtime::runtime_files(spec_json, &opts.base_url, &opts.pkg, with_pagination)
    {
        add(&path, content);
    }

    // generateTests — the SDK's own openai-node-shaped suite (default ON).
    for (path, content) in tests_gen::test_files(
        &spec.resources,
        &ctx,
        &opts.client_name,
        opts.default_export,
    ) {
        add(&path, content);
    }

    files
}

/// The dot-extension of a rel path ('' for none/dotfiles).
fn file_extension(rel_path: &str) -> &str {
    let base = rel_path.rsplit('/').next().unwrap_or(rel_path);
    match base.rfind('.') {
        Some(dot) if dot > 0 => &base[dot..],
        _ => "",
    }
}

/// Prepend the rendered ownership header + one blank line for `.ts` files
/// (other extensions have no idiomatic comment here → untouched).
pub(crate) fn with_file_header(rel_path: &str, content: String) -> String {
    // Only .ts is produced by this generator; keep the ext gate faithful.
    let prefix = match file_extension(rel_path) {
        ".ts" | ".js" => "// ",
        _ => return content,
    };
    let rendered = format!("{prefix}{FILE_HEADER}");
    if content.starts_with(&rendered) {
        content
    } else {
        format!("{rendered}\n\n{content}")
    }
}
