// Code generated by opencli2rust. DO NOT EDIT.

mod custom;
mod gen;

#[tokio::main]
async fn main() -> std::process::ExitCode {
    let mut commands = gen::runtime::CustomCommands::new();
    custom::register(&mut commands);
    let mut actions = gen::runtime::Actions::new();
    gen::runtime::bind::<custom::Custom>(&mut actions);
    gen::cli::run(custom::overrides(), commands, actions).await
}
