# Code generated by opensdk. DO NOT EDIT.

from __future__ import annotations

from typing import Any, Optional

from ._transport import Transport, decode
from .models import *  # noqa: F401,F403


class FineTuningResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport
        self.alpha = AlphaResource(transport)


class AlphaResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport
        self.graders = GradersResource(transport)


class GradersResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport
        self.run = RunResource(transport)


class RunResource:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def create(self, *, grader: RunGraderRequestGrader, item: Optional[dict[str, Any]] = None, model_sample: str) -> RunGraderResponse:
        return decode(RunGraderResponse, self._transport.request("POST", "/fine_tuning/alpha/graders/run", body={"grader": grader, "item": item, "model_sample": model_sample}))
